// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (
    id,
    email,
    password_hash,
    oidc_provider,
    oidc_subject,
    is_active,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING id, email, password_hash, oidc_provider, oidc_subject, is_active, created_at, updated_at
`

type CreateAccountParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash *string   `json:"password_hash"`
	OidcProvider *string   `json:"oidc_provider"`
	OidcSubject  *string   `json:"oidc_subject"`
	IsActive     bool      `json:"is_active"`
}

// sql/queries/account.sql
// Account queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.OidcProvider,
		arg.OidcSubject,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :exec
UPDATE accounts
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAccount, id)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, password_hash, oidc_provider, oidc_subject, is_active, created_at, updated_at FROM accounts
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, password_hash, oidc_provider, oidc_subject, is_active, created_at, updated_at FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    email      = COALESCE($2, email),
    is_active  = COALESCE($3, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, oidc_provider, oidc_subject, is_active, created_at, updated_at
`

type UpdateAccountParams struct {
	ID       uuid.UUID `json:"id"`
	Email    *string   `json:"email"`
	IsActive *bool     `json:"is_active"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Email, arg.IsActive)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
