// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec

INSERT INTO audit_entries (
    id,
    household_id,
    actor_member_id,
    actor_account_id,
    action,
    entity_type,
    entity_id,
    details,
    device_info,
    ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type InsertAuditEntryParams struct {
	ID             uuid.UUID      `json:"id"`
	HouseholdID    uuid.UUID      `json:"household_id"`
	ActorMemberID  *uuid.NullUUID `json:"actor_member_id"`
	ActorAccountID *uuid.NullUUID `json:"actor_account_id"`
	Action         string         `json:"action"`
	EntityType     string         `json:"entity_type"`
	EntityID       uuid.UUID      `json:"entity_id"`
	Details        []byte         `json:"details"`
	DeviceInfo     string         `json:"device_info"`
	IpAddress      *string        `json:"ip_address"`
}

// sql/queries/audit.sql
// Audit log queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.ID,
		arg.HouseholdID,
		arg.ActorMemberID,
		arg.ActorAccountID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.DeviceInfo,
		arg.IpAddress,
	)
	return err
}

const listAccountAudit = `-- name: ListAccountAudit :many
SELECT id, timestamp, household_id, actor_member_id, actor_account_id, action, entity_type, entity_id, details, device_info, ip_address FROM audit_entries
WHERE actor_account_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAccountAuditParams struct {
	ActorAccountID *uuid.NullUUID `json:"actor_account_id"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
}

func (q *Queries) ListAccountAudit(ctx context.Context, arg ListAccountAuditParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAccountAudit, arg.ActorAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.HouseholdID,
			&i.ActorMemberID,
			&i.ActorAccountID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.DeviceInfo,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdAudit = `-- name: ListHouseholdAudit :many
SELECT id, timestamp, household_id, actor_member_id, actor_account_id, action, entity_type, entity_id, details, device_info, ip_address FROM audit_entries
WHERE household_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListHouseholdAuditParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListHouseholdAudit(ctx context.Context, arg ListHouseholdAuditParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listHouseholdAudit, arg.HouseholdID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.HouseholdID,
			&i.ActorMemberID,
			&i.ActorAccountID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.DeviceInfo,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
