// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const insertBackupRecord = `-- name: InsertBackupRecord :one

INSERT INTO backup_records (
    id,
    type,
    destination,
    file_path,
    size_bytes,
    checksum_sha256,
    schema_version,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, created_at, type, destination, file_path, size_bytes, checksum_sha256, schema_version, status, s3_key
`

type InsertBackupRecordParams struct {
	ID             uuid.UUID `json:"id"`
	Type           string    `json:"type"`
	Destination    string    `json:"destination"`
	FilePath       string    `json:"file_path"`
	SizeBytes      int64     `json:"size_bytes"`
	ChecksumSha256 string    `json:"checksum_sha256"`
	SchemaVersion  string    `json:"schema_version"`
	Status         string    `json:"status"`
}

// sql/queries/backup.sql
// Backup record queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) InsertBackupRecord(ctx context.Context, arg InsertBackupRecordParams) (BackupRecord, error) {
	row := q.db.QueryRow(ctx, insertBackupRecord,
		arg.ID,
		arg.Type,
		arg.Destination,
		arg.FilePath,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.SchemaVersion,
		arg.Status,
	)
	var i BackupRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Type,
		&i.Destination,
		&i.FilePath,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.SchemaVersion,
		&i.Status,
		&i.S3Key,
	)
	return i, err
}

const listBackupRecords = `-- name: ListBackupRecords :many
SELECT id, created_at, type, destination, file_path, size_bytes, checksum_sha256, schema_version, status, s3_key FROM backup_records
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBackupRecordsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBackupRecords(ctx context.Context, arg ListBackupRecordsParams) ([]BackupRecord, error) {
	rows, err := q.db.Query(ctx, listBackupRecords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupRecord{}
	for rows.Next() {
		var i BackupRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Type,
			&i.Destination,
			&i.FilePath,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.SchemaVersion,
			&i.Status,
			&i.S3Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackupRecord = `-- name: UpdateBackupRecord :one
UPDATE backup_records
SET
    size_bytes      = COALESCE($2, size_bytes),
    checksum_sha256 = COALESCE($3, checksum_sha256),
    status          = COALESCE($4, status)
WHERE id = $1
RETURNING id, created_at, type, destination, file_path, size_bytes, checksum_sha256, schema_version, status, s3_key
`

type UpdateBackupRecordParams struct {
	ID             uuid.UUID `json:"id"`
	SizeBytes      *int64    `json:"size_bytes"`
	ChecksumSha256 *string   `json:"checksum_sha256"`
	Status         *string   `json:"status"`
}

func (q *Queries) UpdateBackupRecord(ctx context.Context, arg UpdateBackupRecordParams) (BackupRecord, error) {
	row := q.db.QueryRow(ctx, updateBackupRecord,
		arg.ID,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.Status,
	)
	var i BackupRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Type,
		&i.Destination,
		&i.FilePath,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.SchemaVersion,
		&i.Status,
		&i.S3Key,
	)
	return i, err
}

const updateBackupS3Key = `-- name: UpdateBackupS3Key :one
UPDATE backup_records
SET s3_key = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, type, destination, file_path, size_bytes, checksum_sha256, schema_version, status, s3_key
`

type UpdateBackupS3KeyParams struct {
	ID    uuid.UUID `json:"id"`
	S3Key *string   `json:"s3_key"`
}

func (q *Queries) UpdateBackupS3Key(ctx context.Context, arg UpdateBackupS3KeyParams) (BackupRecord, error) {
	row := q.db.QueryRow(ctx, updateBackupS3Key, arg.ID, arg.S3Key)
	var i BackupRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Type,
		&i.Destination,
		&i.FilePath,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.SchemaVersion,
		&i.Status,
		&i.S3Key,
	)
	return i, err
}
