// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chore_pets.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const addChorePet = `-- name: AddChorePet :exec

INSERT INTO chore_pets (chore_id, pet_id)
VALUES ($1, $2)
ON CONFLICT (chore_id, pet_id) DO NOTHING
`

type AddChorePetParams struct {
	ChoreID uuid.UUID `json:"chore_id"`
	PetID   uuid.UUID `json:"pet_id"`
}

// sql/queries/chore_pets.sql
// chore_pets join table queries: links chores to pet members.
// Section D of docs/specs/2026-05-01-fairplay-design.md.
func (q *Queries) AddChorePet(ctx context.Context, arg AddChorePetParams) error {
	_, err := q.db.Exec(ctx, addChorePet, arg.ChoreID, arg.PetID)
	return err
}

const clearChorePets = `-- name: ClearChorePets :exec
DELETE FROM chore_pets WHERE chore_id = $1
`

func (q *Queries) ClearChorePets(ctx context.Context, choreID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearChorePets, choreID)
	return err
}

const listChorePets = `-- name: ListChorePets :many
SELECT pet_id FROM chore_pets
WHERE chore_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChorePets(ctx context.Context, choreID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listChorePets, choreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var pet_id uuid.UUID
		if err := rows.Scan(&pet_id); err != nil {
			return nil, err
		}
		items = append(items, pet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPetMembersForHousehold = `-- name: ListPetMembersForHousehold :many
SELECT id FROM members
WHERE household_id = $1 AND role = 'pet'
`

func (q *Queries) ListPetMembersForHousehold(ctx context.Context, householdID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPetMembersForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChorePet = `-- name: RemoveChorePet :exec
DELETE FROM chore_pets
WHERE chore_id = $1 AND pet_id = $2
`

type RemoveChorePetParams struct {
	ChoreID uuid.UUID `json:"chore_id"`
	PetID   uuid.UUID `json:"pet_id"`
}

func (q *Queries) RemoveChorePet(ctx context.Context, arg RemoveChorePetParams) error {
	_, err := q.db.Exec(ctx, removeChorePet, arg.ChoreID, arg.PetID)
	return err
}
