// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chore.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveChore = `-- name: ArchiveChore :exec
UPDATE chores SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1 AND household_id = $2
`

type ArchiveChoreParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ArchiveChore(ctx context.Context, arg ArchiveChoreParams) error {
	_, err := q.db.Exec(ctx, archiveChore, arg.ID, arg.HouseholdID)
	return err
}

const closeChoreCompletionsForWeek = `-- name: CloseChoreCompletionsForWeek :exec
UPDATE chore_completions
SET closed = TRUE
WHERE member_id = $1
  AND date BETWEEN $2 AND $3
  AND closed = FALSE
`

type CloseChoreCompletionsForWeekParams struct {
	MemberID uuid.UUID   `json:"member_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

func (q *Queries) CloseChoreCompletionsForWeek(ctx context.Context, arg CloseChoreCompletionsForWeekParams) error {
	_, err := q.db.Exec(ctx, closeChoreCompletionsForWeek, arg.MemberID, arg.Date, arg.Date_2)
	return err
}

const createChore = `-- name: CreateChore :one

INSERT INTO chores (
    id, household_id, member_id, name, weight, frequency_kind, days_of_week, auto_approve, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
)
RETURNING id, household_id, member_id, name, weight, frequency_kind, days_of_week, auto_approve, archived_at, created_at, updated_at
`

type CreateChoreParams struct {
	ID            uuid.UUID `json:"id"`
	HouseholdID   uuid.UUID `json:"household_id"`
	MemberID      uuid.UUID `json:"member_id"`
	Name          string    `json:"name"`
	Weight        int32     `json:"weight"`
	FrequencyKind string    `json:"frequency_kind"`
	DaysOfWeek    []string  `json:"days_of_week"`
	AutoApprove   bool      `json:"auto_approve"`
}

// sql/queries/chore.sql
// Chore + ChoreCompletion queries.
func (q *Queries) CreateChore(ctx context.Context, arg CreateChoreParams) (Chore, error) {
	row := q.db.QueryRow(ctx, createChore,
		arg.ID,
		arg.HouseholdID,
		arg.MemberID,
		arg.Name,
		arg.Weight,
		arg.FrequencyKind,
		arg.DaysOfWeek,
		arg.AutoApprove,
	)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.Weight,
		&i.FrequencyKind,
		&i.DaysOfWeek,
		&i.AutoApprove,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChoreCompletion = `-- name: CreateChoreCompletion :one
INSERT INTO chore_completions (
    id, chore_id, member_id, date, approved, approved_by_account_id, payout_cents
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (chore_id, date) DO NOTHING
RETURNING id, chore_id, member_id, date, marked_at, approved, approved_by_account_id, payout_cents, closed
`

type CreateChoreCompletionParams struct {
	ID                  uuid.UUID      `json:"id"`
	ChoreID             uuid.UUID      `json:"chore_id"`
	MemberID            uuid.UUID      `json:"member_id"`
	Date                pgtype.Date    `json:"date"`
	Approved            bool           `json:"approved"`
	ApprovedByAccountID *uuid.NullUUID `json:"approved_by_account_id"`
	PayoutCents         int32          `json:"payout_cents"`
}

func (q *Queries) CreateChoreCompletion(ctx context.Context, arg CreateChoreCompletionParams) (ChoreCompletion, error) {
	row := q.db.QueryRow(ctx, createChoreCompletion,
		arg.ID,
		arg.ChoreID,
		arg.MemberID,
		arg.Date,
		arg.Approved,
		arg.ApprovedByAccountID,
		arg.PayoutCents,
	)
	var i ChoreCompletion
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.MemberID,
		&i.Date,
		&i.MarkedAt,
		&i.Approved,
		&i.ApprovedByAccountID,
		&i.PayoutCents,
		&i.Closed,
	)
	return i, err
}

const deleteChoreCompletion = `-- name: DeleteChoreCompletion :exec
DELETE FROM chore_completions
WHERE chore_id = $1 AND date = $2 AND closed = FALSE
`

type DeleteChoreCompletionParams struct {
	ChoreID uuid.UUID   `json:"chore_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) DeleteChoreCompletion(ctx context.Context, arg DeleteChoreCompletionParams) error {
	_, err := q.db.Exec(ctx, deleteChoreCompletion, arg.ChoreID, arg.Date)
	return err
}

const getChore = `-- name: GetChore :one
SELECT id, household_id, member_id, name, weight, frequency_kind, days_of_week, auto_approve, archived_at, created_at, updated_at FROM chores WHERE id = $1 AND household_id = $2 LIMIT 1
`

type GetChoreParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetChore(ctx context.Context, arg GetChoreParams) (Chore, error) {
	row := q.db.QueryRow(ctx, getChore, arg.ID, arg.HouseholdID)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.Weight,
		&i.FrequencyKind,
		&i.DaysOfWeek,
		&i.AutoApprove,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChoreCompletion = `-- name: GetChoreCompletion :one
SELECT id, chore_id, member_id, date, marked_at, approved, approved_by_account_id, payout_cents, closed FROM chore_completions WHERE chore_id = $1 AND date = $2 LIMIT 1
`

type GetChoreCompletionParams struct {
	ChoreID uuid.UUID   `json:"chore_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) GetChoreCompletion(ctx context.Context, arg GetChoreCompletionParams) (ChoreCompletion, error) {
	row := q.db.QueryRow(ctx, getChoreCompletion, arg.ChoreID, arg.Date)
	var i ChoreCompletion
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.MemberID,
		&i.Date,
		&i.MarkedAt,
		&i.Approved,
		&i.ApprovedByAccountID,
		&i.PayoutCents,
		&i.Closed,
	)
	return i, err
}

const listChoreCompletionsForRange = `-- name: ListChoreCompletionsForRange :many
SELECT cc.id, cc.chore_id, cc.member_id, cc.date, cc.marked_at, cc.approved, cc.approved_by_account_id, cc.payout_cents, cc.closed FROM chore_completions cc
JOIN chores c ON c.id = cc.chore_id
WHERE c.household_id = $1
  AND cc.date BETWEEN $2 AND $3
  AND ($4::uuid IS NULL OR cc.member_id = $4::uuid)
ORDER BY cc.date DESC, cc.marked_at DESC
`

type ListChoreCompletionsForRangeParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	Date        pgtype.Date    `json:"date"`
	Date_2      pgtype.Date    `json:"date_2"`
	MemberID    *uuid.NullUUID `json:"member_id"`
}

func (q *Queries) ListChoreCompletionsForRange(ctx context.Context, arg ListChoreCompletionsForRangeParams) ([]ChoreCompletion, error) {
	rows, err := q.db.Query(ctx, listChoreCompletionsForRange,
		arg.HouseholdID,
		arg.Date,
		arg.Date_2,
		arg.MemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChoreCompletion{}
	for rows.Next() {
		var i ChoreCompletion
		if err := rows.Scan(
			&i.ID,
			&i.ChoreID,
			&i.MemberID,
			&i.Date,
			&i.MarkedAt,
			&i.Approved,
			&i.ApprovedByAccountID,
			&i.PayoutCents,
			&i.Closed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChoreCompletionsForWeek = `-- name: ListChoreCompletionsForWeek :many
SELECT cc.id, cc.chore_id, cc.member_id, cc.date, cc.marked_at, cc.approved, cc.approved_by_account_id, cc.payout_cents, cc.closed FROM chore_completions cc
WHERE cc.member_id = $1
  AND cc.date BETWEEN $2 AND $3
`

type ListChoreCompletionsForWeekParams struct {
	MemberID uuid.UUID   `json:"member_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

func (q *Queries) ListChoreCompletionsForWeek(ctx context.Context, arg ListChoreCompletionsForWeekParams) ([]ChoreCompletion, error) {
	rows, err := q.db.Query(ctx, listChoreCompletionsForWeek, arg.MemberID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChoreCompletion{}
	for rows.Next() {
		var i ChoreCompletion
		if err := rows.Scan(
			&i.ID,
			&i.ChoreID,
			&i.MemberID,
			&i.Date,
			&i.MarkedAt,
			&i.Approved,
			&i.ApprovedByAccountID,
			&i.PayoutCents,
			&i.Closed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChores = `-- name: ListChores :many
SELECT id, household_id, member_id, name, weight, frequency_kind, days_of_week, auto_approve, archived_at, created_at, updated_at FROM chores
WHERE household_id = $1
  AND ($2::uuid IS NULL OR member_id = $2::uuid)
  AND ($3::boolean OR archived_at IS NULL)
ORDER BY name ASC
`

type ListChoresParams struct {
	HouseholdID     uuid.UUID      `json:"household_id"`
	MemberID        *uuid.NullUUID `json:"member_id"`
	IncludeArchived bool           `json:"include_archived"`
}

func (q *Queries) ListChores(ctx context.Context, arg ListChoresParams) ([]Chore, error) {
	rows, err := q.db.Query(ctx, listChores, arg.HouseholdID, arg.MemberID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chore{}
	for rows.Next() {
		var i Chore
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.Name,
			&i.Weight,
			&i.FrequencyKind,
			&i.DaysOfWeek,
			&i.AutoApprove,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChore = `-- name: UpdateChore :one
UPDATE chores
SET name           = COALESCE($3, name),
    weight         = COALESCE($4, weight),
    frequency_kind = COALESCE($5, frequency_kind),
    days_of_week   = COALESCE($6::text[], days_of_week),
    auto_approve   = COALESCE($7, auto_approve),
    updated_at     = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, member_id, name, weight, frequency_kind, days_of_week, auto_approve, archived_at, created_at, updated_at
`

type UpdateChoreParams struct {
	ID            uuid.UUID `json:"id"`
	HouseholdID   uuid.UUID `json:"household_id"`
	Name          *string   `json:"name"`
	Weight        *int32    `json:"weight"`
	FrequencyKind *string   `json:"frequency_kind"`
	DaysOfWeek    []string  `json:"days_of_week"`
	AutoApprove   *bool     `json:"auto_approve"`
}

func (q *Queries) UpdateChore(ctx context.Context, arg UpdateChoreParams) (Chore, error) {
	row := q.db.QueryRow(ctx, updateChore,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Weight,
		arg.FrequencyKind,
		arg.DaysOfWeek,
		arg.AutoApprove,
	)
	var i Chore
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.Weight,
		&i.FrequencyKind,
		&i.DaysOfWeek,
		&i.AutoApprove,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
