// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chore_time_entries.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMemberTimeSummary = `-- name: GetMemberTimeSummary :one
SELECT
    COUNT(*)::BIGINT                                AS entry_count,
    COALESCE(SUM(duration_seconds), 0)::BIGINT      AS total_seconds
FROM chore_time_entries
WHERE member_id = $1
  AND started_at >= $2
  AND started_at < $3
  AND ended_at IS NOT NULL
`

type GetMemberTimeSummaryParams struct {
	MemberID    uuid.UUID          `json:"member_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type GetMemberTimeSummaryRow struct {
	EntryCount   int64 `json:"entry_count"`
	TotalSeconds int64 `json:"total_seconds"`
}

// Aggregate completed entries for a member over [from, to) (half-open).
// Only counts closed entries (duration_seconds IS NOT NULL).
func (q *Queries) GetMemberTimeSummary(ctx context.Context, arg GetMemberTimeSummaryParams) (GetMemberTimeSummaryRow, error) {
	row := q.db.QueryRow(ctx, getMemberTimeSummary, arg.MemberID, arg.StartedAt, arg.StartedAt_2)
	var i GetMemberTimeSummaryRow
	err := row.Scan(&i.EntryCount, &i.TotalSeconds)
	return i, err
}

const getMemberTimeSummaryByChore = `-- name: GetMemberTimeSummaryByChore :many
SELECT
    chore_id,
    COUNT(*)::BIGINT                                AS entry_count,
    COALESCE(SUM(duration_seconds), 0)::BIGINT      AS total_seconds
FROM chore_time_entries
WHERE member_id = $1
  AND started_at >= $2
  AND started_at < $3
  AND ended_at IS NOT NULL
GROUP BY chore_id
ORDER BY total_seconds DESC
`

type GetMemberTimeSummaryByChoreParams struct {
	MemberID    uuid.UUID          `json:"member_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type GetMemberTimeSummaryByChoreRow struct {
	ChoreID      uuid.UUID `json:"chore_id"`
	EntryCount   int64     `json:"entry_count"`
	TotalSeconds int64     `json:"total_seconds"`
}

func (q *Queries) GetMemberTimeSummaryByChore(ctx context.Context, arg GetMemberTimeSummaryByChoreParams) ([]GetMemberTimeSummaryByChoreRow, error) {
	rows, err := q.db.Query(ctx, getMemberTimeSummaryByChore, arg.MemberID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMemberTimeSummaryByChoreRow{}
	for rows.Next() {
		var i GetMemberTimeSummaryByChoreRow
		if err := rows.Scan(&i.ChoreID, &i.EntryCount, &i.TotalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenChoreTimer = `-- name: GetOpenChoreTimer :one
SELECT id, chore_id, member_id, started_at, ended_at, duration_seconds, note, source, created_at FROM chore_time_entries
WHERE chore_id = $1 AND member_id = $2 AND ended_at IS NULL
ORDER BY started_at DESC
LIMIT 1
`

type GetOpenChoreTimerParams struct {
	ChoreID  uuid.UUID `json:"chore_id"`
	MemberID uuid.UUID `json:"member_id"`
}

func (q *Queries) GetOpenChoreTimer(ctx context.Context, arg GetOpenChoreTimerParams) (ChoreTimeEntry, error) {
	row := q.db.QueryRow(ctx, getOpenChoreTimer, arg.ChoreID, arg.MemberID)
	var i ChoreTimeEntry
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.MemberID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertManualTimeEntry = `-- name: InsertManualTimeEntry :one
INSERT INTO chore_time_entries (
    id, chore_id, member_id, started_at, ended_at, note, source
) VALUES (
    $1, $2, $3, $4, $5, $6, 'manual'
)
RETURNING id, chore_id, member_id, started_at, ended_at, duration_seconds, note, source, created_at
`

type InsertManualTimeEntryParams struct {
	ID        uuid.UUID          `json:"id"`
	ChoreID   uuid.UUID          `json:"chore_id"`
	MemberID  uuid.UUID          `json:"member_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	Note      string             `json:"note"`
}

func (q *Queries) InsertManualTimeEntry(ctx context.Context, arg InsertManualTimeEntryParams) (ChoreTimeEntry, error) {
	row := q.db.QueryRow(ctx, insertManualTimeEntry,
		arg.ID,
		arg.ChoreID,
		arg.MemberID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Note,
	)
	var i ChoreTimeEntry
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.MemberID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listChoreTimeEntries = `-- name: ListChoreTimeEntries :many
SELECT te.id, te.chore_id, te.member_id, te.started_at, te.ended_at, te.duration_seconds, te.note, te.source, te.created_at FROM chore_time_entries te
JOIN chores c ON c.id = te.chore_id
WHERE c.household_id = $1
  AND ($4::uuid IS NULL OR te.member_id = $4::uuid)
  AND ($5::uuid IS NULL OR te.chore_id = $5::uuid)
  AND te.started_at >= $2
  AND te.started_at < $3
ORDER BY te.started_at DESC
`

type ListChoreTimeEntriesParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
	MemberID    *uuid.NullUUID     `json:"member_id"`
	ChoreID     *uuid.NullUUID     `json:"chore_id"`
}

func (q *Queries) ListChoreTimeEntries(ctx context.Context, arg ListChoreTimeEntriesParams) ([]ChoreTimeEntry, error) {
	rows, err := q.db.Query(ctx, listChoreTimeEntries,
		arg.HouseholdID,
		arg.StartedAt,
		arg.StartedAt_2,
		arg.MemberID,
		arg.ChoreID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChoreTimeEntry{}
	for rows.Next() {
		var i ChoreTimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.ChoreID,
			&i.MemberID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startChoreTimer = `-- name: StartChoreTimer :one

INSERT INTO chore_time_entries (
    id, chore_id, member_id, started_at, source
) VALUES (
    $1, $2, $3, NOW(), 'timer'
)
RETURNING id, chore_id, member_id, started_at, ended_at, duration_seconds, note, source, created_at
`

type StartChoreTimerParams struct {
	ID       uuid.UUID `json:"id"`
	ChoreID  uuid.UUID `json:"chore_id"`
	MemberID uuid.UUID `json:"member_id"`
}

// sql/queries/chore_time_entries.sql
// Chore time-entry queries: timer start/stop, manual entries, member summaries.
// Open a new timer entry. The unique partial index uq_chore_time_entries_open
// guarantees at most one open entry per (chore_id, member_id); a duplicate
// insert raises a unique-violation that the service maps to 409.
func (q *Queries) StartChoreTimer(ctx context.Context, arg StartChoreTimerParams) (ChoreTimeEntry, error) {
	row := q.db.QueryRow(ctx, startChoreTimer, arg.ID, arg.ChoreID, arg.MemberID)
	var i ChoreTimeEntry
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.MemberID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const stopChoreTimer = `-- name: StopChoreTimer :one
UPDATE chore_time_entries AS te
SET ended_at = NOW()
WHERE te.id = (
    SELECT t2.id FROM chore_time_entries AS t2
    WHERE t2.chore_id = $1 AND t2.member_id = $2 AND t2.ended_at IS NULL
    ORDER BY t2.started_at DESC
    LIMIT 1
)
RETURNING te.id, te.chore_id, te.member_id, te.started_at, te.ended_at, te.duration_seconds, te.note, te.source, te.created_at
`

type StopChoreTimerParams struct {
	ChoreID  uuid.UUID `json:"chore_id"`
	MemberID uuid.UUID `json:"member_id"`
}

// Close the latest open entry for (chore_id, member_id). Server-set ended_at.
func (q *Queries) StopChoreTimer(ctx context.Context, arg StopChoreTimerParams) (ChoreTimeEntry, error) {
	row := q.db.QueryRow(ctx, stopChoreTimer, arg.ChoreID, arg.MemberID)
	var i ChoreTimeEntry
	err := row.Scan(
		&i.ID,
		&i.ChoreID,
		&i.MemberID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
