// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: equity.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEquityTask = `-- name: ArchiveEquityTask :exec
UPDATE equity_tasks
SET archived = true, updated_at = NOW()
WHERE id = $1 AND household_id = $2
`

type ArchiveEquityTaskParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ArchiveEquityTask(ctx context.Context, arg ArchiveEquityTaskParams) error {
	_, err := q.db.Exec(ctx, archiveEquityTask, arg.ID, arg.HouseholdID)
	return err
}

const countTasksByDomain = `-- name: CountTasksByDomain :many
SELECT
    et.domain_id,
    et.owner_member_id,
    COUNT(*) AS task_count
FROM equity_tasks et
WHERE et.household_id = $1 AND et.archived = false
GROUP BY et.domain_id, et.owner_member_id
`

type CountTasksByDomainRow struct {
	DomainID      uuid.UUID      `json:"domain_id"`
	OwnerMemberID *uuid.NullUUID `json:"owner_member_id"`
	TaskCount     int64          `json:"task_count"`
}

// Returns (domain_id, owner_member_id, task_count) for all active tasks.
func (q *Queries) CountTasksByDomain(ctx context.Context, householdID uuid.UUID) ([]CountTasksByDomainRow, error) {
	rows, err := q.db.Query(ctx, countTasksByDomain, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTasksByDomainRow{}
	for rows.Next() {
		var i CountTasksByDomainRow
		if err := rows.Scan(&i.DomainID, &i.OwnerMemberID, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEquityTask = `-- name: CreateEquityTask :one
INSERT INTO equity_tasks (household_id, domain_id, name, task_type, recurrence, est_minutes, owner_member_id, share_pct)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, household_id, domain_id, name, task_type, recurrence, est_minutes, owner_member_id, share_pct, archived, created_at, updated_at
`

type CreateEquityTaskParams struct {
	HouseholdID   uuid.UUID      `json:"household_id"`
	DomainID      uuid.UUID      `json:"domain_id"`
	Name          string         `json:"name"`
	TaskType      string         `json:"task_type"`
	Recurrence    string         `json:"recurrence"`
	EstMinutes    int32          `json:"est_minutes"`
	OwnerMemberID *uuid.NullUUID `json:"owner_member_id"`
	SharePct      int32          `json:"share_pct"`
}

func (q *Queries) CreateEquityTask(ctx context.Context, arg CreateEquityTaskParams) (EquityTask, error) {
	row := q.db.QueryRow(ctx, createEquityTask,
		arg.HouseholdID,
		arg.DomainID,
		arg.Name,
		arg.TaskType,
		arg.Recurrence,
		arg.EstMinutes,
		arg.OwnerMemberID,
		arg.SharePct,
	)
	var i EquityTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DomainID,
		&i.Name,
		&i.TaskType,
		&i.Recurrence,
		&i.EstMinutes,
		&i.OwnerMemberID,
		&i.SharePct,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskDomain = `-- name: CreateTaskDomain :one
INSERT INTO task_domains (household_id, name, icon, description, is_system, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, household_id, name, icon, description, is_system, sort_order, created_at, updated_at
`

type CreateTaskDomainParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
	Icon        string    `json:"icon"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) CreateTaskDomain(ctx context.Context, arg CreateTaskDomainParams) (TaskDomain, error) {
	row := q.db.QueryRow(ctx, createTaskDomain,
		arg.HouseholdID,
		arg.Name,
		arg.Icon,
		arg.Description,
		arg.IsSystem,
		arg.SortOrder,
	)
	var i TaskDomain
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.Description,
		&i.IsSystem,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskLog = `-- name: CreateTaskLog :one

INSERT INTO task_logs (task_id, household_id, member_id, started_at, duration_minutes, is_cognitive, notes, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, household_id, member_id, started_at, duration_minutes, is_cognitive, notes, source, created_at
`

type CreateTaskLogParams struct {
	TaskID          uuid.UUID          `json:"task_id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	MemberID        uuid.UUID          `json:"member_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	IsCognitive     bool               `json:"is_cognitive"`
	Notes           string             `json:"notes"`
	Source          string             `json:"source"`
}

// ── Task Logs ────────────────────────────────────────────────────────────────
func (q *Queries) CreateTaskLog(ctx context.Context, arg CreateTaskLogParams) (TaskLog, error) {
	row := q.db.QueryRow(ctx, createTaskLog,
		arg.TaskID,
		arg.HouseholdID,
		arg.MemberID,
		arg.StartedAt,
		arg.DurationMinutes,
		arg.IsCognitive,
		arg.Notes,
		arg.Source,
	)
	var i TaskLog
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.HouseholdID,
		&i.MemberID,
		&i.StartedAt,
		&i.DurationMinutes,
		&i.IsCognitive,
		&i.Notes,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskDomain = `-- name: DeleteTaskDomain :exec
DELETE FROM task_domains
WHERE id = $1 AND household_id = $2 AND is_system = false
`

type DeleteTaskDomainParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteTaskDomain(ctx context.Context, arg DeleteTaskDomainParams) error {
	_, err := q.db.Exec(ctx, deleteTaskDomain, arg.ID, arg.HouseholdID)
	return err
}

const getEquityTask = `-- name: GetEquityTask :one
SELECT id, household_id, domain_id, name, task_type, recurrence, est_minutes, owner_member_id, share_pct, archived, created_at, updated_at FROM equity_tasks
WHERE id = $1 AND household_id = $2
`

type GetEquityTaskParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetEquityTask(ctx context.Context, arg GetEquityTaskParams) (EquityTask, error) {
	row := q.db.QueryRow(ctx, getEquityTask, arg.ID, arg.HouseholdID)
	var i EquityTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DomainID,
		&i.Name,
		&i.TaskType,
		&i.Recurrence,
		&i.EstMinutes,
		&i.OwnerMemberID,
		&i.SharePct,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDomain = `-- name: GetTaskDomain :one
SELECT d.id, d.household_id, d.name, d.icon, d.description, d.is_system, d.sort_order, d.created_at, d.updated_at, o.owner_member_id
FROM task_domains d
LEFT JOIN domain_ownerships o ON o.domain_id = d.id
WHERE d.id = $1 AND d.household_id = $2
`

type GetTaskDomainParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetTaskDomainRow struct {
	ID            uuid.UUID          `json:"id"`
	HouseholdID   uuid.UUID          `json:"household_id"`
	Name          string             `json:"name"`
	Icon          string             `json:"icon"`
	Description   string             `json:"description"`
	IsSystem      bool               `json:"is_system"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OwnerMemberID *uuid.NullUUID     `json:"owner_member_id"`
}

func (q *Queries) GetTaskDomain(ctx context.Context, arg GetTaskDomainParams) (GetTaskDomainRow, error) {
	row := q.db.QueryRow(ctx, getTaskDomain, arg.ID, arg.HouseholdID)
	var i GetTaskDomainRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.Description,
		&i.IsSystem,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerMemberID,
	)
	return i, err
}

const listEquityTasks = `-- name: ListEquityTasks :many

SELECT id, household_id, domain_id, name, task_type, recurrence, est_minutes, owner_member_id, share_pct, archived, created_at, updated_at FROM equity_tasks
WHERE household_id = $1 AND archived = false
ORDER BY domain_id, name
`

// ── Equity Tasks ─────────────────────────────────────────────────────────────
func (q *Queries) ListEquityTasks(ctx context.Context, householdID uuid.UUID) ([]EquityTask, error) {
	rows, err := q.db.Query(ctx, listEquityTasks, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EquityTask{}
	for rows.Next() {
		var i EquityTask
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DomainID,
			&i.Name,
			&i.TaskType,
			&i.Recurrence,
			&i.EstMinutes,
			&i.OwnerMemberID,
			&i.SharePct,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquityTasksByDomain = `-- name: ListEquityTasksByDomain :many
SELECT id, household_id, domain_id, name, task_type, recurrence, est_minutes, owner_member_id, share_pct, archived, created_at, updated_at FROM equity_tasks
WHERE household_id = $1 AND domain_id = $2 AND archived = false
ORDER BY name
`

type ListEquityTasksByDomainParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	DomainID    uuid.UUID `json:"domain_id"`
}

func (q *Queries) ListEquityTasksByDomain(ctx context.Context, arg ListEquityTasksByDomainParams) ([]EquityTask, error) {
	rows, err := q.db.Query(ctx, listEquityTasksByDomain, arg.HouseholdID, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EquityTask{}
	for rows.Next() {
		var i EquityTask
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DomainID,
			&i.Name,
			&i.TaskType,
			&i.Recurrence,
			&i.EstMinutes,
			&i.OwnerMemberID,
			&i.SharePct,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDomains = `-- name: ListTaskDomains :many


SELECT d.id, d.household_id, d.name, d.icon, d.description, d.is_system, d.sort_order, d.created_at, d.updated_at, o.owner_member_id
FROM task_domains d
LEFT JOIN domain_ownerships o ON o.domain_id = d.id
WHERE d.household_id = $1
ORDER BY d.sort_order, d.name
`

type ListTaskDomainsRow struct {
	ID            uuid.UUID          `json:"id"`
	HouseholdID   uuid.UUID          `json:"household_id"`
	Name          string             `json:"name"`
	Icon          string             `json:"icon"`
	Description   string             `json:"description"`
	IsSystem      bool               `json:"is_system"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OwnerMemberID *uuid.NullUUID     `json:"owner_member_id"`
}

// sql/queries/equity.sql
// Equity engine queries. Run `sqlc generate` to produce Go code in internal/query/.
// ── Task Domains ─────────────────────────────────────────────────────────────
func (q *Queries) ListTaskDomains(ctx context.Context, householdID uuid.UUID) ([]ListTaskDomainsRow, error) {
	rows, err := q.db.Query(ctx, listTaskDomains, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskDomainsRow{}
	for rows.Next() {
		var i ListTaskDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Icon,
			&i.Description,
			&i.IsSystem,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerMemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskLogs = `-- name: ListTaskLogs :many
SELECT tl.id, tl.task_id, tl.household_id, tl.member_id, tl.started_at, tl.duration_minutes, tl.is_cognitive, tl.notes, tl.source, tl.created_at, et.name AS task_name, et.task_type, et.domain_id
FROM task_logs tl
JOIN equity_tasks et ON et.id = tl.task_id
WHERE tl.household_id = $1
  AND tl.started_at >= $2
  AND tl.started_at <= $3
ORDER BY tl.started_at DESC
`

type ListTaskLogsParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type ListTaskLogsRow struct {
	ID              uuid.UUID          `json:"id"`
	TaskID          uuid.UUID          `json:"task_id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	MemberID        uuid.UUID          `json:"member_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	IsCognitive     bool               `json:"is_cognitive"`
	Notes           string             `json:"notes"`
	Source          string             `json:"source"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TaskName        string             `json:"task_name"`
	TaskType        string             `json:"task_type"`
	DomainID        uuid.UUID          `json:"domain_id"`
}

func (q *Queries) ListTaskLogs(ctx context.Context, arg ListTaskLogsParams) ([]ListTaskLogsRow, error) {
	rows, err := q.db.Query(ctx, listTaskLogs, arg.HouseholdID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskLogsRow{}
	for rows.Next() {
		var i ListTaskLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.HouseholdID,
			&i.MemberID,
			&i.StartedAt,
			&i.DurationMinutes,
			&i.IsCognitive,
			&i.Notes,
			&i.Source,
			&i.CreatedAt,
			&i.TaskName,
			&i.TaskType,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMinutesByMember = `-- name: SumMinutesByMember :many
SELECT
    tl.member_id,
    SUM(tl.duration_minutes)                                              AS total_minutes,
    SUM(CASE WHEN tl.is_cognitive THEN tl.duration_minutes ELSE 0 END)   AS cognitive_minutes,
    SUM(CASE WHEN NOT tl.is_cognitive THEN tl.duration_minutes ELSE 0 END) AS physical_minutes
FROM task_logs tl
WHERE tl.household_id = $1
  AND tl.started_at >= $2
  AND tl.started_at <= $3
GROUP BY tl.member_id
`

type SumMinutesByMemberParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type SumMinutesByMemberRow struct {
	MemberID         uuid.UUID `json:"member_id"`
	TotalMinutes     int64     `json:"total_minutes"`
	CognitiveMinutes int64     `json:"cognitive_minutes"`
	PhysicalMinutes  int64     `json:"physical_minutes"`
}

// Returns total minutes logged per member within a time window.
func (q *Queries) SumMinutesByMember(ctx context.Context, arg SumMinutesByMemberParams) ([]SumMinutesByMemberRow, error) {
	rows, err := q.db.Query(ctx, sumMinutesByMember, arg.HouseholdID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumMinutesByMemberRow{}
	for rows.Next() {
		var i SumMinutesByMemberRow
		if err := rows.Scan(
			&i.MemberID,
			&i.TotalMinutes,
			&i.CognitiveMinutes,
			&i.PhysicalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMinutesByMemberAndDomain = `-- name: SumMinutesByMemberAndDomain :many
SELECT
    tl.member_id,
    et.domain_id,
    SUM(tl.duration_minutes) AS total_minutes
FROM task_logs tl
JOIN equity_tasks et ON et.id = tl.task_id
WHERE tl.household_id = $1
  AND tl.started_at >= $2
  AND tl.started_at <= $3
GROUP BY tl.member_id, et.domain_id
`

type SumMinutesByMemberAndDomainParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type SumMinutesByMemberAndDomainRow struct {
	MemberID     uuid.UUID `json:"member_id"`
	DomainID     uuid.UUID `json:"domain_id"`
	TotalMinutes int64     `json:"total_minutes"`
}

// Returns minutes per (member, domain) for the equity domain detail view.
func (q *Queries) SumMinutesByMemberAndDomain(ctx context.Context, arg SumMinutesByMemberAndDomainParams) ([]SumMinutesByMemberAndDomainRow, error) {
	rows, err := q.db.Query(ctx, sumMinutesByMemberAndDomain, arg.HouseholdID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumMinutesByMemberAndDomainRow{}
	for rows.Next() {
		var i SumMinutesByMemberAndDomainRow
		if err := rows.Scan(&i.MemberID, &i.DomainID, &i.TotalMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquityTask = `-- name: UpdateEquityTask :one
UPDATE equity_tasks
SET domain_id       = $3,
    name            = $4,
    task_type       = $5,
    recurrence      = $6,
    est_minutes     = $7,
    owner_member_id = $8,
    share_pct       = $9,
    archived        = $10,
    updated_at      = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, domain_id, name, task_type, recurrence, est_minutes, owner_member_id, share_pct, archived, created_at, updated_at
`

type UpdateEquityTaskParams struct {
	ID            uuid.UUID      `json:"id"`
	HouseholdID   uuid.UUID      `json:"household_id"`
	DomainID      uuid.UUID      `json:"domain_id"`
	Name          string         `json:"name"`
	TaskType      string         `json:"task_type"`
	Recurrence    string         `json:"recurrence"`
	EstMinutes    int32          `json:"est_minutes"`
	OwnerMemberID *uuid.NullUUID `json:"owner_member_id"`
	SharePct      int32          `json:"share_pct"`
	Archived      bool           `json:"archived"`
}

func (q *Queries) UpdateEquityTask(ctx context.Context, arg UpdateEquityTaskParams) (EquityTask, error) {
	row := q.db.QueryRow(ctx, updateEquityTask,
		arg.ID,
		arg.HouseholdID,
		arg.DomainID,
		arg.Name,
		arg.TaskType,
		arg.Recurrence,
		arg.EstMinutes,
		arg.OwnerMemberID,
		arg.SharePct,
		arg.Archived,
	)
	var i EquityTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DomainID,
		&i.Name,
		&i.TaskType,
		&i.Recurrence,
		&i.EstMinutes,
		&i.OwnerMemberID,
		&i.SharePct,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskDomain = `-- name: UpdateTaskDomain :one
UPDATE task_domains
SET name = $3, icon = $4, description = $5, sort_order = $6, updated_at = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, name, icon, description, is_system, sort_order, created_at, updated_at
`

type UpdateTaskDomainParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
	Icon        string    `json:"icon"`
	Description string    `json:"description"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) UpdateTaskDomain(ctx context.Context, arg UpdateTaskDomainParams) (TaskDomain, error) {
	row := q.db.QueryRow(ctx, updateTaskDomain,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Icon,
		arg.Description,
		arg.SortOrder,
	)
	var i TaskDomain
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.Description,
		&i.IsSystem,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDomainOwnership = `-- name: UpsertDomainOwnership :one
INSERT INTO domain_ownerships (household_id, domain_id, owner_member_id, assigned_by_member_id, notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (domain_id) DO UPDATE
  SET owner_member_id = EXCLUDED.owner_member_id,
      assigned_by_member_id = EXCLUDED.assigned_by_member_id,
      notes = EXCLUDED.notes,
      assigned_at = NOW()
RETURNING id, household_id, domain_id, owner_member_id, assigned_at, assigned_by_member_id, notes, created_at
`

type UpsertDomainOwnershipParams struct {
	HouseholdID        uuid.UUID      `json:"household_id"`
	DomainID           uuid.UUID      `json:"domain_id"`
	OwnerMemberID      uuid.UUID      `json:"owner_member_id"`
	AssignedByMemberID *uuid.NullUUID `json:"assigned_by_member_id"`
	Notes              string         `json:"notes"`
}

func (q *Queries) UpsertDomainOwnership(ctx context.Context, arg UpsertDomainOwnershipParams) (DomainOwnership, error) {
	row := q.db.QueryRow(ctx, upsertDomainOwnership,
		arg.HouseholdID,
		arg.DomainID,
		arg.OwnerMemberID,
		arg.AssignedByMemberID,
		arg.Notes,
	)
	var i DomainOwnership
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DomainID,
		&i.OwnerMemberID,
		&i.AssignedAt,
		&i.AssignedByMemberID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const weeklyMinutesByMember = `-- name: WeeklyMinutesByMember :many
SELECT
    tl.member_id,
    date_trunc('week', tl.started_at)::timestamptz AS week_start,
    SUM(tl.duration_minutes)                        AS total_minutes
FROM task_logs tl
WHERE tl.household_id = $1
  AND tl.started_at >= $2
GROUP BY tl.member_id, date_trunc('week', tl.started_at)
ORDER BY week_start
`

type WeeklyMinutesByMemberParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
}

type WeeklyMinutesByMemberRow struct {
	MemberID     uuid.UUID          `json:"member_id"`
	WeekStart    pgtype.Timestamptz `json:"week_start"`
	TotalMinutes int64              `json:"total_minutes"`
}

// Returns weekly aggregates for trend chart (last N weeks).
func (q *Queries) WeeklyMinutesByMember(ctx context.Context, arg WeeklyMinutesByMemberParams) ([]WeeklyMinutesByMemberRow, error) {
	rows, err := q.db.Query(ctx, weeklyMinutesByMember, arg.HouseholdID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyMinutesByMemberRow{}
	for rows.Next() {
		var i WeeklyMinutesByMemberRow
		if err := rows.Scan(&i.MemberID, &i.WeekStart, &i.TotalMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
