// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (id, household_id, name, source, url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, household_id, name, source, sync_config, sync_direction, assigned_member_id, color_override, created_at, updated_at, url, username, password_encrypted, display_name
`

type CreateCalendarParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
	Source      string    `json:"source"`
	Url         string    `json:"url"`
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Source,
		arg.Url,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Source,
		&i.SyncConfig,
		&i.SyncDirection,
		&i.AssignedMemberID,
		&i.ColorOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Username,
		&i.PasswordEncrypted,
		&i.DisplayName,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (
    id,
    household_id,
    calendar_id,
    external_id,
    title,
    description,
    start_time,
    end_time,
    all_day,
    location,
    recurrence_rule,
    assigned_members,
    reminders,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW(), NOW()
)
RETURNING id, household_id, calendar_id, external_id, title, description, start_time, end_time, all_day, location, recurrence_rule, assigned_members, reminders, created_at, updated_at
`

type CreateEventParams struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	CalendarID      *uuid.NullUUID     `json:"calendar_id"`
	ExternalID      *string            `json:"external_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	AllDay          bool               `json:"all_day"`
	Location        string             `json:"location"`
	RecurrenceRule  string             `json:"recurrence_rule"`
	AssignedMembers []uuid.UUID        `json:"assigned_members"`
	Reminders       []byte             `json:"reminders"`
}

// sql/queries/event.sql
// Event queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.HouseholdID,
		arg.CalendarID,
		arg.ExternalID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.RecurrenceRule,
		arg.AssignedMembers,
		arg.Reminders,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CalendarID,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.RecurrenceRule,
		&i.AssignedMembers,
		&i.Reminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1 AND household_id = $2
`

type DeleteEventParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.HouseholdID)
	return err
}

const getCalendar = `-- name: GetCalendar :one
SELECT id, household_id, name, source, sync_config, sync_direction, assigned_member_id, color_override, created_at, updated_at, url, username, password_encrypted, display_name FROM calendars
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetCalendarParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetCalendar(ctx context.Context, arg GetCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendar, arg.ID, arg.HouseholdID)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Source,
		&i.SyncConfig,
		&i.SyncDirection,
		&i.AssignedMemberID,
		&i.ColorOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Username,
		&i.PasswordEncrypted,
		&i.DisplayName,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, household_id, calendar_id, external_id, title, description, start_time, end_time, all_day, location, recurrence_rule, assigned_members, reminders, created_at, updated_at FROM events
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetEventParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.ID, arg.HouseholdID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CalendarID,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.RecurrenceRule,
		&i.AssignedMembers,
		&i.Reminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByExternalID = `-- name: GetEventByExternalID :one
SELECT id, household_id, calendar_id, external_id, title, description, start_time, end_time, all_day, location, recurrence_rule, assigned_members, reminders, created_at, updated_at FROM events
WHERE external_id = $1 AND household_id = $2
LIMIT 1
`

type GetEventByExternalIDParams struct {
	ExternalID  *string   `json:"external_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetEventByExternalID(ctx context.Context, arg GetEventByExternalIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByExternalID, arg.ExternalID, arg.HouseholdID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CalendarID,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.RecurrenceRule,
		&i.AssignedMembers,
		&i.Reminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalendars = `-- name: ListCalendars :many
SELECT id, household_id, name, source, sync_config, sync_direction, assigned_member_id, color_override, created_at, updated_at, url, username, password_encrypted, display_name FROM calendars
WHERE household_id = $1
ORDER BY created_at
`

func (q *Queries) ListCalendars(ctx context.Context, householdID uuid.UUID) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listCalendars, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Calendar{}
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Source,
			&i.SyncConfig,
			&i.SyncDirection,
			&i.AssignedMemberID,
			&i.ColorOverride,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.Username,
			&i.PasswordEncrypted,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsInRange = `-- name: ListEventsInRange :many
SELECT id, household_id, calendar_id, external_id, title, description, start_time, end_time, all_day, location, recurrence_rule, assigned_members, reminders, created_at, updated_at FROM events
WHERE household_id = $1
  AND ($2::timestamptz IS NULL OR end_time   >= $2)
  AND ($3::timestamptz   IS NULL OR start_time <= $3)
  AND ($4::uuid         IS NULL OR $4::uuid = ANY(assigned_members))
ORDER BY start_time ASC
`

type ListEventsInRangeParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	MemberID    *uuid.NullUUID     `json:"member_id"`
}

func (q *Queries) ListEventsInRange(ctx context.Context, arg ListEventsInRangeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsInRange,
		arg.HouseholdID,
		arg.StartTime,
		arg.EndTime,
		arg.MemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.CalendarID,
			&i.ExternalID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.RecurrenceRule,
			&i.AssignedMembers,
			&i.Reminders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    title           = COALESCE($3, title),
    description     = COALESCE($4, description),
    start_time      = COALESCE($5, start_time),
    end_time        = COALESCE($6, end_time),
    all_day         = COALESCE($7, all_day),
    location        = COALESCE($8, location),
    recurrence_rule = COALESCE($9, recurrence_rule),
    assigned_members = COALESCE($10, assigned_members),
    updated_at      = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, calendar_id, external_id, title, description, start_time, end_time, all_day, location, recurrence_rule, assigned_members, reminders, created_at, updated_at
`

type UpdateEventParams struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	AllDay          *bool              `json:"all_day"`
	Location        *string            `json:"location"`
	RecurrenceRule  *string            `json:"recurrence_rule"`
	AssignedMembers []uuid.UUID        `json:"assigned_members"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.HouseholdID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.RecurrenceRule,
		arg.AssignedMembers,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CalendarID,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.RecurrenceRule,
		&i.AssignedMembers,
		&i.Reminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventByExternalID = `-- name: UpsertEventByExternalID :one
INSERT INTO events (
    id,
    household_id,
    calendar_id,
    external_id,
    title,
    description,
    start_time,
    end_time,
    all_day,
    location,
    recurrence_rule,
    assigned_members,
    reminders,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW(), NOW()
)
ON CONFLICT (household_id, external_id) WHERE external_id IS NOT NULL
DO UPDATE SET
    title           = EXCLUDED.title,
    description     = EXCLUDED.description,
    start_time      = EXCLUDED.start_time,
    end_time        = EXCLUDED.end_time,
    all_day         = EXCLUDED.all_day,
    location        = EXCLUDED.location,
    recurrence_rule = EXCLUDED.recurrence_rule,
    updated_at      = NOW()
RETURNING id, household_id, calendar_id, external_id, title, description, start_time, end_time, all_day, location, recurrence_rule, assigned_members, reminders, created_at, updated_at
`

type UpsertEventByExternalIDParams struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	CalendarID      *uuid.NullUUID     `json:"calendar_id"`
	ExternalID      *string            `json:"external_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	AllDay          bool               `json:"all_day"`
	Location        string             `json:"location"`
	RecurrenceRule  string             `json:"recurrence_rule"`
	AssignedMembers []uuid.UUID        `json:"assigned_members"`
	Reminders       []byte             `json:"reminders"`
}

func (q *Queries) UpsertEventByExternalID(ctx context.Context, arg UpsertEventByExternalIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertEventByExternalID,
		arg.ID,
		arg.HouseholdID,
		arg.CalendarID,
		arg.ExternalID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.RecurrenceRule,
		arg.AssignedMembers,
		arg.Reminders,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CalendarID,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.RecurrenceRule,
		&i.AssignedMembers,
		&i.Reminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
