// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createHousehold = `-- name: CreateHousehold :one

INSERT INTO households (
    id,
    name,
    timezone,
    settings,
    created_by,
    invite_code,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING id, name, timezone, settings, created_by, invite_code, created_at, updated_at, payout_cents_per_weight
`

type CreateHouseholdParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Timezone   string    `json:"timezone"`
	Settings   []byte    `json:"settings"`
	CreatedBy  uuid.UUID `json:"created_by"`
	InviteCode string    `json:"invite_code"`
}

// sql/queries/household.sql
// Household queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold,
		arg.ID,
		arg.Name,
		arg.Timezone,
		arg.Settings,
		arg.CreatedBy,
		arg.InviteCode,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Settings,
		&i.CreatedBy,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutCentsPerWeight,
	)
	return i, err
}

const deleteHousehold = `-- name: DeleteHousehold :exec
DELETE FROM households
WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHousehold, id)
	return err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, timezone, settings, created_by, invite_code, created_at, updated_at, payout_cents_per_weight FROM households
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetHousehold(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Settings,
		&i.CreatedBy,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutCentsPerWeight,
	)
	return i, err
}

const getHouseholdByInviteCode = `-- name: GetHouseholdByInviteCode :one
SELECT id, name, timezone, settings, created_by, invite_code, created_at, updated_at, payout_cents_per_weight FROM households
WHERE invite_code = $1
LIMIT 1
`

func (q *Queries) GetHouseholdByInviteCode(ctx context.Context, inviteCode string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByInviteCode, inviteCode)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Settings,
		&i.CreatedBy,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutCentsPerWeight,
	)
	return i, err
}

const getHouseholdPayoutCentsPerWeight = `-- name: GetHouseholdPayoutCentsPerWeight :one
SELECT payout_cents_per_weight FROM households
WHERE id = $1
LIMIT 1
`

// Returns the household's flat per-weight chore payout rate (cents).
// Used as the fallback when a member has no allowance configured but a chore
// is auto-approved. Defaults to 500 (5 stones / weight) per migration
// 20260501000050_chore_wallet_idempotency.sql.
func (q *Queries) GetHouseholdPayoutCentsPerWeight(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getHouseholdPayoutCentsPerWeight, id)
	var payout_cents_per_weight int32
	err := row.Scan(&payout_cents_per_weight)
	return payout_cents_per_weight, err
}

const listHouseholdsByAccount = `-- name: ListHouseholdsByAccount :many
SELECT h.id, h.name, h.timezone, h.settings, h.created_by, h.invite_code, h.created_at, h.updated_at, h.payout_cents_per_weight FROM households h
INNER JOIN members m ON m.household_id = h.id
WHERE m.account_id = $1
ORDER BY h.created_at DESC
`

func (q *Queries) ListHouseholdsByAccount(ctx context.Context, accountID *uuid.NullUUID) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Timezone,
			&i.Settings,
			&i.CreatedBy,
			&i.InviteCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayoutCentsPerWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateInviteCode = `-- name: RegenerateInviteCode :one
UPDATE households
SET invite_code = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, timezone, settings, created_by, invite_code, created_at, updated_at, payout_cents_per_weight
`

type RegenerateInviteCodeParams struct {
	ID         uuid.UUID `json:"id"`
	InviteCode string    `json:"invite_code"`
}

func (q *Queries) RegenerateInviteCode(ctx context.Context, arg RegenerateInviteCodeParams) (Household, error) {
	row := q.db.QueryRow(ctx, regenerateInviteCode, arg.ID, arg.InviteCode)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Settings,
		&i.CreatedBy,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutCentsPerWeight,
	)
	return i, err
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET
    name        = COALESCE($2, name),
    timezone    = COALESCE($3, timezone),
    settings    = COALESCE($4, settings),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, timezone, settings, created_by, invite_code, created_at, updated_at, payout_cents_per_weight
`

type UpdateHouseholdParams struct {
	ID       uuid.UUID `json:"id"`
	Name     *string   `json:"name"`
	Timezone *string   `json:"timezone"`
	Settings []byte    `json:"settings"`
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHousehold,
		arg.ID,
		arg.Name,
		arg.Timezone,
		arg.Settings,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Settings,
		&i.CreatedBy,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayoutCentsPerWeight,
	)
	return i, err
}
