// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: housekeeper.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const sumChoreTimeByCategory = `-- name: SumChoreTimeByCategory :many

SELECT
    c.category::TEXT                                AS category,
    COALESCE(SUM(te.duration_seconds), 0)::BIGINT   AS total_seconds
FROM chore_time_entries te
JOIN chores c ON c.id = te.chore_id
WHERE c.household_id = $1
  AND c.category IS NOT NULL
  AND te.started_at >= $2
  AND te.started_at <  $3
  AND te.ended_at  IS NOT NULL
GROUP BY c.category
ORDER BY c.category ASC
`

type SumChoreTimeByCategoryParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type SumChoreTimeByCategoryRow struct {
	Category     string `json:"category"`
	TotalSeconds int64  `json:"total_seconds"`
}

// sql/queries/housekeeper.sql
// Housekeeper-rate estimation queries.
// Aggregate completed chore_time_entries grouped by chores.category for a
// household over [from, to). Excludes uncategorized chores (NULL category)
// and open entries (ended_at IS NULL).
func (q *Queries) SumChoreTimeByCategory(ctx context.Context, arg SumChoreTimeByCategoryParams) ([]SumChoreTimeByCategoryRow, error) {
	rows, err := q.db.Query(ctx, sumChoreTimeByCategory, arg.HouseholdID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumChoreTimeByCategoryRow{}
	for rows.Next() {
		var i SumChoreTimeByCategoryRow
		if err := rows.Scan(&i.Category, &i.TotalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
