// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: join_request.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const approveJoinRequest = `-- name: ApproveJoinRequest :one
UPDATE join_requests
SET status = 'approved', reviewed_by = $2, reviewed_at = NOW()
WHERE id = $1
RETURNING id, household_id, account_id, requested_at, reviewed_by, reviewed_at, status
`

type ApproveJoinRequestParams struct {
	ID         uuid.UUID      `json:"id"`
	ReviewedBy *uuid.NullUUID `json:"reviewed_by"`
}

func (q *Queries) ApproveJoinRequest(ctx context.Context, arg ApproveJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, approveJoinRequest, arg.ID, arg.ReviewedBy)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.RequestedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Status,
	)
	return i, err
}

const createJoinRequest = `-- name: CreateJoinRequest :one

INSERT INTO join_requests (
    id,
    household_id,
    account_id,
    status,
    requested_at
) VALUES (
    $1, $2, $3, 'pending', NOW()
)
RETURNING id, household_id, account_id, requested_at, reviewed_by, reviewed_at, status
`

type CreateJoinRequestParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	AccountID   uuid.UUID `json:"account_id"`
}

// sql/queries/join_request.sql
// Join request queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, createJoinRequest, arg.ID, arg.HouseholdID, arg.AccountID)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.RequestedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Status,
	)
	return i, err
}

const getJoinRequest = `-- name: GetJoinRequest :one
SELECT id, household_id, account_id, requested_at, reviewed_by, reviewed_at, status FROM join_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetJoinRequest(ctx context.Context, id uuid.UUID) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, getJoinRequest, id)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.RequestedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Status,
	)
	return i, err
}

const listJoinRequestsForHousehold = `-- name: ListJoinRequestsForHousehold :many
SELECT id, household_id, account_id, requested_at, reviewed_by, reviewed_at, status FROM join_requests
WHERE household_id = $1 AND status = 'pending'
ORDER BY requested_at ASC
`

func (q *Queries) ListJoinRequestsForHousehold(ctx context.Context, householdID uuid.UUID) ([]JoinRequest, error) {
	rows, err := q.db.Query(ctx, listJoinRequestsForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JoinRequest{}
	for rows.Next() {
		var i JoinRequest
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.RequestedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectJoinRequest = `-- name: RejectJoinRequest :one
UPDATE join_requests
SET status = 'rejected', reviewed_by = $2, reviewed_at = NOW()
WHERE id = $1
RETURNING id, household_id, account_id, requested_at, reviewed_by, reviewed_at, status
`

type RejectJoinRequestParams struct {
	ID         uuid.UUID      `json:"id"`
	ReviewedBy *uuid.NullUUID `json:"reviewed_by"`
}

func (q *Queries) RejectJoinRequest(ctx context.Context, arg RejectJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, rejectJoinRequest, arg.ID, arg.ReviewedBy)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.RequestedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Status,
	)
	return i, err
}
