// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeAllItems = `-- name: CompleteAllItems :exec
UPDATE list_items
SET completed = true, updated_at = NOW()
WHERE list_id = $1 AND household_id = $2
`

type CompleteAllItemsParams struct {
	ListID      uuid.UUID `json:"list_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) CompleteAllItems(ctx context.Context, arg CompleteAllItemsParams) error {
	_, err := q.db.Exec(ctx, completeAllItems, arg.ListID, arg.HouseholdID)
	return err
}

const createList = `-- name: CreateList :one

INSERT INTO lists (
    id,
    household_id,
    name,
    type,
    shared,
    assigned_member_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING id, household_id, name, type, shared, assigned_member_id, created_at, updated_at
`

type CreateListParams struct {
	ID               uuid.UUID      `json:"id"`
	HouseholdID      uuid.UUID      `json:"household_id"`
	Name             string         `json:"name"`
	Type             string         `json:"type"`
	Shared           bool           `json:"shared"`
	AssignedMemberID *uuid.NullUUID `json:"assigned_member_id"`
}

// sql/queries/list.sql
// List and ListItem queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Type,
		arg.Shared,
		arg.AssignedMemberID,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Type,
		&i.Shared,
		&i.AssignedMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createListItem = `-- name: CreateListItem :one
INSERT INTO list_items (
    id,
    list_id,
    household_id,
    text,
    completed,
    assigned_member_id,
    due_date,
    priority,
    sort_order,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
)
RETURNING id, list_id, household_id, text, completed, assigned_member_id, due_date, priority, sort_order, created_at, updated_at
`

type CreateListItemParams struct {
	ID               uuid.UUID      `json:"id"`
	ListID           uuid.UUID      `json:"list_id"`
	HouseholdID      uuid.UUID      `json:"household_id"`
	Text             string         `json:"text"`
	Completed        bool           `json:"completed"`
	AssignedMemberID *uuid.NullUUID `json:"assigned_member_id"`
	DueDate          pgtype.Date    `json:"due_date"`
	Priority         string         `json:"priority"`
	SortOrder        int32          `json:"sort_order"`
}

func (q *Queries) CreateListItem(ctx context.Context, arg CreateListItemParams) (ListItem, error) {
	row := q.db.QueryRow(ctx, createListItem,
		arg.ID,
		arg.ListID,
		arg.HouseholdID,
		arg.Text,
		arg.Completed,
		arg.AssignedMemberID,
		arg.DueDate,
		arg.Priority,
		arg.SortOrder,
	)
	var i ListItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.HouseholdID,
		&i.Text,
		&i.Completed,
		&i.AssignedMemberID,
		&i.DueDate,
		&i.Priority,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists
WHERE id = $1 AND household_id = $2
`

type DeleteListParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteList(ctx context.Context, arg DeleteListParams) error {
	_, err := q.db.Exec(ctx, deleteList, arg.ID, arg.HouseholdID)
	return err
}

const deleteListItem = `-- name: DeleteListItem :exec
DELETE FROM list_items
WHERE id = $1 AND list_id = $2 AND household_id = $3
`

type DeleteListItemParams struct {
	ID          uuid.UUID `json:"id"`
	ListID      uuid.UUID `json:"list_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteListItem(ctx context.Context, arg DeleteListItemParams) error {
	_, err := q.db.Exec(ctx, deleteListItem, arg.ID, arg.ListID, arg.HouseholdID)
	return err
}

const getList = `-- name: GetList :one
SELECT id, household_id, name, type, shared, assigned_member_id, created_at, updated_at FROM lists
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetListParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetList(ctx context.Context, arg GetListParams) (List, error) {
	row := q.db.QueryRow(ctx, getList, arg.ID, arg.HouseholdID)
	var i List
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Type,
		&i.Shared,
		&i.AssignedMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListItem = `-- name: GetListItem :one
SELECT id, list_id, household_id, text, completed, assigned_member_id, due_date, priority, sort_order, created_at, updated_at FROM list_items
WHERE id = $1 AND list_id = $2 AND household_id = $3
LIMIT 1
`

type GetListItemParams struct {
	ID          uuid.UUID `json:"id"`
	ListID      uuid.UUID `json:"list_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetListItem(ctx context.Context, arg GetListItemParams) (ListItem, error) {
	row := q.db.QueryRow(ctx, getListItem, arg.ID, arg.ListID, arg.HouseholdID)
	var i ListItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.HouseholdID,
		&i.Text,
		&i.Completed,
		&i.AssignedMemberID,
		&i.DueDate,
		&i.Priority,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, list_id, household_id, text, completed, assigned_member_id, due_date, priority, sort_order, created_at, updated_at FROM list_items
WHERE list_id = $1 AND household_id = $2
ORDER BY sort_order ASC, created_at ASC
`

type ListItemsParams struct {
	ListID      uuid.UUID `json:"list_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItem, error) {
	rows, err := q.db.Query(ctx, listItems, arg.ListID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItem{}
	for rows.Next() {
		var i ListItem
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.HouseholdID,
			&i.Text,
			&i.Completed,
			&i.AssignedMemberID,
			&i.DueDate,
			&i.Priority,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLists = `-- name: ListLists :many
SELECT id, household_id, name, type, shared, assigned_member_id, created_at, updated_at FROM lists
WHERE household_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListLists(ctx context.Context, householdID uuid.UUID) ([]List, error) {
	rows, err := q.db.Query(ctx, listLists, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Type,
			&i.Shared,
			&i.AssignedMemberID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET
    name               = COALESCE($3, name),
    shared             = COALESCE($4, shared),
    assigned_member_id = COALESCE($5, assigned_member_id),
    updated_at         = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, name, type, shared, assigned_member_id, created_at, updated_at
`

type UpdateListParams struct {
	ID               uuid.UUID      `json:"id"`
	HouseholdID      uuid.UUID      `json:"household_id"`
	Name             *string        `json:"name"`
	Shared           *bool          `json:"shared"`
	AssignedMemberID *uuid.NullUUID `json:"assigned_member_id"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Shared,
		arg.AssignedMemberID,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Type,
		&i.Shared,
		&i.AssignedMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateListItem = `-- name: UpdateListItem :one
UPDATE list_items
SET
    text               = COALESCE($4, text),
    completed          = COALESCE($5, completed),
    assigned_member_id = COALESCE($6, assigned_member_id),
    due_date           = COALESCE($7, due_date),
    priority           = COALESCE($8, priority),
    sort_order         = COALESCE($9, sort_order),
    updated_at         = NOW()
WHERE id = $1 AND list_id = $2 AND household_id = $3
RETURNING id, list_id, household_id, text, completed, assigned_member_id, due_date, priority, sort_order, created_at, updated_at
`

type UpdateListItemParams struct {
	ID               uuid.UUID      `json:"id"`
	ListID           uuid.UUID      `json:"list_id"`
	HouseholdID      uuid.UUID      `json:"household_id"`
	Text             *string        `json:"text"`
	Completed        *bool          `json:"completed"`
	AssignedMemberID *uuid.NullUUID `json:"assigned_member_id"`
	DueDate          pgtype.Date    `json:"due_date"`
	Priority         *string        `json:"priority"`
	SortOrder        *int32         `json:"sort_order"`
}

func (q *Queries) UpdateListItem(ctx context.Context, arg UpdateListItemParams) (ListItem, error) {
	row := q.db.QueryRow(ctx, updateListItem,
		arg.ID,
		arg.ListID,
		arg.HouseholdID,
		arg.Text,
		arg.Completed,
		arg.AssignedMemberID,
		arg.DueDate,
		arg.Priority,
		arg.SortOrder,
	)
	var i ListItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.HouseholdID,
		&i.Text,
		&i.Completed,
		&i.AssignedMemberID,
		&i.DueDate,
		&i.Priority,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
