// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meal_plan.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMealPlanEntry = `-- name: DeleteMealPlanEntry :exec
DELETE FROM meal_plan_entries
WHERE id = $1 AND household_id = $2
`

type DeleteMealPlanEntryParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteMealPlanEntry(ctx context.Context, arg DeleteMealPlanEntryParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlanEntry, arg.ID, arg.HouseholdID)
	return err
}

const listMealPlanEntries = `-- name: ListMealPlanEntries :many
SELECT id, household_id, recipe_id, date, slot, created_at, updated_at FROM meal_plan_entries
WHERE household_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date, slot
`

type ListMealPlanEntriesParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Date        pgtype.Date `json:"date"`
	Date_2      pgtype.Date `json:"date_2"`
}

func (q *Queries) ListMealPlanEntries(ctx context.Context, arg ListMealPlanEntriesParams) ([]MealPlanEntry, error) {
	rows, err := q.db.Query(ctx, listMealPlanEntries, arg.HouseholdID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPlanEntry{}
	for rows.Next() {
		var i MealPlanEntry
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.RecipeID,
			&i.Date,
			&i.Slot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMealPlanEntry = `-- name: UpsertMealPlanEntry :one

INSERT INTO meal_plan_entries (id, household_id, recipe_id, date, slot, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (household_id, date, slot)
DO UPDATE SET
    recipe_id  = EXCLUDED.recipe_id,
    updated_at = NOW()
RETURNING id, household_id, recipe_id, date, slot, created_at, updated_at
`

type UpsertMealPlanEntryParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	RecipeID    *uuid.NullUUID `json:"recipe_id"`
	Date        pgtype.Date    `json:"date"`
	Slot        string         `json:"slot"`
}

// sql/queries/meal_plan.sql
// Meal plan entry queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) UpsertMealPlanEntry(ctx context.Context, arg UpsertMealPlanEntryParams) (MealPlanEntry, error) {
	row := q.db.QueryRow(ctx, upsertMealPlanEntry,
		arg.HouseholdID,
		arg.RecipeID,
		arg.Date,
		arg.Slot,
	)
	var i MealPlanEntry
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.RecipeID,
		&i.Date,
		&i.Slot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
