// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one

INSERT INTO members (
    id,
    household_id,
    account_id,
    name,
    display_name,
    color,
    avatar_url,
    role,
    age_group,
    pin_hash,
    emergency_info,
    notification_preferences,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW()
)
RETURNING id, household_id, account_id, name, display_name, color, avatar_url, role, age_group, pin_hash, emergency_info, notification_preferences, created_at, updated_at
`

type CreateMemberParams struct {
	ID                      uuid.UUID      `json:"id"`
	HouseholdID             uuid.UUID      `json:"household_id"`
	AccountID               *uuid.NullUUID `json:"account_id"`
	Name                    string         `json:"name"`
	DisplayName             string         `json:"display_name"`
	Color                   string         `json:"color"`
	AvatarUrl               string         `json:"avatar_url"`
	Role                    string         `json:"role"`
	AgeGroup                string         `json:"age_group"`
	PinHash                 *string        `json:"pin_hash"`
	EmergencyInfo           []byte         `json:"emergency_info"`
	NotificationPreferences []byte         `json:"notification_preferences"`
}

// sql/queries/member.sql
// Member queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.HouseholdID,
		arg.AccountID,
		arg.Name,
		arg.DisplayName,
		arg.Color,
		arg.AvatarUrl,
		arg.Role,
		arg.AgeGroup,
		arg.PinHash,
		arg.EmergencyInfo,
		arg.NotificationPreferences,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.DisplayName,
		&i.Color,
		&i.AvatarUrl,
		&i.Role,
		&i.AgeGroup,
		&i.PinHash,
		&i.EmergencyInfo,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members
WHERE id = $1 AND household_id = $2
`

type DeleteMemberParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.ID, arg.HouseholdID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, household_id, account_id, name, display_name, color, avatar_url, role, age_group, pin_hash, emergency_info, notification_preferences, created_at, updated_at FROM members
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetMemberParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, arg.ID, arg.HouseholdID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.DisplayName,
		&i.Color,
		&i.AvatarUrl,
		&i.Role,
		&i.AgeGroup,
		&i.PinHash,
		&i.EmergencyInfo,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByAccountAndHousehold = `-- name: GetMemberByAccountAndHousehold :one
SELECT id, household_id, account_id, name, display_name, color, avatar_url, role, age_group, pin_hash, emergency_info, notification_preferences, created_at, updated_at FROM members
WHERE account_id = $1 AND household_id = $2
LIMIT 1
`

type GetMemberByAccountAndHouseholdParams struct {
	AccountID   *uuid.NullUUID `json:"account_id"`
	HouseholdID uuid.UUID      `json:"household_id"`
}

func (q *Queries) GetMemberByAccountAndHousehold(ctx context.Context, arg GetMemberByAccountAndHouseholdParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByAccountAndHousehold, arg.AccountID, arg.HouseholdID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.DisplayName,
		&i.Color,
		&i.AvatarUrl,
		&i.Role,
		&i.AgeGroup,
		&i.PinHash,
		&i.EmergencyInfo,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrimaryMemberByAccount = `-- name: GetPrimaryMemberByAccount :one
SELECT id, household_id, role FROM members
WHERE account_id = $1
ORDER BY created_at
LIMIT 1
`

type GetPrimaryMemberByAccountRow struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Role        string    `json:"role"`
}

// Returns the user's earliest-created membership; used by the auth middleware
// to populate household + role context for users that belong to one or more
// households. New users with no household yet get pgx.ErrNoRows here, which
// the middleware treats as "valid login, no household yet".
func (q *Queries) GetPrimaryMemberByAccount(ctx context.Context, accountID *uuid.NullUUID) (GetPrimaryMemberByAccountRow, error) {
	row := q.db.QueryRow(ctx, getPrimaryMemberByAccount, accountID)
	var i GetPrimaryMemberByAccountRow
	err := row.Scan(&i.ID, &i.HouseholdID, &i.Role)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, household_id, account_id, name, display_name, color, avatar_url, role, age_group, pin_hash, emergency_info, notification_preferences, created_at, updated_at FROM members
WHERE household_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMembers(ctx context.Context, householdID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.Name,
			&i.DisplayName,
			&i.Color,
			&i.AvatarUrl,
			&i.Role,
			&i.AgeGroup,
			&i.PinHash,
			&i.EmergencyInfo,
			&i.NotificationPreferences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET
    name                     = COALESCE($3, name),
    display_name             = COALESCE($4, display_name),
    color                    = COALESCE($5, color),
    avatar_url               = COALESCE($6, avatar_url),
    role                     = COALESCE($7, role),
    age_group                = COALESCE($8, age_group),
    pin_hash                 = COALESCE($9, pin_hash),
    notification_preferences = COALESCE($10, notification_preferences),
    updated_at               = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, account_id, name, display_name, color, avatar_url, role, age_group, pin_hash, emergency_info, notification_preferences, created_at, updated_at
`

type UpdateMemberParams struct {
	ID                      uuid.UUID `json:"id"`
	HouseholdID             uuid.UUID `json:"household_id"`
	Name                    *string   `json:"name"`
	DisplayName             *string   `json:"display_name"`
	Color                   *string   `json:"color"`
	AvatarUrl               *string   `json:"avatar_url"`
	Role                    *string   `json:"role"`
	AgeGroup                *string   `json:"age_group"`
	PinHash                 *string   `json:"pin_hash"`
	NotificationPreferences []byte    `json:"notification_preferences"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.DisplayName,
		arg.Color,
		arg.AvatarUrl,
		arg.Role,
		arg.AgeGroup,
		arg.PinHash,
		arg.NotificationPreferences,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.DisplayName,
		&i.Color,
		&i.AvatarUrl,
		&i.Role,
		&i.AgeGroup,
		&i.PinHash,
		&i.EmergencyInfo,
		&i.NotificationPreferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
