// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	OidcProvider *string            `json:"oidc_provider"`
	OidcSubject  *string            `json:"oidc_subject"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuditEntry struct {
	ID             uuid.UUID          `json:"id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	HouseholdID    uuid.UUID          `json:"household_id"`
	ActorMemberID  *uuid.NullUUID     `json:"actor_member_id"`
	ActorAccountID *uuid.NullUUID     `json:"actor_account_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityID       uuid.UUID          `json:"entity_id"`
	Details        []byte             `json:"details"`
	DeviceInfo     string             `json:"device_info"`
	IpAddress      *string            `json:"ip_address"`
}

type BackupRecord struct {
	ID             uuid.UUID          `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Type           string             `json:"type"`
	Destination    string             `json:"destination"`
	FilePath       string             `json:"file_path"`
	SizeBytes      int64              `json:"size_bytes"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	SchemaVersion  string             `json:"schema_version"`
	Status         string             `json:"status"`
	S3Key          *string            `json:"s3_key"`
}

type Calendar struct {
	ID                uuid.UUID          `json:"id"`
	HouseholdID       uuid.UUID          `json:"household_id"`
	Name              string             `json:"name"`
	Source            string             `json:"source"`
	SyncConfig        []byte             `json:"sync_config"`
	SyncDirection     string             `json:"sync_direction"`
	AssignedMemberID  *uuid.NullUUID     `json:"assigned_member_id"`
	ColorOverride     *string            `json:"color_override"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Url               string             `json:"url"`
	Username          string             `json:"username"`
	PasswordEncrypted string             `json:"password_encrypted"`
	DisplayName       string             `json:"display_name"`
}

type DomainOwnership struct {
	ID                 uuid.UUID          `json:"id"`
	HouseholdID        uuid.UUID          `json:"household_id"`
	DomainID           uuid.UUID          `json:"domain_id"`
	OwnerMemberID      uuid.UUID          `json:"owner_member_id"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	AssignedByMemberID *uuid.NullUUID     `json:"assigned_by_member_id"`
	Notes              string             `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type EquityTask struct {
	ID            uuid.UUID          `json:"id"`
	HouseholdID   uuid.UUID          `json:"household_id"`
	DomainID      uuid.UUID          `json:"domain_id"`
	Name          string             `json:"name"`
	TaskType      string             `json:"task_type"`
	Recurrence    string             `json:"recurrence"`
	EstMinutes    int32              `json:"est_minutes"`
	OwnerMemberID *uuid.NullUUID     `json:"owner_member_id"`
	SharePct      int32              `json:"share_pct"`
	Archived      bool               `json:"archived"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	CalendarID      *uuid.NullUUID     `json:"calendar_id"`
	ExternalID      *string            `json:"external_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	AllDay          bool               `json:"all_day"`
	Location        string             `json:"location"`
	RecurrenceRule  string             `json:"recurrence_rule"`
	AssignedMembers []uuid.UUID        `json:"assigned_members"`
	Reminders       []byte             `json:"reminders"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Household struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Timezone   string             `json:"timezone"`
	Settings   []byte             `json:"settings"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	InviteCode string             `json:"invite_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type IngredientCanonical struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Aliases         []string  `json:"aliases"`
	Category        string    `json:"category"`
	DefaultUnit     string    `json:"default_unit"`
	UnitConversions []byte    `json:"unit_conversions"`
}

type Invitation struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	Token       string             `json:"token"`
	InvitedBy   uuid.UUID          `json:"invited_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	Status      string             `json:"status"`
}

type JoinRequest struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	AccountID   uuid.UUID          `json:"account_id"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	ReviewedBy  *uuid.NullUUID     `json:"reviewed_by"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	Status      string             `json:"status"`
}

type List struct {
	ID               uuid.UUID          `json:"id"`
	HouseholdID      uuid.UUID          `json:"household_id"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	Shared           bool               `json:"shared"`
	AssignedMemberID *uuid.NullUUID     `json:"assigned_member_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ListItem struct {
	ID               uuid.UUID          `json:"id"`
	ListID           uuid.UUID          `json:"list_id"`
	HouseholdID      uuid.UUID          `json:"household_id"`
	Text             string             `json:"text"`
	Completed        bool               `json:"completed"`
	AssignedMemberID *uuid.NullUUID     `json:"assigned_member_id"`
	DueDate          pgtype.Date        `json:"due_date"`
	Priority         string             `json:"priority"`
	SortOrder        int32              `json:"sort_order"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MealPlanEntry struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	RecipeID    *uuid.NullUUID     `json:"recipe_id"`
	Date        pgtype.Date        `json:"date"`
	Slot        string             `json:"slot"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Member struct {
	ID                      uuid.UUID          `json:"id"`
	HouseholdID             uuid.UUID          `json:"household_id"`
	AccountID               *uuid.NullUUID     `json:"account_id"`
	Name                    string             `json:"name"`
	DisplayName             string             `json:"display_name"`
	Color                   string             `json:"color"`
	AvatarUrl               string             `json:"avatar_url"`
	Role                    string             `json:"role"`
	AgeGroup                string             `json:"age_group"`
	PinHash                 *string            `json:"pin_hash"`
	EmergencyInfo           []byte             `json:"emergency_info"`
	NotificationPreferences []byte             `json:"notification_preferences"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type PantryStaple struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	Name        string             `json:"name"`
	Amount      pgtype.Numeric     `json:"amount"`
	Unit        string             `json:"unit"`
	Aisle       string             `json:"aisle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Recipe struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	SourceUrl    string             `json:"source_url"`
	SourceDomain string             `json:"source_domain"`
	ImageUrl     string             `json:"image_url"`
	PrepTime     string             `json:"prep_time"`
	CookTime     string             `json:"cook_time"`
	TotalTime    string             `json:"total_time"`
	Servings     int32              `json:"servings"`
	ServingsUnit string             `json:"servings_unit"`
	Categories   []string           `json:"categories"`
	Cuisine      string             `json:"cuisine"`
	Tags         []string           `json:"tags"`
	Difficulty   string             `json:"difficulty"`
	Rating       int32              `json:"rating"`
	Notes        string             `json:"notes"`
	IsFavorite   bool               `json:"is_favorite"`
	TimesCooked  int32              `json:"times_cooked"`
	LastCookedAt pgtype.Date        `json:"last_cooked_at"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RecipeIngredient struct {
	ID               uuid.UUID      `json:"id"`
	RecipeID         uuid.UUID      `json:"recipe_id"`
	HouseholdID      uuid.UUID      `json:"household_id"`
	SortOrder        int32          `json:"sort_order"`
	GroupName        string         `json:"group_name"`
	Amount           pgtype.Numeric `json:"amount"`
	Unit             string         `json:"unit"`
	Name             string         `json:"name"`
	Preparation      string         `json:"preparation"`
	Optional         bool           `json:"optional"`
	SubstitutionNote string         `json:"substitution_note"`
}

type RecipeStep struct {
	ID           uuid.UUID `json:"id"`
	RecipeID     uuid.UUID `json:"recipe_id"`
	HouseholdID  uuid.UUID `json:"household_id"`
	SortOrder    int32     `json:"sort_order"`
	Text         string    `json:"text"`
	TimerSeconds *int32    `json:"timer_seconds"`
	ImageUrl     string    `json:"image_url"`
}

type ShoppingList struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	Name        string             `json:"name"`
	DateFrom    pgtype.Date        `json:"date_from"`
	DateTo      pgtype.Date        `json:"date_to"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ShoppingListItem struct {
	ID             uuid.UUID          `json:"id"`
	ShoppingListID uuid.UUID          `json:"shopping_list_id"`
	HouseholdID    uuid.UUID          `json:"household_id"`
	Name           string             `json:"name"`
	Amount         pgtype.Numeric     `json:"amount"`
	Unit           string             `json:"unit"`
	Aisle          string             `json:"aisle"`
	SourceRecipes  []string           `json:"source_recipes"`
	Completed      bool               `json:"completed"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID                   uuid.UUID          `json:"id"`
	HouseholdID          uuid.UUID          `json:"household_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TaskDomain struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	Name        string             `json:"name"`
	Icon        string             `json:"icon"`
	Description string             `json:"description"`
	IsSystem    bool               `json:"is_system"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TaskLog struct {
	ID              uuid.UUID          `json:"id"`
	TaskID          uuid.UUID          `json:"task_id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	MemberID        uuid.UUID          `json:"member_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	IsCognitive     bool               `json:"is_cognitive"`
	Notes           string             `json:"notes"`
	Source          string             `json:"source"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
