// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens
WHERE account_id = $1 AND provider = $2
`

type DeleteOAuthTokenParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Provider  string    `json:"provider"`
}

func (q *Queries) DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthToken, arg.AccountID, arg.Provider)
	return err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, account_id, provider, access_token_encrypted, refresh_token_encrypted, token_expiry, scopes, created_at, updated_at FROM oauth_tokens
WHERE account_id = $1 AND provider = $2
LIMIT 1
`

type GetOAuthTokenParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Provider  string    `json:"provider"`
}

func (q *Queries) GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthToken, arg.AccountID, arg.Provider)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :one

INSERT INTO oauth_tokens (
    id,
    account_id,
    provider,
    access_token_encrypted,
    refresh_token_encrypted,
    token_expiry,
    scopes,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
ON CONFLICT (account_id, provider) DO UPDATE SET
    access_token_encrypted  = EXCLUDED.access_token_encrypted,
    refresh_token_encrypted = EXCLUDED.refresh_token_encrypted,
    token_expiry            = EXCLUDED.token_expiry,
    scopes                  = EXCLUDED.scopes,
    updated_at              = NOW()
RETURNING id, account_id, provider, access_token_encrypted, refresh_token_encrypted, token_expiry, scopes, created_at, updated_at
`

type UpsertOAuthTokenParams struct {
	AccountID             uuid.UUID          `json:"account_id"`
	Provider              string             `json:"provider"`
	AccessTokenEncrypted  string             `json:"access_token_encrypted"`
	RefreshTokenEncrypted string             `json:"refresh_token_encrypted"`
	TokenExpiry           pgtype.Timestamptz `json:"token_expiry"`
	Scopes                []string           `json:"scopes"`
}

// sql/queries/oauth.sql
// OAuth token queries. Run `sqlc generate` to produce Go code.
func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, upsertOAuthToken,
		arg.AccountID,
		arg.Provider,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiry,
		arg.Scopes,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiry,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
