// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: points.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const archiveBehavior = `-- name: ArchiveBehavior :exec
UPDATE behaviors SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1 AND household_id = $2
`

type ArchiveBehaviorParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ArchiveBehavior(ctx context.Context, arg ArchiveBehaviorParams) error {
	_, err := q.db.Exec(ctx, archiveBehavior, arg.ID, arg.HouseholdID)
	return err
}

const archivePointCategory = `-- name: ArchivePointCategory :exec
UPDATE point_categories SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1 AND household_id = $2
`

type ArchivePointCategoryParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ArchivePointCategory(ctx context.Context, arg ArchivePointCategoryParams) error {
	_, err := q.db.Exec(ctx, archivePointCategory, arg.ID, arg.HouseholdID)
	return err
}

const createBehavior = `-- name: CreateBehavior :one

INSERT INTO behaviors (id, household_id, category_id, name, suggested_points, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, household_id, category_id, name, suggested_points, archived_at, created_at, updated_at
`

type CreateBehaviorParams struct {
	ID              uuid.UUID `json:"id"`
	HouseholdID     uuid.UUID `json:"household_id"`
	CategoryID      uuid.UUID `json:"category_id"`
	Name            string    `json:"name"`
	SuggestedPoints int32     `json:"suggested_points"`
}

// ── Behaviors ───────────────────────────────────────────────────────────────
func (q *Queries) CreateBehavior(ctx context.Context, arg CreateBehaviorParams) (Behavior, error) {
	row := q.db.QueryRow(ctx, createBehavior,
		arg.ID,
		arg.HouseholdID,
		arg.CategoryID,
		arg.Name,
		arg.SuggestedPoints,
	)
	var i Behavior
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CategoryID,
		&i.Name,
		&i.SuggestedPoints,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPointCategory = `-- name: CreatePointCategory :one


INSERT INTO point_categories (id, household_id, name, color, sort_order, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, household_id, name, color, sort_order, archived_at, created_at, updated_at
`

type CreatePointCategoryParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	SortOrder   int32     `json:"sort_order"`
}

// sql/queries/points.sql
// ── Categories ──────────────────────────────────────────────────────────────
func (q *Queries) CreatePointCategory(ctx context.Context, arg CreatePointCategoryParams) (PointCategory, error) {
	row := q.db.QueryRow(ctx, createPointCategory,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
	)
	var i PointCategory
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPointGrant = `-- name: CreatePointGrant :one

INSERT INTO point_grants (id, household_id, member_id, category_id, behavior_id, points, reason, granted_by_account_id, granted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id, household_id, member_id, category_id, behavior_id, points, reason, granted_by_account_id, granted_at
`

type CreatePointGrantParams struct {
	ID                 uuid.UUID      `json:"id"`
	HouseholdID        uuid.UUID      `json:"household_id"`
	MemberID           uuid.UUID      `json:"member_id"`
	CategoryID         *uuid.NullUUID `json:"category_id"`
	BehaviorID         *uuid.NullUUID `json:"behavior_id"`
	Points             int32          `json:"points"`
	Reason             string         `json:"reason"`
	GrantedByAccountID *uuid.NullUUID `json:"granted_by_account_id"`
}

// ── Point grants ────────────────────────────────────────────────────────────
func (q *Queries) CreatePointGrant(ctx context.Context, arg CreatePointGrantParams) (PointGrant, error) {
	row := q.db.QueryRow(ctx, createPointGrant,
		arg.ID,
		arg.HouseholdID,
		arg.MemberID,
		arg.CategoryID,
		arg.BehaviorID,
		arg.Points,
		arg.Reason,
		arg.GrantedByAccountID,
	)
	var i PointGrant
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.CategoryID,
		&i.BehaviorID,
		&i.Points,
		&i.Reason,
		&i.GrantedByAccountID,
		&i.GrantedAt,
	)
	return i, err
}

const getBehavior = `-- name: GetBehavior :one
SELECT id, household_id, category_id, name, suggested_points, archived_at, created_at, updated_at FROM behaviors WHERE id = $1 AND household_id = $2 LIMIT 1
`

type GetBehaviorParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetBehavior(ctx context.Context, arg GetBehaviorParams) (Behavior, error) {
	row := q.db.QueryRow(ctx, getBehavior, arg.ID, arg.HouseholdID)
	var i Behavior
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CategoryID,
		&i.Name,
		&i.SuggestedPoints,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPointCategory = `-- name: GetPointCategory :one
SELECT id, household_id, name, color, sort_order, archived_at, created_at, updated_at FROM point_categories WHERE id = $1 AND household_id = $2 LIMIT 1
`

type GetPointCategoryParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetPointCategory(ctx context.Context, arg GetPointCategoryParams) (PointCategory, error) {
	row := q.db.QueryRow(ctx, getPointCategory, arg.ID, arg.HouseholdID)
	var i PointCategory
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPointGrant = `-- name: GetPointGrant :one
SELECT id, household_id, member_id, category_id, behavior_id, points, reason, granted_by_account_id, granted_at FROM point_grants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPointGrant(ctx context.Context, id uuid.UUID) (PointGrant, error) {
	row := q.db.QueryRow(ctx, getPointGrant, id)
	var i PointGrant
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.CategoryID,
		&i.BehaviorID,
		&i.Points,
		&i.Reason,
		&i.GrantedByAccountID,
		&i.GrantedAt,
	)
	return i, err
}

const listBehaviors = `-- name: ListBehaviors :many
SELECT id, household_id, category_id, name, suggested_points, archived_at, created_at, updated_at FROM behaviors
WHERE household_id = $1
  AND ($2::uuid IS NULL OR category_id = $2::uuid)
  AND ($3::boolean OR archived_at IS NULL)
ORDER BY name ASC
`

type ListBehaviorsParams struct {
	HouseholdID     uuid.UUID      `json:"household_id"`
	CategoryID      *uuid.NullUUID `json:"category_id"`
	IncludeArchived bool           `json:"include_archived"`
}

func (q *Queries) ListBehaviors(ctx context.Context, arg ListBehaviorsParams) ([]Behavior, error) {
	rows, err := q.db.Query(ctx, listBehaviors, arg.HouseholdID, arg.CategoryID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Behavior{}
	for rows.Next() {
		var i Behavior
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.CategoryID,
			&i.Name,
			&i.SuggestedPoints,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointCategories = `-- name: ListPointCategories :many
SELECT id, household_id, name, color, sort_order, archived_at, created_at, updated_at FROM point_categories
WHERE household_id = $1
  AND ($2::boolean OR archived_at IS NULL)
ORDER BY sort_order ASC, name ASC
`

type ListPointCategoriesParams struct {
	HouseholdID     uuid.UUID `json:"household_id"`
	IncludeArchived bool      `json:"include_archived"`
}

func (q *Queries) ListPointCategories(ctx context.Context, arg ListPointCategoriesParams) ([]PointCategory, error) {
	rows, err := q.db.Query(ctx, listPointCategories, arg.HouseholdID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointCategory{}
	for rows.Next() {
		var i PointCategory
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointGrants = `-- name: ListPointGrants :many
SELECT id, household_id, member_id, category_id, behavior_id, points, reason, granted_by_account_id, granted_at FROM point_grants
WHERE household_id = $1
  AND ($4::uuid IS NULL OR member_id = $4::uuid)
ORDER BY granted_at DESC
LIMIT $2 OFFSET $3
`

type ListPointGrantsParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
	MemberID    *uuid.NullUUID `json:"member_id"`
}

func (q *Queries) ListPointGrants(ctx context.Context, arg ListPointGrantsParams) ([]PointGrant, error) {
	rows, err := q.db.Query(ctx, listPointGrants,
		arg.HouseholdID,
		arg.Limit,
		arg.Offset,
		arg.MemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointGrant{}
	for rows.Next() {
		var i PointGrant
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.CategoryID,
			&i.BehaviorID,
			&i.Points,
			&i.Reason,
			&i.GrantedByAccountID,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scoreboardByCategory = `-- name: ScoreboardByCategory :many
SELECT m.id AS member_id, pg.category_id, COALESCE(SUM(pg.points), 0)::BIGINT AS total
FROM members m
LEFT JOIN point_grants pg ON pg.member_id = m.id
WHERE m.household_id = $1
GROUP BY m.id, pg.category_id
`

type ScoreboardByCategoryRow struct {
	MemberID   uuid.UUID      `json:"member_id"`
	CategoryID *uuid.NullUUID `json:"category_id"`
	Total      int64          `json:"total"`
}

func (q *Queries) ScoreboardByCategory(ctx context.Context, householdID uuid.UUID) ([]ScoreboardByCategoryRow, error) {
	rows, err := q.db.Query(ctx, scoreboardByCategory, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScoreboardByCategoryRow{}
	for rows.Next() {
		var i ScoreboardByCategoryRow
		if err := rows.Scan(&i.MemberID, &i.CategoryID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scoreboardTotals = `-- name: ScoreboardTotals :many
SELECT m.id AS member_id, COALESCE(SUM(pg.points), 0)::BIGINT AS total
FROM members m
LEFT JOIN point_grants pg ON pg.member_id = m.id
WHERE m.household_id = $1
GROUP BY m.id
ORDER BY total DESC
`

type ScoreboardTotalsRow struct {
	MemberID uuid.UUID `json:"member_id"`
	Total    int64     `json:"total"`
}

func (q *Queries) ScoreboardTotals(ctx context.Context, householdID uuid.UUID) ([]ScoreboardTotalsRow, error) {
	rows, err := q.db.Query(ctx, scoreboardTotals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScoreboardTotalsRow{}
	for rows.Next() {
		var i ScoreboardTotalsRow
		if err := rows.Scan(&i.MemberID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPointsByMember = `-- name: SumPointsByMember :one
SELECT COALESCE(SUM(points), 0)::BIGINT AS total
FROM point_grants
WHERE member_id = $1
`

func (q *Queries) SumPointsByMember(ctx context.Context, memberID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumPointsByMember, memberID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumPointsByMemberAndCategory = `-- name: SumPointsByMemberAndCategory :many
SELECT category_id, COALESCE(SUM(points), 0)::BIGINT AS total
FROM point_grants
WHERE member_id = $1
GROUP BY category_id
`

type SumPointsByMemberAndCategoryRow struct {
	CategoryID *uuid.NullUUID `json:"category_id"`
	Total      int64          `json:"total"`
}

func (q *Queries) SumPointsByMemberAndCategory(ctx context.Context, memberID uuid.UUID) ([]SumPointsByMemberAndCategoryRow, error) {
	rows, err := q.db.Query(ctx, sumPointsByMemberAndCategory, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumPointsByMemberAndCategoryRow{}
	for rows.Next() {
		var i SumPointsByMemberAndCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBehavior = `-- name: UpdateBehavior :one
UPDATE behaviors
SET name             = COALESCE($3, name),
    category_id      = COALESCE($4::uuid, category_id),
    suggested_points = COALESCE($5, suggested_points),
    updated_at       = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, category_id, name, suggested_points, archived_at, created_at, updated_at
`

type UpdateBehaviorParams struct {
	ID              uuid.UUID      `json:"id"`
	HouseholdID     uuid.UUID      `json:"household_id"`
	Name            *string        `json:"name"`
	CategoryID      *uuid.NullUUID `json:"category_id"`
	SuggestedPoints *int32         `json:"suggested_points"`
}

func (q *Queries) UpdateBehavior(ctx context.Context, arg UpdateBehaviorParams) (Behavior, error) {
	row := q.db.QueryRow(ctx, updateBehavior,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.CategoryID,
		arg.SuggestedPoints,
	)
	var i Behavior
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CategoryID,
		&i.Name,
		&i.SuggestedPoints,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePointCategory = `-- name: UpdatePointCategory :one
UPDATE point_categories
SET name        = COALESCE($3, name),
    color       = COALESCE($4, color),
    sort_order  = COALESCE($5, sort_order),
    updated_at  = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, name, color, sort_order, archived_at, created_at, updated_at
`

type UpdatePointCategoryParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Name        *string   `json:"name"`
	Color       *string   `json:"color"`
	SortOrder   *int32    `json:"sort_order"`
}

func (q *Queries) UpdatePointCategory(ctx context.Context, arg UpdatePointCategoryParams) (PointCategory, error) {
	row := q.db.QueryRow(ctx, updatePointCategory,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
	)
	var i PointCategory
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
