// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// sql/queries/chore_pets.sql
	// chore_pets join table queries: links chores to pet members.
	// Section D of docs/specs/2026-05-01-fairplay-design.md.
	AddChorePet(ctx context.Context, arg AddChorePetParams) error
	AddRecipeToCollection(ctx context.Context, arg AddRecipeToCollectionParams) error
	AddStep(ctx context.Context, arg AddStepParams) (RoutineStep, error)
	AdjustWalletBalance(ctx context.Context, arg AdjustWalletBalanceParams) (Wallet, error)
	ApproveAdHocTask(ctx context.Context, arg ApproveAdHocTaskParams) (AdHocTask, error)
	ApproveJoinRequest(ctx context.Context, arg ApproveJoinRequestParams) (JoinRequest, error)
	ArchiveBehavior(ctx context.Context, arg ArchiveBehaviorParams) error
	ArchiveChore(ctx context.Context, arg ArchiveChoreParams) error
	ArchiveEquityTask(ctx context.Context, arg ArchiveEquityTaskParams) error
	ArchivePointCategory(ctx context.Context, arg ArchivePointCategoryParams) error
	ArchiveReward(ctx context.Context, arg ArchiveRewardParams) error
	ClearChorePets(ctx context.Context, choreID uuid.UUID) error
	ClearSavingsGoal(ctx context.Context, memberID uuid.UUID) error
	CloseChoreCompletionsForWeek(ctx context.Context, arg CloseChoreCompletionsForWeekParams) error
	CompleteAllItems(ctx context.Context, arg CompleteAllItemsParams) error
	CountCompletionsForDay(ctx context.Context, arg CountCompletionsForDayParams) (int64, error)
	CountStepsForRoutine(ctx context.Context, routineID uuid.UUID) (int64, error)
	// Returns (domain_id, owner_member_id, task_count) for all active tasks.
	CountTasksByDomain(ctx context.Context, householdID uuid.UUID) ([]CountTasksByDomainRow, error)
	// sql/queries/account.sql
	// Account queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// ── Ad-hoc tasks ─────────────────────────────────────────────────────────────
	CreateAdHocTask(ctx context.Context, arg CreateAdHocTaskParams) (AdHocTask, error)
	// ── Behaviors ───────────────────────────────────────────────────────────────
	CreateBehavior(ctx context.Context, arg CreateBehaviorParams) (Behavior, error)
	CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error)
	// sql/queries/chore.sql
	// Chore + ChoreCompletion queries.
	CreateChore(ctx context.Context, arg CreateChoreParams) (Chore, error)
	CreateChoreCompletion(ctx context.Context, arg CreateChoreCompletionParams) (ChoreCompletion, error)
	CreateEquityTask(ctx context.Context, arg CreateEquityTaskParams) (EquityTask, error)
	// sql/queries/event.sql
	// Event queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// sql/queries/household.sql
	// Household queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	// sql/queries/join_request.sql
	// Join request queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error)
	// sql/queries/list.sql
	// List and ListItem queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateListItem(ctx context.Context, arg CreateListItemParams) (ListItem, error)
	// sql/queries/member.sql
	// Member queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	// sql/queries/points.sql
	// ── Categories ──────────────────────────────────────────────────────────────
	CreatePointCategory(ctx context.Context, arg CreatePointCategoryParams) (PointCategory, error)
	// ── Point grants ────────────────────────────────────────────────────────────
	CreatePointGrant(ctx context.Context, arg CreatePointGrantParams) (PointGrant, error)
	// sql/queries/recipe.sql
	// Recipe queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	// sql/queries/recipe_collection.sql
	// Recipe collection queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateRecipeCollection(ctx context.Context, arg CreateRecipeCollectionParams) (RecipeCollection, error)
	CreateRecipeImportJob(ctx context.Context, arg CreateRecipeImportJobParams) (RecipeImportJob, error)
	// ── Redemptions ─────────────────────────────────────────────────────────────
	CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (Redemption, error)
	// sql/queries/reward.sql
	// ── Rewards catalog ─────────────────────────────────────────────────────────
	CreateReward(ctx context.Context, arg CreateRewardParams) (Reward, error)
	// ── Reward cost adjustments ─────────────────────────────────────────────────
	CreateRewardCostAdjustment(ctx context.Context, arg CreateRewardCostAdjustmentParams) (RewardCostAdjustment, error)
	// sql/queries/routine.sql
	// Routine, RoutineStep, and RoutineCompletion queries.
	CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error)
	// sql/queries/shopping.sql
	// Shopping list queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (ShoppingList, error)
	CreateTaskDomain(ctx context.Context, arg CreateTaskDomainParams) (TaskDomain, error)
	// ── Task Logs ────────────────────────────────────────────────────────────────
	CreateTaskLog(ctx context.Context, arg CreateTaskLogParams) (TaskLog, error)
	// ── Wallet transactions ─────────────────────────────────────────────────────
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error)
	DeactivateAccount(ctx context.Context, id uuid.UUID) error
	DeactivateShoppingLists(ctx context.Context, householdID uuid.UUID) error
	DeclineAdHocTask(ctx context.Context, arg DeclineAdHocTaskParams) (AdHocTask, error)
	DeleteChoreCompletion(ctx context.Context, arg DeleteChoreCompletionParams) error
	DeleteEvent(ctx context.Context, arg DeleteEventParams) error
	DeleteHousehold(ctx context.Context, id uuid.UUID) error
	DeleteList(ctx context.Context, arg DeleteListParams) error
	DeleteListItem(ctx context.Context, arg DeleteListItemParams) error
	DeleteMealPlanEntry(ctx context.Context, arg DeleteMealPlanEntryParams) error
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeletePantryStaple(ctx context.Context, arg DeletePantryStapleParams) error
	DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) error
	DeleteRecipeCollection(ctx context.Context, arg DeleteRecipeCollectionParams) error
	DeleteRewardCostAdjustment(ctx context.Context, arg DeleteRewardCostAdjustmentParams) error
	DeleteRoutine(ctx context.Context, arg DeleteRoutineParams) error
	DeleteShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) error
	DeleteStep(ctx context.Context, id uuid.UUID) error
	DeleteTaskDomain(ctx context.Context, arg DeleteTaskDomainParams) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByOIDC(ctx context.Context, arg GetAccountByOIDCParams) (Account, error)
	// ── Allowance ────────────────────────────────────────────────────────────────
	GetActiveAllowance(ctx context.Context, memberID uuid.UUID) (AllowanceSetting, error)
	// ── Savings goals ───────────────────────────────────────────────────────────
	GetActiveSavingsGoal(ctx context.Context, memberID uuid.UUID) (SavingsGoal, error)
	GetActiveShoppingList(ctx context.Context, householdID uuid.UUID) (ShoppingList, error)
	GetAdHocTask(ctx context.Context, arg GetAdHocTaskParams) (AdHocTask, error)
	GetBehavior(ctx context.Context, arg GetBehaviorParams) (Behavior, error)
	GetCalendar(ctx context.Context, arg GetCalendarParams) (Calendar, error)
	GetChore(ctx context.Context, arg GetChoreParams) (Chore, error)
	GetChoreCompletion(ctx context.Context, arg GetChoreCompletionParams) (ChoreCompletion, error)
	// Returns (date, completion_count) for the past N days for a given routine+member.
	GetDailyCompletionCounts(ctx context.Context, arg GetDailyCompletionCountsParams) ([]GetDailyCompletionCountsRow, error)
	GetEquityTask(ctx context.Context, arg GetEquityTaskParams) (EquityTask, error)
	GetEvent(ctx context.Context, arg GetEventParams) (Event, error)
	GetEventByExternalID(ctx context.Context, arg GetEventByExternalIDParams) (Event, error)
	GetHousehold(ctx context.Context, id uuid.UUID) (Household, error)
	GetHouseholdByInviteCode(ctx context.Context, inviteCode string) (Household, error)
	// Returns the household's flat per-weight chore payout rate (cents).
	// Used as the fallback when a member has no allowance configured but a chore
	// is auto-approved. Defaults to 500 (5 stones / weight) per migration
	// 20260501000050_chore_wallet_idempotency.sql.
	GetHouseholdPayoutCentsPerWeight(ctx context.Context, id uuid.UUID) (int32, error)
	GetJoinRequest(ctx context.Context, id uuid.UUID) (JoinRequest, error)
	GetList(ctx context.Context, arg GetListParams) (List, error)
	GetListItem(ctx context.Context, arg GetListItemParams) (ListItem, error)
	GetMember(ctx context.Context, arg GetMemberParams) (Member, error)
	GetMemberByAccountAndHousehold(ctx context.Context, arg GetMemberByAccountAndHouseholdParams) (Member, error)
	// Aggregate completed entries for a member over [from, to) (half-open).
	// Only counts closed entries (duration_seconds IS NOT NULL).
	GetMemberTimeSummary(ctx context.Context, arg GetMemberTimeSummaryParams) (GetMemberTimeSummaryRow, error)
	GetMemberTimeSummaryByChore(ctx context.Context, arg GetMemberTimeSummaryByChoreParams) ([]GetMemberTimeSummaryByChoreRow, error)
	// Returns rows for the supplied member IDs scoped to a single household.
	// Used to validate that assigned_members on events/chores belong to the
	// caller's household. Foreign or unknown IDs are simply absent from the
	// result; the caller compares input vs returned cardinality to detect them.
	GetMembersByIDs(ctx context.Context, arg GetMembersByIDsParams) ([]Member, error)
	GetOpenChoreTimer(ctx context.Context, arg GetOpenChoreTimerParams) (ChoreTimeEntry, error)
	// sql/queries/wallet.sql
	// ── Wallets ─────────────────────────────────────────────────────────────────
	GetOrCreateWallet(ctx context.Context, memberID uuid.UUID) (Wallet, error)
	GetPointCategory(ctx context.Context, arg GetPointCategoryParams) (PointCategory, error)
	GetPointGrant(ctx context.Context, id uuid.UUID) (PointGrant, error)
	// Returns the user's earliest-created membership; used by the auth middleware
	// to populate household + role context for users that belong to one or more
	// households. New users with no household yet get pgx.ErrNoRows here, which
	// the middleware treats as "valid login, no household yet".
	GetPrimaryMemberByAccount(ctx context.Context, accountID *uuid.NullUUID) (GetPrimaryMemberByAccountRow, error)
	GetRecipe(ctx context.Context, arg GetRecipeParams) (Recipe, error)
	GetRecipeBySourceURL(ctx context.Context, arg GetRecipeBySourceURLParams) (Recipe, error)
	GetRecipeCollection(ctx context.Context, arg GetRecipeCollectionParams) (RecipeCollection, error)
	GetRecipeImportJob(ctx context.Context, arg GetRecipeImportJobParams) (RecipeImportJob, error)
	GetRedemption(ctx context.Context, arg GetRedemptionParams) (Redemption, error)
	GetReward(ctx context.Context, arg GetRewardParams) (Reward, error)
	GetRoutine(ctx context.Context, arg GetRoutineParams) (Routine, error)
	GetShoppingList(ctx context.Context, arg GetShoppingListParams) (ShoppingList, error)
	GetStep(ctx context.Context, arg GetStepParams) (RoutineStep, error)
	GetSubscriptionByCustomer(ctx context.Context, stripeCustomerID string) (Subscription, error)
	GetSubscriptionByHousehold(ctx context.Context, householdID uuid.UUID) (Subscription, error)
	GetTaskDomain(ctx context.Context, arg GetTaskDomainParams) (GetTaskDomainRow, error)
	GetWalletByMember(ctx context.Context, memberID uuid.UUID) (Wallet, error)
	GetWeeklySummary(ctx context.Context, arg GetWeeklySummaryParams) (WeeklySummary, error)
	IncrementTimesCooked(ctx context.Context, arg IncrementTimesCookedParams) (Recipe, error)
	// sql/queries/audit.sql
	// Audit log queries. Run `sqlc generate` to produce Go code in internal/query/.
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	// sql/queries/backup.sql
	// Backup record queries. Run `sqlc generate` to produce Go code in internal/query/.
	InsertBackupRecord(ctx context.Context, arg InsertBackupRecordParams) (BackupRecord, error)
	InsertManualTimeEntry(ctx context.Context, arg InsertManualTimeEntryParams) (ChoreTimeEntry, error)
	InsertShoppingListItem(ctx context.Context, arg InsertShoppingListItemParams) (ShoppingListItem, error)
	ListAccountAudit(ctx context.Context, arg ListAccountAuditParams) ([]AuditEntry, error)
	ListActiveRewardCostAdjustments(ctx context.Context, arg ListActiveRewardCostAdjustmentsParams) ([]RewardCostAdjustment, error)
	ListAdHocTasks(ctx context.Context, arg ListAdHocTasksParams) ([]AdHocTask, error)
	ListAllRewardCostAdjustments(ctx context.Context, arg ListAllRewardCostAdjustmentsParams) ([]RewardCostAdjustment, error)
	ListAllowances(ctx context.Context, householdID uuid.UUID) ([]AllowanceSetting, error)
	ListBackupRecords(ctx context.Context, arg ListBackupRecordsParams) ([]BackupRecord, error)
	ListBehaviors(ctx context.Context, arg ListBehaviorsParams) ([]Behavior, error)
	ListCalendars(ctx context.Context, householdID uuid.UUID) ([]Calendar, error)
	ListChoreCompletionsForRange(ctx context.Context, arg ListChoreCompletionsForRangeParams) ([]ChoreCompletion, error)
	ListChoreCompletionsForWeek(ctx context.Context, arg ListChoreCompletionsForWeekParams) ([]ChoreCompletion, error)
	ListChorePets(ctx context.Context, choreID uuid.UUID) ([]uuid.UUID, error)
	ListChoreTimeEntries(ctx context.Context, arg ListChoreTimeEntriesParams) ([]ChoreTimeEntry, error)
	ListChores(ctx context.Context, arg ListChoresParams) ([]Chore, error)
	ListCompletionsForDay(ctx context.Context, arg ListCompletionsForDayParams) ([]RoutineCompletion, error)
	// ── Equity Tasks ─────────────────────────────────────────────────────────────
	ListEquityTasks(ctx context.Context, householdID uuid.UUID) ([]EquityTask, error)
	ListEquityTasksByDomain(ctx context.Context, arg ListEquityTasksByDomainParams) ([]EquityTask, error)
	ListEventsInRange(ctx context.Context, arg ListEventsInRangeParams) ([]Event, error)
	ListFavoriteRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error)
	ListHouseholdAudit(ctx context.Context, arg ListHouseholdAuditParams) ([]AuditEntry, error)
	ListHouseholdsByAccount(ctx context.Context, accountID *uuid.NullUUID) ([]Household, error)
	// Ingredient join for shopping list generation:
	// fetch all recipe_ingredients for recipes that appear in meal plan entries
	// within the given date range for the household.
	ListIngredientsForMealPlanRange(ctx context.Context, arg ListIngredientsForMealPlanRangeParams) ([]ListIngredientsForMealPlanRangeRow, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]ListItem, error)
	ListJoinRequestsForHousehold(ctx context.Context, householdID uuid.UUID) ([]JoinRequest, error)
	ListLists(ctx context.Context, householdID uuid.UUID) ([]List, error)
	ListMealPlanEntries(ctx context.Context, arg ListMealPlanEntriesParams) ([]MealPlanEntry, error)
	ListMembers(ctx context.Context, householdID uuid.UUID) ([]Member, error)
	ListMembersInHousehold(ctx context.Context, householdID uuid.UUID) ([]uuid.UUID, error)
	ListPantryStaples(ctx context.Context, householdID uuid.UUID) ([]PantryStaple, error)
	ListPetMembersForHousehold(ctx context.Context, householdID uuid.UUID) ([]uuid.UUID, error)
	ListPointCategories(ctx context.Context, arg ListPointCategoriesParams) ([]PointCategory, error)
	ListPointGrants(ctx context.Context, arg ListPointGrantsParams) ([]PointGrant, error)
	ListRecipeCollections(ctx context.Context, householdID uuid.UUID) ([]RecipeCollection, error)
	ListRecipeIngredients(ctx context.Context, arg ListRecipeIngredientsParams) ([]RecipeIngredient, error)
	ListRecipeSteps(ctx context.Context, arg ListRecipeStepsParams) ([]RecipeStep, error)
	ListRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error)
	ListRecipesByCollection(ctx context.Context, arg ListRecipesByCollectionParams) ([]Recipe, error)
	ListRedemptions(ctx context.Context, arg ListRedemptionsParams) ([]Redemption, error)
	ListRewards(ctx context.Context, arg ListRewardsParams) ([]Reward, error)
	ListRoutines(ctx context.Context, arg ListRoutinesParams) ([]Routine, error)
	ListShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) ([]ShoppingListItem, error)
	ListSteps(ctx context.Context, routineID uuid.UUID) ([]RoutineStep, error)
	// sql/queries/equity.sql
	// Equity engine queries. Run `sqlc generate` to produce Go code in internal/query/.
	// ── Task Domains ─────────────────────────────────────────────────────────────
	ListTaskDomains(ctx context.Context, householdID uuid.UUID) ([]ListTaskDomainsRow, error)
	ListTaskLogs(ctx context.Context, arg ListTaskLogsParams) ([]ListTaskLogsRow, error)
	ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error)
	MarkAdHocTaskCompleted(ctx context.Context, arg MarkAdHocTaskCompletedParams) (AdHocTask, error)
	MarkRecipeImportJobFailed(ctx context.Context, arg MarkRecipeImportJobFailedParams) error
	MarkRecipeImportJobSucceeded(ctx context.Context, arg MarkRecipeImportJobSucceededParams) error
	MarkRoutineComplete(ctx context.Context, arg MarkRoutineCompleteParams) (RoutineCompletion, error)
	MarkStepComplete(ctx context.Context, arg MarkStepCompleteParams) (RoutineCompletion, error)
	RecomputeWalletBalance(ctx context.Context, memberID uuid.UUID) (Wallet, error)
	RegenerateInviteCode(ctx context.Context, arg RegenerateInviteCodeParams) (Household, error)
	RejectJoinRequest(ctx context.Context, arg RejectJoinRequestParams) (JoinRequest, error)
	RemoveChorePet(ctx context.Context, arg RemoveChorePetParams) error
	RemoveRecipeFromCollection(ctx context.Context, arg RemoveRecipeFromCollectionParams) error
	ScoreboardByCategory(ctx context.Context, householdID uuid.UUID) ([]ScoreboardByCategoryRow, error)
	ScoreboardTotals(ctx context.Context, householdID uuid.UUID) ([]ScoreboardTotalsRow, error)
	// Canonical ingredient search
	SearchIngredients(ctx context.Context, dollar_1 *string) ([]IngredientCanonical, error)
	SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error)
	SetRedemptionStatus(ctx context.Context, arg SetRedemptionStatusParams) (Redemption, error)
	// sql/queries/chore_time_entries.sql
	// Chore time-entry queries: timer start/stop, manual entries, member summaries.
	// Open a new timer entry. The unique partial index uq_chore_time_entries_open
	// guarantees at most one open entry per (chore_id, member_id); a duplicate
	// insert raises a unique-violation that the service maps to 409.
	StartChoreTimer(ctx context.Context, arg StartChoreTimerParams) (ChoreTimeEntry, error)
	// Close the latest open entry for (chore_id, member_id). Server-set ended_at.
	StopChoreTimer(ctx context.Context, arg StopChoreTimerParams) (ChoreTimeEntry, error)
	SumChorePayoutsForChoreInWeek(ctx context.Context, arg SumChorePayoutsForChoreInWeekParams) (int64, error)
	// sql/queries/housekeeper.sql
	// Housekeeper-rate estimation queries.
	// Aggregate completed chore_time_entries grouped by chores.category for a
	// household over [from, to). Excludes uncategorized chores (NULL category)
	// and open entries (ended_at IS NULL).
	SumChoreTimeByCategory(ctx context.Context, arg SumChoreTimeByCategoryParams) ([]SumChoreTimeByCategoryRow, error)
	// Returns total minutes logged per member within a time window.
	SumMinutesByMember(ctx context.Context, arg SumMinutesByMemberParams) ([]SumMinutesByMemberRow, error)
	// Returns minutes per (member, domain) for the equity domain detail view.
	SumMinutesByMemberAndDomain(ctx context.Context, arg SumMinutesByMemberAndDomainParams) ([]SumMinutesByMemberAndDomainRow, error)
	SumPointsByMember(ctx context.Context, memberID uuid.UUID) (int64, error)
	SumPointsByMemberAndCategory(ctx context.Context, memberID uuid.UUID) ([]SumPointsByMemberAndCategoryRow, error)
	// ── Timeline (unified per-kid stream) ───────────────────────────────────────
	TimelineForMember(ctx context.Context, arg TimelineForMemberParams) ([]TimelineForMemberRow, error)
	UnmarkCompletion(ctx context.Context, id uuid.UUID) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBackupRecord(ctx context.Context, arg UpdateBackupRecordParams) (BackupRecord, error)
	UpdateBackupS3Key(ctx context.Context, arg UpdateBackupS3KeyParams) (BackupRecord, error)
	UpdateBehavior(ctx context.Context, arg UpdateBehaviorParams) (Behavior, error)
	UpdateChore(ctx context.Context, arg UpdateChoreParams) (Chore, error)
	UpdateEquityTask(ctx context.Context, arg UpdateEquityTaskParams) (EquityTask, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error)
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateListItem(ctx context.Context, arg UpdateListItemParams) (ListItem, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	// Sets the (private) hourly_rate range. Use sqlc.arg so callers can explicitly
	// clear the range by passing NULLs. Authorization is enforced in the service
	// layer — this query has no role check of its own.
	UpdateMemberHourlyRate(ctx context.Context, arg UpdateMemberHourlyRateParams) (Member, error)
	UpdateMemberNotify(ctx context.Context, arg UpdateMemberNotifyParams) (Member, error)
	UpdatePointCategory(ctx context.Context, arg UpdatePointCategoryParams) (PointCategory, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateRecipeCollection(ctx context.Context, arg UpdateRecipeCollectionParams) (RecipeCollection, error)
	UpdateReward(ctx context.Context, arg UpdateRewardParams) (Reward, error)
	UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error)
	UpdateShoppingListItem(ctx context.Context, arg UpdateShoppingListItemParams) (ShoppingListItem, error)
	UpdateStep(ctx context.Context, arg UpdateStepParams) (RoutineStep, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpdateTaskDomain(ctx context.Context, arg UpdateTaskDomainParams) (TaskDomain, error)
	UpsertAllowance(ctx context.Context, arg UpsertAllowanceParams) (AllowanceSetting, error)
	UpsertDomainOwnership(ctx context.Context, arg UpsertDomainOwnershipParams) (DomainOwnership, error)
	UpsertEventByExternalID(ctx context.Context, arg UpsertEventByExternalIDParams) (Event, error)
	// sql/queries/meal_plan.sql
	// Meal plan entry queries. Run `sqlc generate` to produce Go code in internal/query/.
	UpsertMealPlanEntry(ctx context.Context, arg UpsertMealPlanEntryParams) (MealPlanEntry, error)
	// Pantry staples
	UpsertPantryStaple(ctx context.Context, arg UpsertPantryStapleParams) (PantryStaple, error)
	UpsertSavingsGoal(ctx context.Context, arg UpsertSavingsGoalParams) (SavingsGoal, error)
	// sql/queries/subscription.sql
	// Stripe subscription queries. Run `sqlc generate` to produce Go code.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	// ── Weekly summaries ─────────────────────────────────────────────────────────
	UpsertWeeklySummary(ctx context.Context, arg UpsertWeeklySummaryParams) (WeeklySummary, error)
	// Returns weekly aggregates for trend chart (last N weeks).
	WeeklyMinutesByMember(ctx context.Context, arg WeeklyMinutesByMemberParams) ([]WeeklyMinutesByMemberRow, error)
}

var _ Querier = (*Queries)(nil)
