// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteAllItems(ctx context.Context, arg CompleteAllItemsParams) error
	// sql/queries/account.sql
	// Account queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// sql/queries/event.sql
	// Event queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// sql/queries/household.sql
	// Household queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	// sql/queries/list.sql
	// List and ListItem queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateListItem(ctx context.Context, arg CreateListItemParams) (ListItem, error)
	// sql/queries/member.sql
	// Member queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	// sql/queries/recipe.sql
	// Recipe queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	DeactivateAccount(ctx context.Context, id uuid.UUID) error
	DeleteEvent(ctx context.Context, arg DeleteEventParams) error
	DeleteHousehold(ctx context.Context, id uuid.UUID) error
	DeleteList(ctx context.Context, arg DeleteListParams) error
	DeleteListItem(ctx context.Context, arg DeleteListItemParams) error
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error
	DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetCalendar(ctx context.Context, arg GetCalendarParams) (Calendar, error)
	GetEvent(ctx context.Context, arg GetEventParams) (Event, error)
	GetEventByExternalID(ctx context.Context, arg GetEventByExternalIDParams) (Event, error)
	GetHousehold(ctx context.Context, id uuid.UUID) (Household, error)
	GetHouseholdByInviteCode(ctx context.Context, inviteCode string) (Household, error)
	GetList(ctx context.Context, arg GetListParams) (List, error)
	GetListItem(ctx context.Context, arg GetListItemParams) (ListItem, error)
	GetMember(ctx context.Context, arg GetMemberParams) (Member, error)
	GetMemberByAccountAndHousehold(ctx context.Context, arg GetMemberByAccountAndHouseholdParams) (Member, error)
	GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error)
	GetRecipe(ctx context.Context, arg GetRecipeParams) (Recipe, error)
	GetRecipeBySourceURL(ctx context.Context, arg GetRecipeBySourceURLParams) (Recipe, error)
	GetSubscriptionByCustomer(ctx context.Context, stripeCustomerID string) (Subscription, error)
	GetSubscriptionByHousehold(ctx context.Context, householdID uuid.UUID) (Subscription, error)
	IncrementTimesCooked(ctx context.Context, arg IncrementTimesCookedParams) (Recipe, error)
	// sql/queries/audit.sql
	// Audit log queries. Run `sqlc generate` to produce Go code in internal/query/.
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	// sql/queries/backup.sql
	// Backup record queries. Run `sqlc generate` to produce Go code in internal/query/.
	InsertBackupRecord(ctx context.Context, arg InsertBackupRecordParams) (BackupRecord, error)
	ListAccountAudit(ctx context.Context, arg ListAccountAuditParams) ([]AuditEntry, error)
	ListBackupRecords(ctx context.Context, arg ListBackupRecordsParams) ([]BackupRecord, error)
	ListCalendars(ctx context.Context, householdID uuid.UUID) ([]Calendar, error)
	ListEventsInRange(ctx context.Context, arg ListEventsInRangeParams) ([]Event, error)
	ListFavoriteRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error)
	ListHouseholdAudit(ctx context.Context, arg ListHouseholdAuditParams) ([]AuditEntry, error)
	ListHouseholdsByAccount(ctx context.Context, accountID *uuid.NullUUID) ([]Household, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]ListItem, error)
	ListLists(ctx context.Context, householdID uuid.UUID) ([]List, error)
	ListMembers(ctx context.Context, householdID uuid.UUID) ([]Member, error)
	ListRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error)
	RegenerateInviteCode(ctx context.Context, arg RegenerateInviteCodeParams) (Household, error)
	SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBackupRecord(ctx context.Context, arg UpdateBackupRecordParams) (BackupRecord, error)
	UpdateBackupS3Key(ctx context.Context, arg UpdateBackupS3KeyParams) (BackupRecord, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error)
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateListItem(ctx context.Context, arg UpdateListItemParams) (ListItem, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpsertEventByExternalID(ctx context.Context, arg UpsertEventByExternalIDParams) (Event, error)
	// sql/queries/oauth.sql
	// OAuth token queries. Run `sqlc generate` to produce Go code.
	UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error)
	// sql/queries/subscription.sql
	// Stripe subscription queries. Run `sqlc generate` to produce Go code.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
