// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveEquityTask(ctx context.Context, arg ArchiveEquityTaskParams) error
	CompleteAllItems(ctx context.Context, arg CompleteAllItemsParams) error
	// Returns (domain_id, owner_member_id, task_count) for all active tasks.
	CountTasksByDomain(ctx context.Context, householdID uuid.UUID) ([]CountTasksByDomainRow, error)
	// sql/queries/account.sql
	// Account queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error)
	CreateEquityTask(ctx context.Context, arg CreateEquityTaskParams) (EquityTask, error)
	// sql/queries/event.sql
	// Event queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// sql/queries/household.sql
	// Household queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	// sql/queries/list.sql
	// List and ListItem queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateListItem(ctx context.Context, arg CreateListItemParams) (ListItem, error)
	// sql/queries/member.sql
	// Member queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	// sql/queries/recipe.sql
	// Recipe queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	// sql/queries/shopping.sql
	// Shopping list queries. Run `sqlc generate` to produce Go code in internal/query/.
	CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (ShoppingList, error)
	CreateTaskDomain(ctx context.Context, arg CreateTaskDomainParams) (TaskDomain, error)
	// ── Task Logs ────────────────────────────────────────────────────────────────
	CreateTaskLog(ctx context.Context, arg CreateTaskLogParams) (TaskLog, error)
	DeactivateAccount(ctx context.Context, id uuid.UUID) error
	DeactivateShoppingLists(ctx context.Context, householdID uuid.UUID) error
	DeleteEvent(ctx context.Context, arg DeleteEventParams) error
	DeleteHousehold(ctx context.Context, id uuid.UUID) error
	DeleteList(ctx context.Context, arg DeleteListParams) error
	DeleteListItem(ctx context.Context, arg DeleteListItemParams) error
	DeleteMealPlanEntry(ctx context.Context, arg DeleteMealPlanEntryParams) error
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeletePantryStaple(ctx context.Context, arg DeletePantryStapleParams) error
	DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) error
	DeleteShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) error
	DeleteTaskDomain(ctx context.Context, arg DeleteTaskDomainParams) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByOIDC(ctx context.Context, arg GetAccountByOIDCParams) (Account, error)
	GetActiveShoppingList(ctx context.Context, householdID uuid.UUID) (ShoppingList, error)
	GetCalendar(ctx context.Context, arg GetCalendarParams) (Calendar, error)
	GetEquityTask(ctx context.Context, arg GetEquityTaskParams) (EquityTask, error)
	GetEvent(ctx context.Context, arg GetEventParams) (Event, error)
	GetEventByExternalID(ctx context.Context, arg GetEventByExternalIDParams) (Event, error)
	GetHousehold(ctx context.Context, id uuid.UUID) (Household, error)
	GetHouseholdByInviteCode(ctx context.Context, inviteCode string) (Household, error)
	GetList(ctx context.Context, arg GetListParams) (List, error)
	GetListItem(ctx context.Context, arg GetListItemParams) (ListItem, error)
	GetMember(ctx context.Context, arg GetMemberParams) (Member, error)
	GetMemberByAccountAndHousehold(ctx context.Context, arg GetMemberByAccountAndHouseholdParams) (Member, error)
	// Returns the user's earliest-created membership; used by the auth middleware
	// to populate household + role context for users that belong to one or more
	// households. New users with no household yet get pgx.ErrNoRows here, which
	// the middleware treats as "valid login, no household yet".
	GetPrimaryMemberByAccount(ctx context.Context, accountID *uuid.NullUUID) (GetPrimaryMemberByAccountRow, error)
	GetRecipe(ctx context.Context, arg GetRecipeParams) (Recipe, error)
	GetRecipeBySourceURL(ctx context.Context, arg GetRecipeBySourceURLParams) (Recipe, error)
	GetShoppingList(ctx context.Context, arg GetShoppingListParams) (ShoppingList, error)
	GetSubscriptionByCustomer(ctx context.Context, stripeCustomerID string) (Subscription, error)
	GetSubscriptionByHousehold(ctx context.Context, householdID uuid.UUID) (Subscription, error)
	GetTaskDomain(ctx context.Context, arg GetTaskDomainParams) (GetTaskDomainRow, error)
	IncrementTimesCooked(ctx context.Context, arg IncrementTimesCookedParams) (Recipe, error)
	// sql/queries/audit.sql
	// Audit log queries. Run `sqlc generate` to produce Go code in internal/query/.
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	// sql/queries/backup.sql
	// Backup record queries. Run `sqlc generate` to produce Go code in internal/query/.
	InsertBackupRecord(ctx context.Context, arg InsertBackupRecordParams) (BackupRecord, error)
	InsertShoppingListItem(ctx context.Context, arg InsertShoppingListItemParams) (ShoppingListItem, error)
	ListAccountAudit(ctx context.Context, arg ListAccountAuditParams) ([]AuditEntry, error)
	ListBackupRecords(ctx context.Context, arg ListBackupRecordsParams) ([]BackupRecord, error)
	ListCalendars(ctx context.Context, householdID uuid.UUID) ([]Calendar, error)
	// ── Equity Tasks ─────────────────────────────────────────────────────────────
	ListEquityTasks(ctx context.Context, householdID uuid.UUID) ([]EquityTask, error)
	ListEquityTasksByDomain(ctx context.Context, arg ListEquityTasksByDomainParams) ([]EquityTask, error)
	ListEventsInRange(ctx context.Context, arg ListEventsInRangeParams) ([]Event, error)
	ListFavoriteRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error)
	ListHouseholdAudit(ctx context.Context, arg ListHouseholdAuditParams) ([]AuditEntry, error)
	ListHouseholdsByAccount(ctx context.Context, accountID *uuid.NullUUID) ([]Household, error)
	// Ingredient join for shopping list generation:
	// fetch all recipe_ingredients for recipes that appear in meal plan entries
	// within the given date range for the household.
	ListIngredientsForMealPlanRange(ctx context.Context, arg ListIngredientsForMealPlanRangeParams) ([]ListIngredientsForMealPlanRangeRow, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]ListItem, error)
	ListLists(ctx context.Context, householdID uuid.UUID) ([]List, error)
	ListMealPlanEntries(ctx context.Context, arg ListMealPlanEntriesParams) ([]MealPlanEntry, error)
	ListMembers(ctx context.Context, householdID uuid.UUID) ([]Member, error)
	ListPantryStaples(ctx context.Context, householdID uuid.UUID) ([]PantryStaple, error)
	ListRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error)
	ListShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) ([]ShoppingListItem, error)
	// sql/queries/equity.sql
	// Equity engine queries. Run `sqlc generate` to produce Go code in internal/query/.
	// ── Task Domains ─────────────────────────────────────────────────────────────
	ListTaskDomains(ctx context.Context, householdID uuid.UUID) ([]ListTaskDomainsRow, error)
	ListTaskLogs(ctx context.Context, arg ListTaskLogsParams) ([]ListTaskLogsRow, error)
	RegenerateInviteCode(ctx context.Context, arg RegenerateInviteCodeParams) (Household, error)
	// Canonical ingredient search
	SearchIngredients(ctx context.Context, dollar_1 *string) ([]IngredientCanonical, error)
	SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error)
	// Returns total minutes logged per member within a time window.
	SumMinutesByMember(ctx context.Context, arg SumMinutesByMemberParams) ([]SumMinutesByMemberRow, error)
	// Returns minutes per (member, domain) for the equity domain detail view.
	SumMinutesByMemberAndDomain(ctx context.Context, arg SumMinutesByMemberAndDomainParams) ([]SumMinutesByMemberAndDomainRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBackupRecord(ctx context.Context, arg UpdateBackupRecordParams) (BackupRecord, error)
	UpdateBackupS3Key(ctx context.Context, arg UpdateBackupS3KeyParams) (BackupRecord, error)
	UpdateEquityTask(ctx context.Context, arg UpdateEquityTaskParams) (EquityTask, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error)
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateListItem(ctx context.Context, arg UpdateListItemParams) (ListItem, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateShoppingListItem(ctx context.Context, arg UpdateShoppingListItemParams) (ShoppingListItem, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpdateTaskDomain(ctx context.Context, arg UpdateTaskDomainParams) (TaskDomain, error)
	UpsertDomainOwnership(ctx context.Context, arg UpsertDomainOwnershipParams) (DomainOwnership, error)
	UpsertEventByExternalID(ctx context.Context, arg UpsertEventByExternalIDParams) (Event, error)
	// sql/queries/meal_plan.sql
	// Meal plan entry queries. Run `sqlc generate` to produce Go code in internal/query/.
	UpsertMealPlanEntry(ctx context.Context, arg UpsertMealPlanEntryParams) (MealPlanEntry, error)
	// Pantry staples
	UpsertPantryStaple(ctx context.Context, arg UpsertPantryStapleParams) (PantryStaple, error)
	// sql/queries/subscription.sql
	// Stripe subscription queries. Run `sqlc generate` to produce Go code.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	// Returns weekly aggregates for trend chart (last N weeks).
	WeeklyMinutesByMember(ctx context.Context, arg WeeklyMinutesByMemberParams) ([]WeeklyMinutesByMemberRow, error)
}

var _ Querier = (*Queries)(nil)
