// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_collection.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const addRecipeToCollection = `-- name: AddRecipeToCollection :exec
INSERT INTO recipe_collection_items (collection_id, recipe_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (collection_id, recipe_id) DO NOTHING
`

type AddRecipeToCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	RecipeID     uuid.UUID `json:"recipe_id"`
	SortOrder    int32     `json:"sort_order"`
}

func (q *Queries) AddRecipeToCollection(ctx context.Context, arg AddRecipeToCollectionParams) error {
	_, err := q.db.Exec(ctx, addRecipeToCollection, arg.CollectionID, arg.RecipeID, arg.SortOrder)
	return err
}

const createRecipeCollection = `-- name: CreateRecipeCollection :one

INSERT INTO recipe_collections (id, household_id, name, slug, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, household_id, name, slug, sort_order, created_at, updated_at
`

type CreateRecipeCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	SortOrder   int32     `json:"sort_order"`
}

// sql/queries/recipe_collection.sql
// Recipe collection queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateRecipeCollection(ctx context.Context, arg CreateRecipeCollectionParams) (RecipeCollection, error) {
	row := q.db.QueryRow(ctx, createRecipeCollection,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Slug,
		arg.SortOrder,
	)
	var i RecipeCollection
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipeCollection = `-- name: DeleteRecipeCollection :exec
DELETE FROM recipe_collections
WHERE id = $1 AND household_id = $2
`

type DeleteRecipeCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteRecipeCollection(ctx context.Context, arg DeleteRecipeCollectionParams) error {
	_, err := q.db.Exec(ctx, deleteRecipeCollection, arg.ID, arg.HouseholdID)
	return err
}

const getRecipeCollection = `-- name: GetRecipeCollection :one
SELECT id, household_id, name, slug, sort_order, created_at, updated_at FROM recipe_collections
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetRecipeCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetRecipeCollection(ctx context.Context, arg GetRecipeCollectionParams) (RecipeCollection, error) {
	row := q.db.QueryRow(ctx, getRecipeCollection, arg.ID, arg.HouseholdID)
	var i RecipeCollection
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecipeCollections = `-- name: ListRecipeCollections :many
SELECT id, household_id, name, slug, sort_order, created_at, updated_at FROM recipe_collections
WHERE household_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListRecipeCollections(ctx context.Context, householdID uuid.UUID) ([]RecipeCollection, error) {
	rows, err := q.db.Query(ctx, listRecipeCollections, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeCollection{}
	for rows.Next() {
		var i RecipeCollection
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByCollection = `-- name: ListRecipesByCollection :many
SELECT r.id, r.household_id, r.title, r.description, r.source_url, r.source_domain, r.image_url, r.prep_time, r.cook_time, r.total_time, r.servings, r.servings_unit, r.categories, r.cuisine, r.tags, r.difficulty, r.rating, r.notes, r.is_favorite, r.times_cooked, r.last_cooked_at, r.created_by, r.created_at, r.updated_at
FROM recipes r
INNER JOIN recipe_collection_items rci ON rci.recipe_id = r.id
WHERE rci.collection_id = $1 AND r.household_id = $2
ORDER BY rci.sort_order ASC, rci.added_at ASC
`

type ListRecipesByCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	HouseholdID  uuid.UUID `json:"household_id"`
}

func (q *Queries) ListRecipesByCollection(ctx context.Context, arg ListRecipesByCollectionParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipesByCollection, arg.CollectionID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.SourceDomain,
			&i.ImageUrl,
			&i.PrepTime,
			&i.CookTime,
			&i.TotalTime,
			&i.Servings,
			&i.ServingsUnit,
			&i.Categories,
			&i.Cuisine,
			&i.Tags,
			&i.Difficulty,
			&i.Rating,
			&i.Notes,
			&i.IsFavorite,
			&i.TimesCooked,
			&i.LastCookedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecipeFromCollection = `-- name: RemoveRecipeFromCollection :exec
DELETE FROM recipe_collection_items
WHERE collection_id = $1 AND recipe_id = $2
`

type RemoveRecipeFromCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	RecipeID     uuid.UUID `json:"recipe_id"`
}

func (q *Queries) RemoveRecipeFromCollection(ctx context.Context, arg RemoveRecipeFromCollectionParams) error {
	_, err := q.db.Exec(ctx, removeRecipeFromCollection, arg.CollectionID, arg.RecipeID)
	return err
}

const updateRecipeCollection = `-- name: UpdateRecipeCollection :one
UPDATE recipe_collections
SET
    name       = COALESCE($3, name),
    slug       = COALESCE($4, slug),
    sort_order = COALESCE($5, sort_order),
    updated_at = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, name, slug, sort_order, created_at, updated_at
`

type UpdateRecipeCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Name        *string   `json:"name"`
	Slug        *string   `json:"slug"`
	SortOrder   *int32    `json:"sort_order"`
}

func (q *Queries) UpdateRecipeCollection(ctx context.Context, arg UpdateRecipeCollectionParams) (RecipeCollection, error) {
	row := q.db.QueryRow(ctx, updateRecipeCollection,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Slug,
		arg.SortOrder,
	)
	var i RecipeCollection
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
