// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_import_job.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createRecipeImportJob = `-- name: CreateRecipeImportJob :one
INSERT INTO recipe_import_jobs (
    id,
    household_id,
    member_id,
    url,
    status,
    error_message,
    recipe_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, 'running', '', NULL, NOW(), NOW()
)
RETURNING id, household_id, member_id, url, status, error_message, recipe_id, created_at, updated_at
`

type CreateRecipeImportJobParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	MemberID    uuid.UUID `json:"member_id"`
	Url         string    `json:"url"`
}

func (q *Queries) CreateRecipeImportJob(ctx context.Context, arg CreateRecipeImportJobParams) (RecipeImportJob, error) {
	row := q.db.QueryRow(ctx, createRecipeImportJob,
		arg.ID,
		arg.HouseholdID,
		arg.MemberID,
		arg.Url,
	)
	var i RecipeImportJob
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Url,
		&i.Status,
		&i.ErrorMessage,
		&i.RecipeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeImportJob = `-- name: GetRecipeImportJob :one
SELECT id, household_id, member_id, url, status, error_message, recipe_id, created_at, updated_at
FROM recipe_import_jobs
WHERE id = $1 AND household_id = $2
`

type GetRecipeImportJobParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetRecipeImportJob(ctx context.Context, arg GetRecipeImportJobParams) (RecipeImportJob, error) {
	row := q.db.QueryRow(ctx, getRecipeImportJob, arg.ID, arg.HouseholdID)
	var i RecipeImportJob
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Url,
		&i.Status,
		&i.ErrorMessage,
		&i.RecipeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRecipeImportJobFailed = `-- name: MarkRecipeImportJobFailed :exec
UPDATE recipe_import_jobs
SET status = 'failed',
    error_message = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkRecipeImportJobFailedParams struct {
	ID           uuid.UUID `json:"id"`
	ErrorMessage string    `json:"error_message"`
}

func (q *Queries) MarkRecipeImportJobFailed(ctx context.Context, arg MarkRecipeImportJobFailedParams) error {
	_, err := q.db.Exec(ctx, markRecipeImportJobFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markRecipeImportJobSucceeded = `-- name: MarkRecipeImportJobSucceeded :exec
UPDATE recipe_import_jobs
SET status = 'succeeded',
    recipe_id = $2,
    error_message = '',
    updated_at = NOW()
WHERE id = $1
`

type MarkRecipeImportJobSucceededParams struct {
	ID       uuid.UUID      `json:"id"`
	RecipeID *uuid.NullUUID `json:"recipe_id"`
}

func (q *Queries) MarkRecipeImportJobSucceeded(ctx context.Context, arg MarkRecipeImportJobSucceededParams) error {
	_, err := q.db.Exec(ctx, markRecipeImportJobSucceeded, arg.ID, arg.RecipeID)
	return err
}
