// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipe = `-- name: CreateRecipe :one

INSERT INTO recipes (
    id,
    household_id,
    title,
    description,
    source_url,
    source_domain,
    image_url,
    prep_time,
    cook_time,
    total_time,
    servings,
    servings_unit,
    categories,
    cuisine,
    tags,
    difficulty,
    rating,
    notes,
    is_favorite,
    times_cooked,
    last_cooked_at,
    created_by,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, NOW(), NOW()
)
RETURNING id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at
`

type CreateRecipeParams struct {
	ID           uuid.UUID   `json:"id"`
	HouseholdID  uuid.UUID   `json:"household_id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	SourceUrl    string      `json:"source_url"`
	SourceDomain string      `json:"source_domain"`
	ImageUrl     string      `json:"image_url"`
	PrepTime     string      `json:"prep_time"`
	CookTime     string      `json:"cook_time"`
	TotalTime    string      `json:"total_time"`
	Servings     int32       `json:"servings"`
	ServingsUnit string      `json:"servings_unit"`
	Categories   []string    `json:"categories"`
	Cuisine      string      `json:"cuisine"`
	Tags         []string    `json:"tags"`
	Difficulty   string      `json:"difficulty"`
	Rating       int32       `json:"rating"`
	Notes        string      `json:"notes"`
	IsFavorite   bool        `json:"is_favorite"`
	TimesCooked  int32       `json:"times_cooked"`
	LastCookedAt pgtype.Date `json:"last_cooked_at"`
	CreatedBy    uuid.UUID   `json:"created_by"`
}

// sql/queries/recipe.sql
// Recipe queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.ID,
		arg.HouseholdID,
		arg.Title,
		arg.Description,
		arg.SourceUrl,
		arg.SourceDomain,
		arg.ImageUrl,
		arg.PrepTime,
		arg.CookTime,
		arg.TotalTime,
		arg.Servings,
		arg.ServingsUnit,
		arg.Categories,
		arg.Cuisine,
		arg.Tags,
		arg.Difficulty,
		arg.Rating,
		arg.Notes,
		arg.IsFavorite,
		arg.TimesCooked,
		arg.LastCookedAt,
		arg.CreatedBy,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.SourceDomain,
		&i.ImageUrl,
		&i.PrepTime,
		&i.CookTime,
		&i.TotalTime,
		&i.Servings,
		&i.ServingsUnit,
		&i.Categories,
		&i.Cuisine,
		&i.Tags,
		&i.Difficulty,
		&i.Rating,
		&i.Notes,
		&i.IsFavorite,
		&i.TimesCooked,
		&i.LastCookedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE id = $1 AND household_id = $2
`

type DeleteRecipeParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) error {
	_, err := q.db.Exec(ctx, deleteRecipe, arg.ID, arg.HouseholdID)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at FROM recipes
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetRecipeParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetRecipe(ctx context.Context, arg GetRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipe, arg.ID, arg.HouseholdID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.SourceDomain,
		&i.ImageUrl,
		&i.PrepTime,
		&i.CookTime,
		&i.TotalTime,
		&i.Servings,
		&i.ServingsUnit,
		&i.Categories,
		&i.Cuisine,
		&i.Tags,
		&i.Difficulty,
		&i.Rating,
		&i.Notes,
		&i.IsFavorite,
		&i.TimesCooked,
		&i.LastCookedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeBySourceURL = `-- name: GetRecipeBySourceURL :one
SELECT id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at FROM recipes
WHERE source_url = $1 AND household_id = $2
LIMIT 1
`

type GetRecipeBySourceURLParams struct {
	SourceUrl   string    `json:"source_url"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetRecipeBySourceURL(ctx context.Context, arg GetRecipeBySourceURLParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeBySourceURL, arg.SourceUrl, arg.HouseholdID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.SourceDomain,
		&i.ImageUrl,
		&i.PrepTime,
		&i.CookTime,
		&i.TotalTime,
		&i.Servings,
		&i.ServingsUnit,
		&i.Categories,
		&i.Cuisine,
		&i.Tags,
		&i.Difficulty,
		&i.Rating,
		&i.Notes,
		&i.IsFavorite,
		&i.TimesCooked,
		&i.LastCookedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementTimesCooked = `-- name: IncrementTimesCooked :one
UPDATE recipes
SET
    times_cooked   = times_cooked + 1,
    last_cooked_at = NOW(),
    updated_at     = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at
`

type IncrementTimesCookedParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) IncrementTimesCooked(ctx context.Context, arg IncrementTimesCookedParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, incrementTimesCooked, arg.ID, arg.HouseholdID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.SourceDomain,
		&i.ImageUrl,
		&i.PrepTime,
		&i.CookTime,
		&i.TotalTime,
		&i.Servings,
		&i.ServingsUnit,
		&i.Categories,
		&i.Cuisine,
		&i.Tags,
		&i.Difficulty,
		&i.Rating,
		&i.Notes,
		&i.IsFavorite,
		&i.TimesCooked,
		&i.LastCookedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFavoriteRecipes = `-- name: ListFavoriteRecipes :many
SELECT id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at FROM recipes
WHERE household_id = $1 AND is_favorite = true
ORDER BY updated_at DESC
`

func (q *Queries) ListFavoriteRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listFavoriteRecipes, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.SourceDomain,
			&i.ImageUrl,
			&i.PrepTime,
			&i.CookTime,
			&i.TotalTime,
			&i.Servings,
			&i.ServingsUnit,
			&i.Categories,
			&i.Cuisine,
			&i.Tags,
			&i.Difficulty,
			&i.Rating,
			&i.Notes,
			&i.IsFavorite,
			&i.TimesCooked,
			&i.LastCookedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT id, recipe_id, household_id, sort_order, group_name, amount, unit, name, preparation, optional, substitution_note FROM recipe_ingredients
WHERE recipe_id = $1 AND household_id = $2
ORDER BY sort_order ASC, name ASC
`

type ListRecipeIngredientsParams struct {
	RecipeID    uuid.UUID `json:"recipe_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListRecipeIngredients(ctx context.Context, arg ListRecipeIngredientsParams) ([]RecipeIngredient, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, arg.RecipeID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeIngredient{}
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.HouseholdID,
			&i.SortOrder,
			&i.GroupName,
			&i.Amount,
			&i.Unit,
			&i.Name,
			&i.Preparation,
			&i.Optional,
			&i.SubstitutionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeSteps = `-- name: ListRecipeSteps :many
SELECT id, recipe_id, household_id, sort_order, text, timer_seconds, image_url FROM recipe_steps
WHERE recipe_id = $1 AND household_id = $2
ORDER BY sort_order ASC
`

type ListRecipeStepsParams struct {
	RecipeID    uuid.UUID `json:"recipe_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListRecipeSteps(ctx context.Context, arg ListRecipeStepsParams) ([]RecipeStep, error) {
	rows, err := q.db.Query(ctx, listRecipeSteps, arg.RecipeID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeStep{}
	for rows.Next() {
		var i RecipeStep
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.HouseholdID,
			&i.SortOrder,
			&i.Text,
			&i.TimerSeconds,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at FROM recipes
WHERE household_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context, householdID uuid.UUID) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipes, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.SourceDomain,
			&i.ImageUrl,
			&i.PrepTime,
			&i.CookTime,
			&i.TotalTime,
			&i.Servings,
			&i.ServingsUnit,
			&i.Categories,
			&i.Cuisine,
			&i.Tags,
			&i.Difficulty,
			&i.Rating,
			&i.Notes,
			&i.IsFavorite,
			&i.TimesCooked,
			&i.LastCookedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipes = `-- name: SearchRecipes :many
SELECT id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at FROM recipes
WHERE household_id = $1
  AND (
      title ILIKE '%' || $2 || '%'
      OR notes ILIKE '%' || $2 || '%'
      OR cuisine ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
`

type SearchRecipesParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Column2     *string   `json:"column_2"`
}

func (q *Queries) SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, searchRecipes, arg.HouseholdID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.SourceDomain,
			&i.ImageUrl,
			&i.PrepTime,
			&i.CookTime,
			&i.TotalTime,
			&i.Servings,
			&i.ServingsUnit,
			&i.Categories,
			&i.Cuisine,
			&i.Tags,
			&i.Difficulty,
			&i.Rating,
			&i.Notes,
			&i.IsFavorite,
			&i.TimesCooked,
			&i.LastCookedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET
    title        = COALESCE($3, title),
    notes        = COALESCE($4, notes),
    rating       = COALESCE($5, rating),
    is_favorite  = COALESCE($6, is_favorite),
    tags         = COALESCE($7, tags),
    categories   = COALESCE($8, categories),
    difficulty   = COALESCE($9, difficulty),
    updated_at   = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, title, description, source_url, source_domain, image_url, prep_time, cook_time, total_time, servings, servings_unit, categories, cuisine, tags, difficulty, rating, notes, is_favorite, times_cooked, last_cooked_at, created_by, created_at, updated_at
`

type UpdateRecipeParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Title       *string   `json:"title"`
	Notes       *string   `json:"notes"`
	Rating      *int32    `json:"rating"`
	IsFavorite  *bool     `json:"is_favorite"`
	Tags        []string  `json:"tags"`
	Categories  []string  `json:"categories"`
	Difficulty  *string   `json:"difficulty"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.HouseholdID,
		arg.Title,
		arg.Notes,
		arg.Rating,
		arg.IsFavorite,
		arg.Tags,
		arg.Categories,
		arg.Difficulty,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.SourceDomain,
		&i.ImageUrl,
		&i.PrepTime,
		&i.CookTime,
		&i.TotalTime,
		&i.Servings,
		&i.ServingsUnit,
		&i.Categories,
		&i.Cuisine,
		&i.Tags,
		&i.Difficulty,
		&i.Rating,
		&i.Notes,
		&i.IsFavorite,
		&i.TimesCooked,
		&i.LastCookedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
