// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reward.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveReward = `-- name: ArchiveReward :exec
UPDATE rewards SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND household_id = $2
`

type ArchiveRewardParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ArchiveReward(ctx context.Context, arg ArchiveRewardParams) error {
	_, err := q.db.Exec(ctx, archiveReward, arg.ID, arg.HouseholdID)
	return err
}

const clearSavingsGoal = `-- name: ClearSavingsGoal :exec
UPDATE savings_goals SET cleared_at = NOW()
WHERE member_id = $1 AND cleared_at IS NULL
`

func (q *Queries) ClearSavingsGoal(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSavingsGoal, memberID)
	return err
}

const createRedemption = `-- name: CreateRedemption :one

INSERT INTO redemptions (id, household_id, reward_id, member_id, points_at_redemption, status, requested_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, household_id, reward_id, member_id, points_at_redemption, status, requested_at, decided_at, decided_by_account_id, fulfilled_at, decline_reason, grant_id
`

type CreateRedemptionParams struct {
	ID                 uuid.UUID `json:"id"`
	HouseholdID        uuid.UUID `json:"household_id"`
	RewardID           uuid.UUID `json:"reward_id"`
	MemberID           uuid.UUID `json:"member_id"`
	PointsAtRedemption int32     `json:"points_at_redemption"`
	Status             string    `json:"status"`
}

// ── Redemptions ─────────────────────────────────────────────────────────────
func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, createRedemption,
		arg.ID,
		arg.HouseholdID,
		arg.RewardID,
		arg.MemberID,
		arg.PointsAtRedemption,
		arg.Status,
	)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.RewardID,
		&i.MemberID,
		&i.PointsAtRedemption,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedByAccountID,
		&i.FulfilledAt,
		&i.DeclineReason,
		&i.GrantID,
	)
	return i, err
}

const createReward = `-- name: CreateReward :one


INSERT INTO rewards (id, household_id, name, description, image_url, cost_points, fulfillment_kind, active, created_by_account_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, household_id, name, description, image_url, cost_points, fulfillment_kind, active, created_by_account_id, created_at, updated_at
`

type CreateRewardParams struct {
	ID                 uuid.UUID      `json:"id"`
	HouseholdID        uuid.UUID      `json:"household_id"`
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	ImageUrl           *string        `json:"image_url"`
	CostPoints         int32          `json:"cost_points"`
	FulfillmentKind    string         `json:"fulfillment_kind"`
	Active             bool           `json:"active"`
	CreatedByAccountID *uuid.NullUUID `json:"created_by_account_id"`
}

// sql/queries/reward.sql
// ── Rewards catalog ─────────────────────────────────────────────────────────
func (q *Queries) CreateReward(ctx context.Context, arg CreateRewardParams) (Reward, error) {
	row := q.db.QueryRow(ctx, createReward,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.CostPoints,
		arg.FulfillmentKind,
		arg.Active,
		arg.CreatedByAccountID,
	)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CostPoints,
		&i.FulfillmentKind,
		&i.Active,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRewardCostAdjustment = `-- name: CreateRewardCostAdjustment :one

INSERT INTO reward_cost_adjustments (id, household_id, member_id, reward_id, delta_points, reason, expires_at, created_by_account_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id, household_id, member_id, reward_id, delta_points, reason, expires_at, created_by_account_id, created_at
`

type CreateRewardCostAdjustmentParams struct {
	ID                 uuid.UUID          `json:"id"`
	HouseholdID        uuid.UUID          `json:"household_id"`
	MemberID           uuid.UUID          `json:"member_id"`
	RewardID           uuid.UUID          `json:"reward_id"`
	DeltaPoints        int32              `json:"delta_points"`
	Reason             string             `json:"reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedByAccountID *uuid.NullUUID     `json:"created_by_account_id"`
}

// ── Reward cost adjustments ─────────────────────────────────────────────────
func (q *Queries) CreateRewardCostAdjustment(ctx context.Context, arg CreateRewardCostAdjustmentParams) (RewardCostAdjustment, error) {
	row := q.db.QueryRow(ctx, createRewardCostAdjustment,
		arg.ID,
		arg.HouseholdID,
		arg.MemberID,
		arg.RewardID,
		arg.DeltaPoints,
		arg.Reason,
		arg.ExpiresAt,
		arg.CreatedByAccountID,
	)
	var i RewardCostAdjustment
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.RewardID,
		&i.DeltaPoints,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRewardCostAdjustment = `-- name: DeleteRewardCostAdjustment :exec
DELETE FROM reward_cost_adjustments
WHERE id = $1 AND household_id = $2
`

type DeleteRewardCostAdjustmentParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteRewardCostAdjustment(ctx context.Context, arg DeleteRewardCostAdjustmentParams) error {
	_, err := q.db.Exec(ctx, deleteRewardCostAdjustment, arg.ID, arg.HouseholdID)
	return err
}

const getActiveSavingsGoal = `-- name: GetActiveSavingsGoal :one

SELECT id, member_id, reward_id, started_at, cleared_at FROM savings_goals
WHERE member_id = $1 AND cleared_at IS NULL
LIMIT 1
`

// ── Savings goals ───────────────────────────────────────────────────────────
func (q *Queries) GetActiveSavingsGoal(ctx context.Context, memberID uuid.UUID) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, getActiveSavingsGoal, memberID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RewardID,
		&i.StartedAt,
		&i.ClearedAt,
	)
	return i, err
}

const getRedemption = `-- name: GetRedemption :one
SELECT id, household_id, reward_id, member_id, points_at_redemption, status, requested_at, decided_at, decided_by_account_id, fulfilled_at, decline_reason, grant_id FROM redemptions WHERE id = $1 AND household_id = $2 LIMIT 1
`

type GetRedemptionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetRedemption(ctx context.Context, arg GetRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, getRedemption, arg.ID, arg.HouseholdID)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.RewardID,
		&i.MemberID,
		&i.PointsAtRedemption,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedByAccountID,
		&i.FulfilledAt,
		&i.DeclineReason,
		&i.GrantID,
	)
	return i, err
}

const getReward = `-- name: GetReward :one
SELECT id, household_id, name, description, image_url, cost_points, fulfillment_kind, active, created_by_account_id, created_at, updated_at FROM rewards WHERE id = $1 AND household_id = $2 LIMIT 1
`

type GetRewardParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetReward(ctx context.Context, arg GetRewardParams) (Reward, error) {
	row := q.db.QueryRow(ctx, getReward, arg.ID, arg.HouseholdID)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CostPoints,
		&i.FulfillmentKind,
		&i.Active,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRewardCostAdjustments = `-- name: ListActiveRewardCostAdjustments :many
SELECT id, household_id, member_id, reward_id, delta_points, reason, expires_at, created_by_account_id, created_at FROM reward_cost_adjustments
WHERE member_id = $1 AND reward_id = $2
  AND (expires_at IS NULL OR expires_at > NOW())
`

type ListActiveRewardCostAdjustmentsParams struct {
	MemberID uuid.UUID `json:"member_id"`
	RewardID uuid.UUID `json:"reward_id"`
}

func (q *Queries) ListActiveRewardCostAdjustments(ctx context.Context, arg ListActiveRewardCostAdjustmentsParams) ([]RewardCostAdjustment, error) {
	rows, err := q.db.Query(ctx, listActiveRewardCostAdjustments, arg.MemberID, arg.RewardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RewardCostAdjustment{}
	for rows.Next() {
		var i RewardCostAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.RewardID,
			&i.DeltaPoints,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedByAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRewardCostAdjustments = `-- name: ListAllRewardCostAdjustments :many
SELECT id, household_id, member_id, reward_id, delta_points, reason, expires_at, created_by_account_id, created_at FROM reward_cost_adjustments
WHERE household_id = $1
  AND ($2::uuid IS NULL OR member_id = $2::uuid)
  AND ($3::uuid IS NULL OR reward_id = $3::uuid)
ORDER BY created_at DESC
`

type ListAllRewardCostAdjustmentsParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	MemberID    *uuid.NullUUID `json:"member_id"`
	RewardID    *uuid.NullUUID `json:"reward_id"`
}

func (q *Queries) ListAllRewardCostAdjustments(ctx context.Context, arg ListAllRewardCostAdjustmentsParams) ([]RewardCostAdjustment, error) {
	rows, err := q.db.Query(ctx, listAllRewardCostAdjustments, arg.HouseholdID, arg.MemberID, arg.RewardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RewardCostAdjustment{}
	for rows.Next() {
		var i RewardCostAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.RewardID,
			&i.DeltaPoints,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedByAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedemptions = `-- name: ListRedemptions :many
SELECT id, household_id, reward_id, member_id, points_at_redemption, status, requested_at, decided_at, decided_by_account_id, fulfilled_at, decline_reason, grant_id FROM redemptions
WHERE household_id = $1
  AND ($4::uuid IS NULL OR member_id = $4::uuid)
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY requested_at DESC
LIMIT $2 OFFSET $3
`

type ListRedemptionsParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
	MemberID    *uuid.NullUUID `json:"member_id"`
	Status      *string        `json:"status"`
}

func (q *Queries) ListRedemptions(ctx context.Context, arg ListRedemptionsParams) ([]Redemption, error) {
	rows, err := q.db.Query(ctx, listRedemptions,
		arg.HouseholdID,
		arg.Limit,
		arg.Offset,
		arg.MemberID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Redemption{}
	for rows.Next() {
		var i Redemption
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.RewardID,
			&i.MemberID,
			&i.PointsAtRedemption,
			&i.Status,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.DecidedByAccountID,
			&i.FulfilledAt,
			&i.DeclineReason,
			&i.GrantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, household_id, name, description, image_url, cost_points, fulfillment_kind, active, created_by_account_id, created_at, updated_at FROM rewards
WHERE household_id = $1
  AND ($2::boolean = FALSE OR active = TRUE)
ORDER BY name ASC
`

type ListRewardsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	OnlyActive  bool      `json:"only_active"`
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]Reward, error) {
	rows, err := q.db.Query(ctx, listRewards, arg.HouseholdID, arg.OnlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reward{}
	for rows.Next() {
		var i Reward
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CostPoints,
			&i.FulfillmentKind,
			&i.Active,
			&i.CreatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRedemptionStatus = `-- name: SetRedemptionStatus :one
UPDATE redemptions
SET status                = $3,
    decided_at            = COALESCE($4, decided_at),
    decided_by_account_id = COALESCE($5::uuid, decided_by_account_id),
    fulfilled_at          = COALESCE($6, fulfilled_at),
    decline_reason        = COALESCE($7, decline_reason),
    grant_id              = COALESCE($8::uuid, grant_id)
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, reward_id, member_id, points_at_redemption, status, requested_at, decided_at, decided_by_account_id, fulfilled_at, decline_reason, grant_id
`

type SetRedemptionStatusParams struct {
	ID                 uuid.UUID          `json:"id"`
	HouseholdID        uuid.UUID          `json:"household_id"`
	Status             string             `json:"status"`
	DecidedAt          pgtype.Timestamptz `json:"decided_at"`
	DecidedByAccountID *uuid.NullUUID     `json:"decided_by_account_id"`
	FulfilledAt        pgtype.Timestamptz `json:"fulfilled_at"`
	DeclineReason      *string            `json:"decline_reason"`
	GrantID            *uuid.NullUUID     `json:"grant_id"`
}

func (q *Queries) SetRedemptionStatus(ctx context.Context, arg SetRedemptionStatusParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, setRedemptionStatus,
		arg.ID,
		arg.HouseholdID,
		arg.Status,
		arg.DecidedAt,
		arg.DecidedByAccountID,
		arg.FulfilledAt,
		arg.DeclineReason,
		arg.GrantID,
	)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.RewardID,
		&i.MemberID,
		&i.PointsAtRedemption,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedByAccountID,
		&i.FulfilledAt,
		&i.DeclineReason,
		&i.GrantID,
	)
	return i, err
}

const timelineForMember = `-- name: TimelineForMember :many

SELECT
    'point_grant'::text         AS kind,
    pg.id                        AS id,
    pg.granted_at                AS occurred_at,
    pg.points::BIGINT            AS amount,
    pg.reason                    AS reason,
    pg.behavior_id::text         AS ref_a,
    pg.category_id::text         AS ref_b
FROM point_grants pg
WHERE pg.member_id = $1
UNION ALL
SELECT
    'redemption'::text,
    r.id,
    r.requested_at,
    r.points_at_redemption::BIGINT,
    r.status,
    r.reward_id::text,
    NULL
FROM redemptions r
WHERE r.member_id = $1
UNION ALL
SELECT
    'reward_cost_adjustment'::text,
    rca.id,
    rca.created_at,
    rca.delta_points::BIGINT,
    rca.reason,
    rca.reward_id::text,
    NULL
FROM reward_cost_adjustments rca
WHERE rca.member_id = $1
UNION ALL
SELECT
    'wallet_transaction'::text,
    wt.id,
    wt.created_at,
    wt.amount_cents,
    wt.reason,
    wt.kind,
    NULL
FROM wallet_transactions wt
WHERE wt.member_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type TimelineForMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type TimelineForMemberRow struct {
	Kind       string             `json:"kind"`
	ID         uuid.UUID          `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Amount     int64              `json:"amount"`
	Reason     string             `json:"reason"`
	RefA       string             `json:"ref_a"`
	RefB       string             `json:"ref_b"`
}

// ── Timeline (unified per-kid stream) ───────────────────────────────────────
func (q *Queries) TimelineForMember(ctx context.Context, arg TimelineForMemberParams) ([]TimelineForMemberRow, error) {
	rows, err := q.db.Query(ctx, timelineForMember, arg.MemberID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineForMemberRow{}
	for rows.Next() {
		var i TimelineForMemberRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.OccurredAt,
			&i.Amount,
			&i.Reason,
			&i.RefA,
			&i.RefB,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReward = `-- name: UpdateReward :one
UPDATE rewards
SET name             = COALESCE($3, name),
    description      = COALESCE($4, description),
    image_url        = COALESCE($5, image_url),
    cost_points      = COALESCE($6, cost_points),
    fulfillment_kind = COALESCE($7, fulfillment_kind),
    active           = COALESCE($8, active),
    updated_at       = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, name, description, image_url, cost_points, fulfillment_kind, active, created_by_account_id, created_at, updated_at
`

type UpdateRewardParams struct {
	ID              uuid.UUID `json:"id"`
	HouseholdID     uuid.UUID `json:"household_id"`
	Name            *string   `json:"name"`
	Description     *string   `json:"description"`
	ImageUrl        *string   `json:"image_url"`
	CostPoints      *int32    `json:"cost_points"`
	FulfillmentKind *string   `json:"fulfillment_kind"`
	Active          *bool     `json:"active"`
}

func (q *Queries) UpdateReward(ctx context.Context, arg UpdateRewardParams) (Reward, error) {
	row := q.db.QueryRow(ctx, updateReward,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.CostPoints,
		arg.FulfillmentKind,
		arg.Active,
	)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CostPoints,
		&i.FulfillmentKind,
		&i.Active,
		&i.CreatedByAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSavingsGoal = `-- name: UpsertSavingsGoal :one
INSERT INTO savings_goals (id, member_id, reward_id, started_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (member_id) DO UPDATE
SET reward_id  = EXCLUDED.reward_id,
    started_at = NOW(),
    cleared_at = NULL
RETURNING id, member_id, reward_id, started_at, cleared_at
`

type UpsertSavingsGoalParams struct {
	ID       uuid.UUID `json:"id"`
	MemberID uuid.UUID `json:"member_id"`
	RewardID uuid.UUID `json:"reward_id"`
}

func (q *Queries) UpsertSavingsGoal(ctx context.Context, arg UpsertSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, upsertSavingsGoal, arg.ID, arg.MemberID, arg.RewardID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RewardID,
		&i.StartedAt,
		&i.ClearedAt,
	)
	return i, err
}
