// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routine.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addStep = `-- name: AddStep :one
INSERT INTO routine_steps (
    id, routine_id, name, est_minutes, sort_order, icon, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING id, routine_id, name, est_minutes, sort_order, icon, created_at, updated_at
`

type AddStepParams struct {
	ID         uuid.UUID `json:"id"`
	RoutineID  uuid.UUID `json:"routine_id"`
	Name       string    `json:"name"`
	EstMinutes *int32    `json:"est_minutes"`
	SortOrder  int32     `json:"sort_order"`
	Icon       *string   `json:"icon"`
}

func (q *Queries) AddStep(ctx context.Context, arg AddStepParams) (RoutineStep, error) {
	row := q.db.QueryRow(ctx, addStep,
		arg.ID,
		arg.RoutineID,
		arg.Name,
		arg.EstMinutes,
		arg.SortOrder,
		arg.Icon,
	)
	var i RoutineStep
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.Name,
		&i.EstMinutes,
		&i.SortOrder,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCompletionsForDay = `-- name: CountCompletionsForDay :one
SELECT COUNT(*)::BIGINT
FROM routine_completions
WHERE routine_id = $1
  AND member_id = $2
  AND completed_at::DATE = $3
`

type CountCompletionsForDayParams struct {
	RoutineID   uuid.UUID          `json:"routine_id"`
	MemberID    uuid.UUID          `json:"member_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CountCompletionsForDay(ctx context.Context, arg CountCompletionsForDayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletionsForDay, arg.RoutineID, arg.MemberID, arg.CompletedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countStepsForRoutine = `-- name: CountStepsForRoutine :one
SELECT COUNT(*)::BIGINT
FROM routine_steps
WHERE routine_id = $1
`

func (q *Queries) CountStepsForRoutine(ctx context.Context, routineID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStepsForRoutine, routineID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRoutine = `-- name: CreateRoutine :one

INSERT INTO routines (
    id, household_id, name, member_id, days_of_week, time_slot, archived, sort_order, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
)
RETURNING id, household_id, name, member_id, days_of_week, time_slot, archived, sort_order, created_at, updated_at
`

type CreateRoutineParams struct {
	ID          uuid.UUID      `json:"id"`
	HouseholdID uuid.UUID      `json:"household_id"`
	Name        string         `json:"name"`
	MemberID    *uuid.NullUUID `json:"member_id"`
	DaysOfWeek  []string       `json:"days_of_week"`
	TimeSlot    string         `json:"time_slot"`
	Archived    bool           `json:"archived"`
	SortOrder   int32          `json:"sort_order"`
}

// sql/queries/routine.sql
// Routine, RoutineStep, and RoutineCompletion queries.
func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, createRoutine,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.MemberID,
		arg.DaysOfWeek,
		arg.TimeSlot,
		arg.Archived,
		arg.SortOrder,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.MemberID,
		&i.DaysOfWeek,
		&i.TimeSlot,
		&i.Archived,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoutine = `-- name: DeleteRoutine :exec
DELETE FROM routines
WHERE id = $1 AND household_id = $2
`

type DeleteRoutineParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteRoutine(ctx context.Context, arg DeleteRoutineParams) error {
	_, err := q.db.Exec(ctx, deleteRoutine, arg.ID, arg.HouseholdID)
	return err
}

const deleteStep = `-- name: DeleteStep :exec
DELETE FROM routine_steps
WHERE id = $1
`

func (q *Queries) DeleteStep(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStep, id)
	return err
}

const getDailyCompletionCounts = `-- name: GetDailyCompletionCounts :many
SELECT
    completed_at::DATE AS day,
    COUNT(*)::BIGINT   AS completion_count
FROM routine_completions
WHERE routine_id = $1
  AND member_id  = $2
  AND completed_at >= $3
GROUP BY completed_at::DATE
ORDER BY day DESC
`

type GetDailyCompletionCountsParams struct {
	RoutineID   uuid.UUID          `json:"routine_id"`
	MemberID    uuid.UUID          `json:"member_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type GetDailyCompletionCountsRow struct {
	Day             pgtype.Date `json:"day"`
	CompletionCount int64       `json:"completion_count"`
}

// Returns (date, completion_count) for the past N days for a given routine+member.
func (q *Queries) GetDailyCompletionCounts(ctx context.Context, arg GetDailyCompletionCountsParams) ([]GetDailyCompletionCountsRow, error) {
	rows, err := q.db.Query(ctx, getDailyCompletionCounts, arg.RoutineID, arg.MemberID, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyCompletionCountsRow{}
	for rows.Next() {
		var i GetDailyCompletionCountsRow
		if err := rows.Scan(&i.Day, &i.CompletionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutine = `-- name: GetRoutine :one
SELECT id, household_id, name, member_id, days_of_week, time_slot, archived, sort_order, created_at, updated_at FROM routines
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetRoutineParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetRoutine(ctx context.Context, arg GetRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutine, arg.ID, arg.HouseholdID)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.MemberID,
		&i.DaysOfWeek,
		&i.TimeSlot,
		&i.Archived,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStep = `-- name: GetStep :one
SELECT s.id, s.routine_id, s.name, s.est_minutes, s.sort_order, s.icon, s.created_at, s.updated_at FROM routine_steps s
JOIN routines r ON r.id = s.routine_id
WHERE s.id = $1 AND r.household_id = $2
LIMIT 1
`

type GetStepParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetStep(ctx context.Context, arg GetStepParams) (RoutineStep, error) {
	row := q.db.QueryRow(ctx, getStep, arg.ID, arg.HouseholdID)
	var i RoutineStep
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.Name,
		&i.EstMinutes,
		&i.SortOrder,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompletionsForDay = `-- name: ListCompletionsForDay :many
SELECT rc.id, rc.routine_id, rc.step_id, rc.member_id, rc.completed_at
FROM routine_completions rc
JOIN routines r ON r.id = rc.routine_id
WHERE r.household_id = $1
  AND rc.completed_at::DATE = $2
  AND ($3::uuid IS NULL OR rc.member_id = $3::uuid)
ORDER BY rc.completed_at ASC
`

type ListCompletionsForDayParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	MemberID    *uuid.NullUUID     `json:"member_id"`
}

func (q *Queries) ListCompletionsForDay(ctx context.Context, arg ListCompletionsForDayParams) ([]RoutineCompletion, error) {
	rows, err := q.db.Query(ctx, listCompletionsForDay, arg.HouseholdID, arg.CompletedAt, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutineCompletion{}
	for rows.Next() {
		var i RoutineCompletion
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.StepID,
			&i.MemberID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutines = `-- name: ListRoutines :many
SELECT id, household_id, name, member_id, days_of_week, time_slot, archived, sort_order, created_at, updated_at FROM routines
WHERE household_id = $1
  AND archived = FALSE
  AND ($2::uuid IS NULL OR member_id = $2::uuid)
  AND ($3::text IS NULL OR time_slot = $3::text)
ORDER BY sort_order ASC, created_at ASC
`

type ListRoutinesParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	MemberID    *uuid.NullUUID `json:"member_id"`
	TimeSlot    *string        `json:"time_slot"`
}

func (q *Queries) ListRoutines(ctx context.Context, arg ListRoutinesParams) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutines, arg.HouseholdID, arg.MemberID, arg.TimeSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Routine{}
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.MemberID,
			&i.DaysOfWeek,
			&i.TimeSlot,
			&i.Archived,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSteps = `-- name: ListSteps :many
SELECT id, routine_id, name, est_minutes, sort_order, icon, created_at, updated_at FROM routine_steps
WHERE routine_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListSteps(ctx context.Context, routineID uuid.UUID) ([]RoutineStep, error) {
	rows, err := q.db.Query(ctx, listSteps, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutineStep{}
	for rows.Next() {
		var i RoutineStep
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.Name,
			&i.EstMinutes,
			&i.SortOrder,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRoutineComplete = `-- name: MarkRoutineComplete :one
INSERT INTO routine_completions (id, routine_id, step_id, member_id, completed_at)
VALUES ($1, $2, NULL, $3, NOW())
ON CONFLICT ON CONSTRAINT uq_routine_completion_whole
DO UPDATE SET completed_at = NOW()
RETURNING id, routine_id, step_id, member_id, completed_at
`

type MarkRoutineCompleteParams struct {
	ID        uuid.UUID `json:"id"`
	RoutineID uuid.UUID `json:"routine_id"`
	MemberID  uuid.UUID `json:"member_id"`
}

func (q *Queries) MarkRoutineComplete(ctx context.Context, arg MarkRoutineCompleteParams) (RoutineCompletion, error) {
	row := q.db.QueryRow(ctx, markRoutineComplete, arg.ID, arg.RoutineID, arg.MemberID)
	var i RoutineCompletion
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.StepID,
		&i.MemberID,
		&i.CompletedAt,
	)
	return i, err
}

const markStepComplete = `-- name: MarkStepComplete :one
INSERT INTO routine_completions (id, routine_id, step_id, member_id, completed_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT ON CONSTRAINT uq_routine_completion_step
DO UPDATE SET completed_at = NOW()
RETURNING id, routine_id, step_id, member_id, completed_at
`

type MarkStepCompleteParams struct {
	ID        uuid.UUID      `json:"id"`
	RoutineID uuid.UUID      `json:"routine_id"`
	StepID    *uuid.NullUUID `json:"step_id"`
	MemberID  uuid.UUID      `json:"member_id"`
}

func (q *Queries) MarkStepComplete(ctx context.Context, arg MarkStepCompleteParams) (RoutineCompletion, error) {
	row := q.db.QueryRow(ctx, markStepComplete,
		arg.ID,
		arg.RoutineID,
		arg.StepID,
		arg.MemberID,
	)
	var i RoutineCompletion
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.StepID,
		&i.MemberID,
		&i.CompletedAt,
	)
	return i, err
}

const unmarkCompletion = `-- name: UnmarkCompletion :exec
DELETE FROM routine_completions
WHERE id = $1
`

func (q *Queries) UnmarkCompletion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unmarkCompletion, id)
	return err
}

const updateRoutine = `-- name: UpdateRoutine :one
UPDATE routines
SET
    name         = COALESCE($3, name),
    member_id    = COALESCE($4, member_id),
    days_of_week = COALESCE($5, days_of_week),
    time_slot    = COALESCE($6, time_slot),
    archived     = COALESCE($7, archived),
    sort_order   = COALESCE($8, sort_order),
    updated_at   = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, name, member_id, days_of_week, time_slot, archived, sort_order, created_at, updated_at
`

type UpdateRoutineParams struct {
	ID          uuid.UUID      `json:"id"`
	HouseholdID uuid.UUID      `json:"household_id"`
	Name        *string        `json:"name"`
	MemberID    *uuid.NullUUID `json:"member_id"`
	DaysOfWeek  []string       `json:"days_of_week"`
	TimeSlot    *string        `json:"time_slot"`
	Archived    *bool          `json:"archived"`
	SortOrder   *int32         `json:"sort_order"`
}

func (q *Queries) UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, updateRoutine,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.MemberID,
		arg.DaysOfWeek,
		arg.TimeSlot,
		arg.Archived,
		arg.SortOrder,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.MemberID,
		&i.DaysOfWeek,
		&i.TimeSlot,
		&i.Archived,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStep = `-- name: UpdateStep :one
UPDATE routine_steps
SET
    name        = COALESCE($2, name),
    est_minutes = COALESCE($3, est_minutes),
    sort_order  = COALESCE($4, sort_order),
    icon        = COALESCE($5, icon),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, routine_id, name, est_minutes, sort_order, icon, created_at, updated_at
`

type UpdateStepParams struct {
	ID         uuid.UUID `json:"id"`
	Name       *string   `json:"name"`
	EstMinutes *int32    `json:"est_minutes"`
	SortOrder  *int32    `json:"sort_order"`
	Icon       *string   `json:"icon"`
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) (RoutineStep, error) {
	row := q.db.QueryRow(ctx, updateStep,
		arg.ID,
		arg.Name,
		arg.EstMinutes,
		arg.SortOrder,
		arg.Icon,
	)
	var i RoutineStep
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.Name,
		&i.EstMinutes,
		&i.SortOrder,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
