// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopping.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShoppingList = `-- name: CreateShoppingList :one

INSERT INTO shopping_lists (household_id, name, date_from, date_to, is_active)
VALUES ($1, $2, $3, $4, true)
RETURNING id, household_id, name, date_from, date_to, is_active, created_at, updated_at
`

type CreateShoppingListParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Name        string      `json:"name"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
}

// sql/queries/shopping.sql
// Shopping list queries. Run `sqlc generate` to produce Go code in internal/query/.
func (q *Queries) CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, createShoppingList,
		arg.HouseholdID,
		arg.Name,
		arg.DateFrom,
		arg.DateTo,
	)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.DateFrom,
		&i.DateTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateShoppingLists = `-- name: DeactivateShoppingLists :exec
UPDATE shopping_lists
SET is_active = false, updated_at = NOW()
WHERE household_id = $1 AND is_active = true
`

func (q *Queries) DeactivateShoppingLists(ctx context.Context, householdID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateShoppingLists, householdID)
	return err
}

const deletePantryStaple = `-- name: DeletePantryStaple :exec
DELETE FROM pantry_staples
WHERE id = $1 AND household_id = $2
`

type DeletePantryStapleParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeletePantryStaple(ctx context.Context, arg DeletePantryStapleParams) error {
	_, err := q.db.Exec(ctx, deletePantryStaple, arg.ID, arg.HouseholdID)
	return err
}

const deleteShoppingListItems = `-- name: DeleteShoppingListItems :exec
DELETE FROM shopping_list_items
WHERE shopping_list_id = $1
`

func (q *Queries) DeleteShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShoppingListItems, shoppingListID)
	return err
}

const getActiveShoppingList = `-- name: GetActiveShoppingList :one
SELECT id, household_id, name, date_from, date_to, is_active, created_at, updated_at FROM shopping_lists
WHERE household_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveShoppingList(ctx context.Context, householdID uuid.UUID) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, getActiveShoppingList, householdID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.DateFrom,
		&i.DateTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShoppingList = `-- name: GetShoppingList :one
SELECT id, household_id, name, date_from, date_to, is_active, created_at, updated_at FROM shopping_lists
WHERE id = $1 AND household_id = $2
LIMIT 1
`

type GetShoppingListParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetShoppingList(ctx context.Context, arg GetShoppingListParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, getShoppingList, arg.ID, arg.HouseholdID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.DateFrom,
		&i.DateTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertShoppingListItem = `-- name: InsertShoppingListItem :one
INSERT INTO shopping_list_items (shopping_list_id, household_id, name, amount, unit, aisle, source_recipes, completed, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, shopping_list_id, household_id, name, amount, unit, aisle, source_recipes, completed, sort_order, created_at, updated_at
`

type InsertShoppingListItemParams struct {
	ShoppingListID uuid.UUID      `json:"shopping_list_id"`
	HouseholdID    uuid.UUID      `json:"household_id"`
	Name           string         `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	Unit           string         `json:"unit"`
	Aisle          string         `json:"aisle"`
	SourceRecipes  []string       `json:"source_recipes"`
	Completed      bool           `json:"completed"`
	SortOrder      int32          `json:"sort_order"`
}

func (q *Queries) InsertShoppingListItem(ctx context.Context, arg InsertShoppingListItemParams) (ShoppingListItem, error) {
	row := q.db.QueryRow(ctx, insertShoppingListItem,
		arg.ShoppingListID,
		arg.HouseholdID,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.Aisle,
		arg.SourceRecipes,
		arg.Completed,
		arg.SortOrder,
	)
	var i ShoppingListItem
	err := row.Scan(
		&i.ID,
		&i.ShoppingListID,
		&i.HouseholdID,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.Aisle,
		&i.SourceRecipes,
		&i.Completed,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIngredientsForMealPlanRange = `-- name: ListIngredientsForMealPlanRange :many

SELECT
    r.id AS recipe_id,
    ri.name,
    ri.amount,
    ri.unit,
    ri.optional,
    r.title      AS recipe_title,
    COALESCE(ic.category, '') AS aisle
FROM meal_plan_entries mpe
JOIN recipes            r   ON r.id = mpe.recipe_id
JOIN recipe_ingredients ri  ON ri.recipe_id = r.id
LEFT JOIN ingredient_canonical ic ON ic.name ILIKE ri.name
WHERE mpe.household_id = $1
  AND mpe.date >= $2
  AND mpe.date <= $3
  AND mpe.recipe_id IS NOT NULL
ORDER BY aisle, ri.name
`

type ListIngredientsForMealPlanRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Date        pgtype.Date `json:"date"`
	Date_2      pgtype.Date `json:"date_2"`
}

type ListIngredientsForMealPlanRangeRow struct {
	RecipeID    uuid.UUID      `json:"recipe_id"`
	Name        string         `json:"name"`
	Amount      pgtype.Numeric `json:"amount"`
	Unit        string         `json:"unit"`
	Optional    bool           `json:"optional"`
	RecipeTitle string         `json:"recipe_title"`
	Aisle       string         `json:"aisle"`
}

// Ingredient join for shopping list generation:
// fetch all recipe_ingredients for recipes that appear in meal plan entries
// within the given date range for the household.
func (q *Queries) ListIngredientsForMealPlanRange(ctx context.Context, arg ListIngredientsForMealPlanRangeParams) ([]ListIngredientsForMealPlanRangeRow, error) {
	rows, err := q.db.Query(ctx, listIngredientsForMealPlanRange, arg.HouseholdID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngredientsForMealPlanRangeRow{}
	for rows.Next() {
		var i ListIngredientsForMealPlanRangeRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.Optional,
			&i.RecipeTitle,
			&i.Aisle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPantryStaples = `-- name: ListPantryStaples :many
SELECT id, household_id, name, amount, unit, aisle, created_at, updated_at FROM pantry_staples
WHERE household_id = $1
ORDER BY aisle, name
`

func (q *Queries) ListPantryStaples(ctx context.Context, householdID uuid.UUID) ([]PantryStaple, error) {
	rows, err := q.db.Query(ctx, listPantryStaples, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PantryStaple{}
	for rows.Next() {
		var i PantryStaple
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.Aisle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingListItems = `-- name: ListShoppingListItems :many
SELECT id, shopping_list_id, household_id, name, amount, unit, aisle, source_recipes, completed, sort_order, created_at, updated_at FROM shopping_list_items
WHERE shopping_list_id = $1
ORDER BY aisle, sort_order, name
`

func (q *Queries) ListShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) ([]ShoppingListItem, error) {
	rows, err := q.db.Query(ctx, listShoppingListItems, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShoppingListItem{}
	for rows.Next() {
		var i ShoppingListItem
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.HouseholdID,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.Aisle,
			&i.SourceRecipes,
			&i.Completed,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIngredients = `-- name: SearchIngredients :many

SELECT id, name, aliases, category, default_unit, unit_conversions FROM ingredient_canonical
WHERE name ILIKE '%' || $1 || '%'
   OR EXISTS (
       SELECT 1 FROM unnest(aliases) AS a WHERE a ILIKE '%' || $1 || '%'
   )
ORDER BY name
LIMIT 25
`

// Canonical ingredient search
func (q *Queries) SearchIngredients(ctx context.Context, dollar_1 *string) ([]IngredientCanonical, error) {
	rows, err := q.db.Query(ctx, searchIngredients, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngredientCanonical{}
	for rows.Next() {
		var i IngredientCanonical
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Aliases,
			&i.Category,
			&i.DefaultUnit,
			&i.UnitConversions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoppingListItem = `-- name: UpdateShoppingListItem :one
UPDATE shopping_list_items
SET completed = $3, updated_at = NOW()
WHERE id = $1 AND household_id = $2
RETURNING id, shopping_list_id, household_id, name, amount, unit, aisle, source_recipes, completed, sort_order, created_at, updated_at
`

type UpdateShoppingListItemParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Completed   bool      `json:"completed"`
}

func (q *Queries) UpdateShoppingListItem(ctx context.Context, arg UpdateShoppingListItemParams) (ShoppingListItem, error) {
	row := q.db.QueryRow(ctx, updateShoppingListItem, arg.ID, arg.HouseholdID, arg.Completed)
	var i ShoppingListItem
	err := row.Scan(
		&i.ID,
		&i.ShoppingListID,
		&i.HouseholdID,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.Aisle,
		&i.SourceRecipes,
		&i.Completed,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPantryStaple = `-- name: UpsertPantryStaple :one

INSERT INTO pantry_staples (household_id, name, amount, unit, aisle)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (household_id, name)
DO UPDATE SET amount = EXCLUDED.amount, unit = EXCLUDED.unit, aisle = EXCLUDED.aisle, updated_at = NOW()
RETURNING id, household_id, name, amount, unit, aisle, created_at, updated_at
`

type UpsertPantryStapleParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	Name        string         `json:"name"`
	Amount      pgtype.Numeric `json:"amount"`
	Unit        string         `json:"unit"`
	Aisle       string         `json:"aisle"`
}

// Pantry staples
func (q *Queries) UpsertPantryStaple(ctx context.Context, arg UpsertPantryStapleParams) (PantryStaple, error) {
	row := q.db.QueryRow(ctx, upsertPantryStaple,
		arg.HouseholdID,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.Aisle,
	)
	var i PantryStaple
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.Aisle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
