// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionByCustomer = `-- name: GetSubscriptionByCustomer :one
SELECT id, household_id, stripe_customer_id, stripe_subscription_id, status, current_period_end, created_at, updated_at FROM subscriptions
WHERE stripe_customer_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByCustomer(ctx context.Context, stripeCustomerID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByCustomer, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByHousehold = `-- name: GetSubscriptionByHousehold :one
SELECT id, household_id, stripe_customer_id, stripe_subscription_id, status, current_period_end, created_at, updated_at FROM subscriptions
WHERE household_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByHousehold(ctx context.Context, householdID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByHousehold, householdID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET
    status             = $2,
    current_period_end = $3,
    updated_at         = NOW()
WHERE stripe_subscription_id = $1
`

type UpdateSubscriptionStatusParams struct {
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.StripeSubscriptionID, arg.Status, arg.CurrentPeriodEnd)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :one

INSERT INTO subscriptions (
    id,
    household_id,
    stripe_customer_id,
    stripe_subscription_id,
    status,
    current_period_end,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, NOW(), NOW()
)
ON CONFLICT (household_id) DO UPDATE SET
    stripe_customer_id     = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    status                 = EXCLUDED.status,
    current_period_end     = EXCLUDED.current_period_end,
    updated_at             = NOW()
RETURNING id, household_id, stripe_customer_id, stripe_subscription_id, status, current_period_end, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	HouseholdID          uuid.UUID          `json:"household_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

// sql/queries/subscription.sql
// Stripe subscription queries. Run `sqlc generate` to produce Go code.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.HouseholdID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
