// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustWalletBalance = `-- name: AdjustWalletBalance :one
UPDATE wallets
SET balance_cents = balance_cents + $2,
    updated_at = NOW()
WHERE member_id = $1
RETURNING id, member_id, balance_cents, updated_at
`

type AdjustWalletBalanceParams struct {
	MemberID     uuid.UUID `json:"member_id"`
	BalanceCents int64     `json:"balance_cents"`
}

func (q *Queries) AdjustWalletBalance(ctx context.Context, arg AdjustWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, adjustWalletBalance, arg.MemberID, arg.BalanceCents)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BalanceCents,
		&i.UpdatedAt,
	)
	return i, err
}

const approveAdHocTask = `-- name: ApproveAdHocTask :one
UPDATE ad_hoc_tasks
SET status = 'approved', approved_at = NOW(), approved_by_account_id = $3
WHERE id = $1 AND household_id = $2 AND status = 'pending'
RETURNING id, household_id, member_id, name, payout_cents, requires_approval, status, created_by_account_id, completed_at, approved_at, approved_by_account_id, decline_reason, expires_at, created_at
`

type ApproveAdHocTaskParams struct {
	ID                  uuid.UUID      `json:"id"`
	HouseholdID         uuid.UUID      `json:"household_id"`
	ApprovedByAccountID *uuid.NullUUID `json:"approved_by_account_id"`
}

func (q *Queries) ApproveAdHocTask(ctx context.Context, arg ApproveAdHocTaskParams) (AdHocTask, error) {
	row := q.db.QueryRow(ctx, approveAdHocTask, arg.ID, arg.HouseholdID, arg.ApprovedByAccountID)
	var i AdHocTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.PayoutCents,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedByAccountID,
		&i.CompletedAt,
		&i.ApprovedAt,
		&i.ApprovedByAccountID,
		&i.DeclineReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAdHocTask = `-- name: CreateAdHocTask :one

INSERT INTO ad_hoc_tasks (
    id, household_id, member_id, name, payout_cents, requires_approval, status, created_by_account_id, expires_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, 'open', $6, $7
)
RETURNING id, household_id, member_id, name, payout_cents, requires_approval, status, created_by_account_id, completed_at, approved_at, approved_by_account_id, decline_reason, expires_at, created_at
`

type CreateAdHocTaskParams struct {
	HouseholdID        uuid.UUID          `json:"household_id"`
	MemberID           uuid.UUID          `json:"member_id"`
	Name               string             `json:"name"`
	PayoutCents        int32              `json:"payout_cents"`
	RequiresApproval   bool               `json:"requires_approval"`
	CreatedByAccountID *uuid.NullUUID     `json:"created_by_account_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

// ── Ad-hoc tasks ─────────────────────────────────────────────────────────────
func (q *Queries) CreateAdHocTask(ctx context.Context, arg CreateAdHocTaskParams) (AdHocTask, error) {
	row := q.db.QueryRow(ctx, createAdHocTask,
		arg.HouseholdID,
		arg.MemberID,
		arg.Name,
		arg.PayoutCents,
		arg.RequiresApproval,
		arg.CreatedByAccountID,
		arg.ExpiresAt,
	)
	var i AdHocTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.PayoutCents,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedByAccountID,
		&i.CompletedAt,
		&i.ApprovedAt,
		&i.ApprovedByAccountID,
		&i.DeclineReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one

INSERT INTO wallet_transactions (
    id, wallet_id, member_id, amount_cents, kind, reference_id, reason, created_by_account_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
RETURNING id, wallet_id, member_id, amount_cents, kind, reference_id, reason, created_by_account_id, created_at
`

type CreateWalletTransactionParams struct {
	ID                 uuid.UUID      `json:"id"`
	WalletID           uuid.UUID      `json:"wallet_id"`
	MemberID           uuid.UUID      `json:"member_id"`
	AmountCents        int64          `json:"amount_cents"`
	Kind               string         `json:"kind"`
	ReferenceID        *uuid.NullUUID `json:"reference_id"`
	Reason             string         `json:"reason"`
	CreatedByAccountID *uuid.NullUUID `json:"created_by_account_id"`
}

// ── Wallet transactions ─────────────────────────────────────────────────────
func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction,
		arg.ID,
		arg.WalletID,
		arg.MemberID,
		arg.AmountCents,
		arg.Kind,
		arg.ReferenceID,
		arg.Reason,
		arg.CreatedByAccountID,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.MemberID,
		&i.AmountCents,
		&i.Kind,
		&i.ReferenceID,
		&i.Reason,
		&i.CreatedByAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const declineAdHocTask = `-- name: DeclineAdHocTask :one
UPDATE ad_hoc_tasks
SET status = 'declined', decline_reason = $3
WHERE id = $1 AND household_id = $2 AND status = 'pending'
RETURNING id, household_id, member_id, name, payout_cents, requires_approval, status, created_by_account_id, completed_at, approved_at, approved_by_account_id, decline_reason, expires_at, created_at
`

type DeclineAdHocTaskParams struct {
	ID            uuid.UUID `json:"id"`
	HouseholdID   uuid.UUID `json:"household_id"`
	DeclineReason string    `json:"decline_reason"`
}

func (q *Queries) DeclineAdHocTask(ctx context.Context, arg DeclineAdHocTaskParams) (AdHocTask, error) {
	row := q.db.QueryRow(ctx, declineAdHocTask, arg.ID, arg.HouseholdID, arg.DeclineReason)
	var i AdHocTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.PayoutCents,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedByAccountID,
		&i.CompletedAt,
		&i.ApprovedAt,
		&i.ApprovedByAccountID,
		&i.DeclineReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAllowance = `-- name: GetActiveAllowance :one

SELECT id, household_id, member_id, amount_cents, active_from, created_at FROM allowance_settings
WHERE member_id = $1 AND active_from <= CURRENT_DATE
ORDER BY active_from DESC
LIMIT 1
`

// ── Allowance ────────────────────────────────────────────────────────────────
func (q *Queries) GetActiveAllowance(ctx context.Context, memberID uuid.UUID) (AllowanceSetting, error) {
	row := q.db.QueryRow(ctx, getActiveAllowance, memberID)
	var i AllowanceSetting
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.AmountCents,
		&i.ActiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const getAdHocTask = `-- name: GetAdHocTask :one
SELECT id, household_id, member_id, name, payout_cents, requires_approval, status, created_by_account_id, completed_at, approved_at, approved_by_account_id, decline_reason, expires_at, created_at FROM ad_hoc_tasks WHERE id = $1 AND household_id = $2
`

type GetAdHocTaskParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetAdHocTask(ctx context.Context, arg GetAdHocTaskParams) (AdHocTask, error) {
	row := q.db.QueryRow(ctx, getAdHocTask, arg.ID, arg.HouseholdID)
	var i AdHocTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.PayoutCents,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedByAccountID,
		&i.CompletedAt,
		&i.ApprovedAt,
		&i.ApprovedByAccountID,
		&i.DeclineReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateWallet = `-- name: GetOrCreateWallet :one


INSERT INTO wallets (id, member_id, balance_cents, updated_at)
VALUES (gen_random_uuid(), $1, 0, NOW())
ON CONFLICT (member_id) DO UPDATE SET updated_at = wallets.updated_at
RETURNING id, member_id, balance_cents, updated_at
`

// sql/queries/wallet.sql
// ── Wallets ─────────────────────────────────────────────────────────────────
func (q *Queries) GetOrCreateWallet(ctx context.Context, memberID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getOrCreateWallet, memberID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BalanceCents,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByMember = `-- name: GetWalletByMember :one
SELECT id, member_id, balance_cents, updated_at FROM wallets WHERE member_id = $1
`

func (q *Queries) GetWalletByMember(ctx context.Context, memberID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByMember, memberID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BalanceCents,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeeklySummary = `-- name: GetWeeklySummary :one
SELECT id, household_id, member_id, week_start, earned_cents, streak_bonus_cents, chores_completed, chores_possible, created_at FROM weekly_summaries WHERE member_id = $1 AND week_start = $2
`

type GetWeeklySummaryParams struct {
	MemberID  uuid.UUID   `json:"member_id"`
	WeekStart pgtype.Date `json:"week_start"`
}

func (q *Queries) GetWeeklySummary(ctx context.Context, arg GetWeeklySummaryParams) (WeeklySummary, error) {
	row := q.db.QueryRow(ctx, getWeeklySummary, arg.MemberID, arg.WeekStart)
	var i WeeklySummary
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.WeekStart,
		&i.EarnedCents,
		&i.StreakBonusCents,
		&i.ChoresCompleted,
		&i.ChoresPossible,
		&i.CreatedAt,
	)
	return i, err
}

const listAdHocTasks = `-- name: ListAdHocTasks :many
SELECT id, household_id, member_id, name, payout_cents, requires_approval, status, created_by_account_id, completed_at, approved_at, approved_by_account_id, decline_reason, expires_at, created_at FROM ad_hoc_tasks
WHERE household_id = $1
  AND ($2::uuid IS NULL OR member_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
`

type ListAdHocTasksParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	MemberID    *uuid.NullUUID `json:"member_id"`
	Status      *string        `json:"status"`
}

func (q *Queries) ListAdHocTasks(ctx context.Context, arg ListAdHocTasksParams) ([]AdHocTask, error) {
	rows, err := q.db.Query(ctx, listAdHocTasks, arg.HouseholdID, arg.MemberID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdHocTask{}
	for rows.Next() {
		var i AdHocTask
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.Name,
			&i.PayoutCents,
			&i.RequiresApproval,
			&i.Status,
			&i.CreatedByAccountID,
			&i.CompletedAt,
			&i.ApprovedAt,
			&i.ApprovedByAccountID,
			&i.DeclineReason,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllowances = `-- name: ListAllowances :many
SELECT DISTINCT ON (member_id) id, household_id, member_id, amount_cents, active_from, created_at
FROM allowance_settings
WHERE household_id = $1 AND active_from <= CURRENT_DATE
ORDER BY member_id, active_from DESC
`

func (q *Queries) ListAllowances(ctx context.Context, householdID uuid.UUID) ([]AllowanceSetting, error) {
	rows, err := q.db.Query(ctx, listAllowances, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllowanceSetting{}
	for rows.Next() {
		var i AllowanceSetting
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.AmountCents,
			&i.ActiveFrom,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersInHousehold = `-- name: ListMembersInHousehold :many
SELECT id FROM members WHERE household_id = $1
`

func (q *Queries) ListMembersInHousehold(ctx context.Context, householdID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMembersInHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, wallet_id, member_id, amount_cents, kind, reference_id, reason, created_by_account_id, created_at FROM wallet_transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID uuid.UUID `json:"wallet_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTransaction{}
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.MemberID,
			&i.AmountCents,
			&i.Kind,
			&i.ReferenceID,
			&i.Reason,
			&i.CreatedByAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAdHocTaskCompleted = `-- name: MarkAdHocTaskCompleted :one
UPDATE ad_hoc_tasks
SET status = 'pending', completed_at = NOW()
WHERE id = $1 AND household_id = $2 AND status = 'open'
RETURNING id, household_id, member_id, name, payout_cents, requires_approval, status, created_by_account_id, completed_at, approved_at, approved_by_account_id, decline_reason, expires_at, created_at
`

type MarkAdHocTaskCompletedParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) MarkAdHocTaskCompleted(ctx context.Context, arg MarkAdHocTaskCompletedParams) (AdHocTask, error) {
	row := q.db.QueryRow(ctx, markAdHocTaskCompleted, arg.ID, arg.HouseholdID)
	var i AdHocTask
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.Name,
		&i.PayoutCents,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedByAccountID,
		&i.CompletedAt,
		&i.ApprovedAt,
		&i.ApprovedByAccountID,
		&i.DeclineReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const recomputeWalletBalance = `-- name: RecomputeWalletBalance :one
WITH ledger AS (
  SELECT COALESCE(SUM(wt.amount_cents), 0)::BIGINT AS s
  FROM wallet_transactions wt
  WHERE wt.member_id = $1
)
UPDATE wallets SET balance_cents = (SELECT s FROM ledger), updated_at = NOW()
WHERE wallets.member_id = $1
RETURNING id, member_id, balance_cents, updated_at
`

func (q *Queries) RecomputeWalletBalance(ctx context.Context, memberID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, recomputeWalletBalance, memberID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BalanceCents,
		&i.UpdatedAt,
	)
	return i, err
}

const sumChorePayoutsForChoreInWeek = `-- name: SumChorePayoutsForChoreInWeek :one
SELECT COALESCE(SUM(wt.amount_cents), 0)::BIGINT AS total
FROM wallet_transactions wt
WHERE wt.member_id = $1
  AND wt.kind = 'chore_payout'
  AND wt.reference_id IN (
    SELECT cc.id FROM chore_completions cc
    WHERE cc.chore_id = $2 AND cc.date BETWEEN $3 AND $4
  )
`

type SumChorePayoutsForChoreInWeekParams struct {
	MemberID uuid.UUID   `json:"member_id"`
	ChoreID  uuid.UUID   `json:"chore_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

func (q *Queries) SumChorePayoutsForChoreInWeek(ctx context.Context, arg SumChorePayoutsForChoreInWeekParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumChorePayoutsForChoreInWeek,
		arg.MemberID,
		arg.ChoreID,
		arg.Date,
		arg.Date_2,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const upsertAllowance = `-- name: UpsertAllowance :one
INSERT INTO allowance_settings (id, household_id, member_id, amount_cents, active_from)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, household_id, member_id, amount_cents, active_from, created_at
`

type UpsertAllowanceParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	MemberID    uuid.UUID   `json:"member_id"`
	AmountCents int64       `json:"amount_cents"`
	ActiveFrom  pgtype.Date `json:"active_from"`
}

func (q *Queries) UpsertAllowance(ctx context.Context, arg UpsertAllowanceParams) (AllowanceSetting, error) {
	row := q.db.QueryRow(ctx, upsertAllowance,
		arg.HouseholdID,
		arg.MemberID,
		arg.AmountCents,
		arg.ActiveFrom,
	)
	var i AllowanceSetting
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.AmountCents,
		&i.ActiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWeeklySummary = `-- name: UpsertWeeklySummary :one

INSERT INTO weekly_summaries (
    id, household_id, member_id, week_start, earned_cents, streak_bonus_cents, chores_completed, chores_possible
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (member_id, week_start) DO UPDATE
  SET earned_cents = EXCLUDED.earned_cents,
      streak_bonus_cents = EXCLUDED.streak_bonus_cents,
      chores_completed = EXCLUDED.chores_completed,
      chores_possible = EXCLUDED.chores_possible
RETURNING id, household_id, member_id, week_start, earned_cents, streak_bonus_cents, chores_completed, chores_possible, created_at
`

type UpsertWeeklySummaryParams struct {
	HouseholdID      uuid.UUID   `json:"household_id"`
	MemberID         uuid.UUID   `json:"member_id"`
	WeekStart        pgtype.Date `json:"week_start"`
	EarnedCents      int64       `json:"earned_cents"`
	StreakBonusCents int64       `json:"streak_bonus_cents"`
	ChoresCompleted  int32       `json:"chores_completed"`
	ChoresPossible   int32       `json:"chores_possible"`
}

// ── Weekly summaries ─────────────────────────────────────────────────────────
func (q *Queries) UpsertWeeklySummary(ctx context.Context, arg UpsertWeeklySummaryParams) (WeeklySummary, error) {
	row := q.db.QueryRow(ctx, upsertWeeklySummary,
		arg.HouseholdID,
		arg.MemberID,
		arg.WeekStart,
		arg.EarnedCents,
		arg.StreakBonusCents,
		arg.ChoresCompleted,
		arg.ChoresPossible,
	)
	var i WeeklySummary
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.WeekStart,
		&i.EarnedCents,
		&i.StreakBonusCents,
		&i.ChoresCompleted,
		&i.ChoresPossible,
		&i.CreatedAt,
	)
	return i, err
}
